#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
正确添加缺失领域法术到 spells-data.js
方法：直接用 Python 生成格式正确的 JS 文本，插入到 ]; 之前
"""

import re
import shutil
import os

# ─── 完整的66个缺失法术数据 ───
# 格式：每个法术是一个 dict，对应 JS 对象
SPELLS_DATA = [

    # ════════════════ 气领域 (Air) ════════════════
    {
        "id": "obscuring_mist",
        "nameEn": "Obscuring Mist",
        "nameZh": "迷雾术",
        "level": 1,
        "school": "咒法系",
        "subschool": "创造",
        "descriptor": "",
        "components": "V, S",
        "castingTime": "标准动作",
        "range": "近距 (25尺+5尺/2环)",
        "target": "以你为中心的弥散范围",
        "duration": "1分钟/环",
        "savingThrow": "无",
        "spellResist": "否",
        "desc": "你周围会弥漫一股浓密的雾气，使所有穿过该区域的生物的有效视野缩短至5尺。远程攻击无法穿过迷雾，侦测类和侦察检定会受到-5惩罚。",
        "arcane": {"wizard": 1, "sorcerer": 1},
        "divine": {"cleric": 1, "druid": 1},
        "classes": {"wizard": 1, "sorcerer": 1, "cleric": 1, "druid": 1},
    },
    {
        "id": "air_walk",
        "nameEn": "Air Walk",
        "nameZh": "空气行走",
        "level": 4,
        "school": "变化系",
        "subschool": "",
        "descriptor": "",
        "components": "V, S, DF",
        "castingTime": "标准动作",
        "range": "触碰",
        "target": "触碰的生物",
        "duration": "10分钟/环",
        "savingThrow": "意志过则无效（无害）",
        "spellResist": "是（无害）",
        "desc": "受术者能在空中行走，如同在坚实的地面上一般。受术者不会坠落，并获得飞行速度（机动性：完美）。",
        "arcane": {"wizard": 4, "sorcerer": 4},
        "divine": {"cleric": 4, "druid": 4},
        "classes": {"wizard": 4, "sorcerer": 4, "cleric": 4, "druid": 4},
    },
    {
        "id": "control_winds",
        "nameEn": "Control Winds",
        "nameZh": "控制风力",
        "level": 5,
        "school": "变化系",
        "subschool": "",
        "descriptor": "",
        "components": "V, S, DF",
        "castingTime": "标准动作",
        "range": "近距 (25尺+5尺/2环)",
        "target": "以你为中心，半径100尺的弥散区域",
        "duration": "10分钟/环",
        "savingThrow": "强韧过则减半",
        "spellResist": "否",
        "desc": "你改变天然风的速度和方向，最高可达飓风级别（风速110尺）。强风会阻碍飞行、远程攻击和声音传达。",
        "arcane": None,
        "divine": {"druid": 5},
        "classes": {"druid": 5},
    },

    # ════════════════ 动物领域 (Animal) ════════════════
    {
        "id": "calm_animals",
        "nameEn": "Calm Animals",
        "nameZh": "安抚动物",
        "level": 1,
        "school": "惑控系",
        "subschool": "强迫",
        "descriptor": "[影响心灵]",
        "components": "V, S, DF",
        "castingTime": "标准动作",
        "range": "近距 (25尺+5尺/2环)",
        "target": "至多每等级1只动物的放射区域",
        "duration": "专注",
        "savingThrow": "意志过则无效",
        "spellResist": "是",
        "desc": "该法术可以使动物平静下来，使其不会攻击或逃跑。平静的动物无法攻击或施展任何攻击性行动，但它们会保护自己。",
        "arcane": None,
        "divine": {"druid": 1, "ranger": 1},
        "classes": {"druid": 1, "ranger": 1},
    },
    {
        "id": "hold_animal",
        "nameEn": "Hold Animal",
        "nameZh": "禁锢动物",
        "level": 2,
        "school": "惑控系",
        "subschool": "强迫",
        "descriptor": "[影响心灵]",
        "components": "V, S, DF",
        "castingTime": "标准动作",
        "range": "中距 (100尺+10尺/环)",
        "target": "一个动物",
        "duration": "1轮/环",
        "savingThrow": "意志过则无效",
        "spellResist": "是",
        "desc": "你使一个动物无法移动。受术动物不能行动，但可以进行豁免检定。如果受到伤害，它可以尝试新的意志豁免来打破控制。",
        "arcane": None,
        "divine": {"druid": 2, "ranger": 2},
        "classes": {"druid": 2, "ranger": 2},
    },
    {
        "id": "dominate_animal",
        "nameEn": "Dominate Animal",
        "nameZh": "支配动物",
        "level": 3,
        "school": "惑控系",
        "subschool": "强迫",
        "descriptor": "[影响心灵]",
        "components": "V, S",
        "castingTime": "标准动作",
        "range": "近距 (25尺+5尺/2环)",
        "target": "一个动物",
        "duration": "1轮/环",
        "savingThrow": "意志过则无效",
        "spellResist": "是",
        "desc": "你在精神上控制一个动物。你可以使它执行任何你所说的行动（最多一个句子）。受术者不会执行明显有害的行动。",
        "arcane": None,
        "divine": {"druid": 3},
        "classes": {"druid": 3},
    },
    {
        "id": "summon_natures_ally_4",
        "nameEn": "Summon Natures Ally IV",
        "nameZh": "召唤自然盟友 IV",
        "level": 4,
        "school": "咒法系",
        "subschool": "召唤",
        "descriptor": "",
        "components": "V, S, DF",
        "castingTime": "标准动作（见描述）",
        "range": "近距 (25尺+5尺/2环)",
        "target": "见描述",
        "duration": "1轮/环（D）",
        "savingThrow": "无",
        "spellResist": "否",
        "desc": "你召唤一个自然生物为你作战，总计不超过4 HD。召唤的生物在你的指挥下行动，法术施展后立即出现。",
        "arcane": None,
        "divine": {"druid": 4, "ranger": 4},
        "classes": {"druid": 4, "ranger": 4},
    },
    {
        "id": "antilife_shell",
        "nameEn": "Antilife Shell",
        "nameZh": "反生命壳",
        "level": 6,
        "school": "防护系",
        "subschool": "",
        "descriptor": "",
        "components": "V, S, DF",
        "castingTime": "标准动作",
        "range": "10尺",
        "target": "以你为中心，半径10尺的弥散区域",
        "duration": "1轮/环（D）",
        "savingThrow": "无",
        "spellResist": "否",
        "desc": "你创造一个排斥所有活物的壳。任何活着的生物都无法穿过这个壳。不死生物、构装生物、元素生物和泥形生物不受影响。",
        "arcane": None,
        "divine": {"druid": 6},
        "classes": {"druid": 6},
    },
    {
        "id": "animal_shapes",
        "nameEn": "Animal Shapes",
        "nameZh": "动物形态",
        "level": 7,
        "school": "变化系",
        "subschool": "变身",
        "descriptor": "",
        "components": "V, S, DF",
        "castingTime": "标准动作",
        "range": "近距 (25尺+5尺/2环)",
        "target": "至多每等级1个自愿生物",
        "duration": "1小时/环（D）",
        "savingThrow": "无",
        "spellResist": "否",
        "desc": "你可以将自愿的生物变成任何你选择的动物形态。每个目标变成同一种动物，保留自己的属性，但获得所变动物的天然武器和特殊能力。",
        "arcane": None,
        "divine": {"druid": 7},
        "classes": {"druid": 7},
    },

    # ════════════════ 混乱领域 (Chaos) ════════════════
    {
        "id": "protection_from_law",
        "nameEn": "Protection from Law",
        "nameZh": "防护律法",
        "level": 1,
        "school": "防护系",
        "subschool": "",
        "descriptor": "[律法]",
        "components": "V, S, DF",
        "castingTime": "标准动作",
        "range": "触碰",
        "target": "触碰的生物",
        "duration": "1分钟/环",
        "savingThrow": "意志过则无效（无害）",
        "spellResist": "是（无害）",
        "desc": "该法术在受术者周围创造一个魔法屏障，保护其免受守序生物的攻击。受术者对守序生物的攻击有+2偏斜加值，对守序生物的法术有+2抗性加值。",
        "arcane": None,
        "divine": {"cleric": 1},
        "classes": {"cleric": 1},
    },
    {
        "id": "chaos_hammer",
        "nameEn": "Chaos Hammer",
        "nameZh": "混乱之锤",
        "level": 4,
        "school": "塑能系",
        "subschool": "",
        "descriptor": "[混乱][声波]",
        "components": "V, S",
        "castingTime": "标准动作",
        "range": "近距 (25尺+5尺/2环)",
        "target": "至多每3等级1个守序生物的放射区域",
        "duration": "瞬时",
        "savingThrow": "强韧过则减半",
        "spellResist": "是",
        "desc": "你发射一道混乱能量的冲击波，对守序生物造成1d8点伤害每2施法者等级（最高5d8）。守序生物如果未能通过强韧检定，会耳聋1d4轮。",
        "arcane": None,
        "divine": {"cleric": 4},
        "classes": {"cleric": 4},
    },
    {
        "id": "animate_objects",
        "nameEn": "Animate Objects",
        "nameZh": "活化物体",
        "level": 6,
        "school": "变化系",
        "subschool": "",
        "descriptor": "",
        "components": "V, S, M",
        "castingTime": "标准动作",
        "range": "中距 (100尺+10尺/环)",
        "target": "见描述",
        "duration": "1轮/环",
        "savingThrow": "无",
        "spellResist": "否",
        "desc": "你使无生命物体变成你的仆从。你可以活化至多每等级25磅重量的物体，活化的物体会攻击你的敌人或执行你的命令。",
        "material": "一个槐木树枝",
        "arcane": {"wizard": 6, "sorcerer": 6},
        "divine": None,
        "classes": {"wizard": 6, "sorcerer": 6},
    },
    {
        "id": "cloak_of_chaos",
        "nameEn": "Cloak of Chaos",
        "nameZh": "混乱之袍",
        "level": 8,
        "school": "防护系",
        "subschool": "",
        "descriptor": "[混乱]",
        "components": "V, S, DF",
        "castingTime": "标准动作",
        "range": "近距 (25尺+5尺/2环)",
        "target": "见描述",
        "duration": "1轮/环（D）",
        "savingThrow": "见描述",
        "spellResist": "是（见描述）",
        "desc": "该法术的功能如同混乱版的法术抗力护盾。所有受影响的目标对守序法术和类法术能力有+4抗力加值，对守序生物的魅惑和胁迫效果有抗性。",
        "arcane": None,
        "divine": {"cleric": 8},
        "classes": {"cleric": 8},
    },

    # ════════════════ 死亡领域 (Death) ════════════════
    {
        "id": "death_knell",
        "nameEn": "Death Knell",
        "nameZh": "死亡丧钟",
        "level": 2,
        "school": "死灵系",
        "subschool": "",
        "descriptor": "[死亡][邪恶]",
        "components": "V, S",
        "castingTime": "标准动作",
        "range": "中距 (100尺+10尺/环)",
        "target": "一个生命骰小于你的生物",
        "duration": "瞬时（见描述）",
        "savingThrow": "意志过则无效",
        "spellResist": "是",
        "desc": "你吸取濒死生物的生命力。如果目标因该法术死亡，你获得1d8点临时生命值和+1施法者等级（用于所有目的），持续1小时。",
        "arcane": None,
        "divine": {"cleric": 2},
        "classes": {"cleric": 2},
    },
    {
        "id": "create_greater_undead",
        "nameEn": "Create Greater Undead",
        "nameZh": "创造高等亡灵",
        "level": 8,
        "school": "死灵系",
        "subschool": "创造",
        "descriptor": "[邪恶]",
        "components": "V, S, M",
        "castingTime": "1分钟",
        "range": "近距 (25尺+5尺/2环)",
        "target": "见描述",
        "duration": "瞬时",
        "savingThrow": "无",
        "spellResist": "否",
        "desc": "你创造一个高等亡灵生物（如幽魂、吸血鬼、巫妖或木乃伊）。你每天可以创造一个HD不超过4倍施法者等级的亡灵。",
        "material": "一个装有至少25gp价值的黄金或宝石的容器",
        "arcane": {"wizard": 8, "sorcerer": 8},
        "divine": {"cleric": 8},
        "classes": {"wizard": 8, "sorcerer": 8, "cleric": 8},
    },

    # ════════════════ 土领域 (Earth) ════════════════
    {
        "id": "magic_stone",
        "nameEn": "Magic Stone",
        "nameZh": "魔法石",
        "level": 1,
        "school": "变化系",
        "subschool": "",
        "descriptor": "",
        "components": "V, S, DF",
        "castingTime": "标准动作",
        "range": "触碰",
        "target": "至多3颗石头",
        "duration": "30分钟或直到发射",
        "savingThrow": "无",
        "spellResist": "否",
        "desc": "你对至多3颗普通石头施展魔法。你可以将这些石头当作远程武器投掷（射程增量20尺），造成1d6+1点钝击伤害（对中型和更大生物）。",
        "arcane": None,
        "divine": {"druid": 1, "cleric": 1},
        "classes": {"druid": 1, "cleric": 1},
    },
    {
        "id": "soften_earth_and_stone",
        "nameEn": "Soften Earth and Stone",
        "nameZh": "软化泥土与岩石",
        "level": 2,
        "school": "变化系",
        "subschool": "",
        "descriptor": "",
        "components": "V, S, DF",
        "castingTime": "标准动作",
        "range": "近距 (25尺+5尺/2环)",
        "target": "至多每等级10立方尺的泥土或岩石",
        "duration": "瞬时",
        "savingThrow": "见描述",
        "spellResist": "否",
        "desc": "你使泥土变成软泥，或使岩石变成软土。软化后的泥土或岩石可以被徒手挖掘。陷入软化泥土的生物可以通过强韧检定（DC15）逃脱。",
        "arcane": None,
        "divine": {"druid": 2},
        "classes": {"druid": 2},
    },
    {
        "id": "stone_shape",
        "nameEn": "Stone Shape",
        "nameZh": "塑石术",
        "level": 3,
        "school": "变化系",
        "subschool": "",
        "descriptor": "",
        "components": "V, S, DF",
        "castingTime": "标准动作",
        "range": "触碰",
        "target": "至多每等级1立方尺的石头",
        "duration": "瞬时",
        "savingThrow": "无",
        "spellResist": "否",
        "desc": "你改变石头的形状。你可以将一块石头塑造成任何你想要的形状——台阶、洞穴、石椅等。该法术不能创造移动的机械或复杂装置。",
        "arcane": {"wizard": 3, "sorcerer": 3},
        "divine": {"cleric": 3, "druid": 3},
        "classes": {"wizard": 3, "sorcerer": 3, "cleric": 3, "druid": 3},
    },
    {
        "id": "spike_stones",
        "nameEn": "Spike Stones",
        "nameZh": "尖石术",
        "level": 4,
        "school": "塑能系",
        "subschool": "",
        "descriptor": "",
        "components": "V, S, DF",
        "castingTime": "标准动作",
        "range": "近距 (25尺+5尺/2环)",
        "target": "以你为中心，半径20尺的弥散区域",
        "duration": "1小时/环（D）",
        "savingThrow": "无",
        "spellResist": "否",
        "desc": "你在地面上创造尖锐的石笋。穿过该区域的生物有可能被绊倒（敏捷检定DC15），失败则跌倒并受到1d8点穿刺伤害。",
        "arcane": None,
        "divine": {"druid": 4},
        "classes": {"druid": 4},
    },
    {
        "id": "stoneskin",
        "nameEn": "Stoneskin",
        "nameZh": "石肤术",
        "level": 6,
        "school": "变化系",
        "subschool": "",
        "descriptor": "",
        "components": "V, S, M",
        "castingTime": "标准动作",
        "range": "触碰",
        "target": "触碰的生物",
        "duration": "10分钟/环或直到被穿透",
        "savingThrow": "意志过则无效（无害）",
        "spellResist": "是（无害）",
        "desc": "受术者的皮肤变成石头般的质地，获得伤害减免10/钝击或穿刺。该法术持续直到吸收的伤害总量达到10点每施法者等级（最高150点）。",
        "material": "一块花岗岩、砂岩或石灰岩，以及一瓶价值150gp的澄清水",
        "arcane": {"wizard": 6, "sorcerer": 6},
        "divine": {"cleric": 6, "druid": 6},
        "classes": {"wizard": 6, "sorcerer": 6, "cleric": 6, "druid": 6},
    },
    {
        "id": "iron_body",
        "nameEn": "Iron Body",
        "nameZh": "铁躯术",
        "level": 8,
        "school": "变化系",
        "subschool": "",
        "descriptor": "",
        "components": "V, S, M",
        "castingTime": "标准动作",
        "range": "触碰",
        "target": "触碰的生物",
        "duration": "1分钟/环（D）",
        "savingThrow": "意志过则无效（无害）",
        "spellResist": "是（无害）",
        "desc": "你的身体变成生铁。你获得伤害减免15/钝击，对音波、毒、意念结合的豁免检定有+6增强加值，并且不受重击或夹击。你的速度减少至基础的3/4。",
        "material": "一小块铁和一小瓶价值100gp的粘性油",
        "arcane": {"wizard": 8, "sorcerer": 8},
        "divine": None,
        "classes": {"wizard": 8, "sorcerer": 8},
    },

    # ════════════════ 邪恶领域 (Evil) ════════════════
    {
        "id": "protection_from_good",
        "nameEn": "Protection from Good",
        "nameZh": "防护善良",
        "level": 1,
        "school": "防护系",
        "subschool": "",
        "descriptor": "[善良]",
        "components": "V, S, DF",
        "castingTime": "标准动作",
        "range": "触碰",
        "target": "触碰的生物",
        "duration": "1分钟/环",
        "savingThrow": "意志过则无效（无害）",
        "spellResist": "是（无害）",
        "desc": "该法术在受术者周围创造一个魔法屏障，保护其免受善良生物的攻击。受术者对善良生物的攻击有+2偏斜加值，对善良生物的法术有+2抗性加值。",
        "arcane": None,
        "divine": {"cleric": 1},
        "classes": {"cleric": 1},
    },
    {
        "id": "desecrate",
        "nameEn": "Desecrate",
        "nameZh": "污秽之地",
        "level": 2,
        "school": "咒法系",
        "subschool": "创造",
        "descriptor": "[邪恶]",
        "components": "V, S, M",
        "castingTime": "标准动作",
        "range": "近距 (25尺+5尺/2环)",
        "target": "以你为中心，半径60尺的弥散区域",
        "duration": "2小时/环（D）",
        "savingThrow": "无",
        "spellResist": "否",
        "desc": "你污秽一片区域，使之对邪恶生物（包括不死生物）变得有利。在该区域内的邪恶生物在攻击和伤害骰上有+1亵渎加值，豁免检定有+3亵渎加值。",
        "material": "一些奉献给邪恶神祗的物品，价值至少25gp",
        "arcane": None,
        "divine": {"cleric": 2},
        "classes": {"cleric": 2},
    },
    {
        "id": "dispel_good",
        "nameEn": "Dispel Good",
        "nameZh": "驱散善良",
        "level": 5,
        "school": "塑能系",
        "subschool": "",
        "descriptor": "[邪恶]",
        "components": "V, S, DF",
        "castingTime": "标准动作",
        "range": "近距 (25尺+5尺/2环)",
        "target": "一个善良生物",
        "duration": "瞬时",
        "savingThrow": "见描述",
        "spellResist": "是",
        "desc": "该法术的功能如同驱散守序，但针对善良生物。你尝试驱散善良生物身上的护盾和祝福法术。",
        "arcane": None,
        "divine": {"cleric": 5},
        "classes": {"cleric": 5},
    },
    {
        "id": "blasphemy",
        "nameEn": "Blasphemy",
        "nameZh": "亵渎之言",
        "level": 7,
        "school": "塑能系",
        "subschool": "",
        "descriptor": "[邪恶][音波][影响心灵]",
        "components": "V",
        "castingTime": "标准动作",
        "range": "40尺半径",
        "target": "放射区域内所有善良生物",
        "duration": "瞬时",
        "savingThrow": "无或意志过则无害（见描述）",
        "spellResist": "是",
        "desc": "你说出亵渎的言辞，使善良生物受到不同影响，取决于其生命骰数：小于施法者等级的生物立即死亡；其余善良生物被震慑或眩晕。",
        "arcane": None,
        "divine": {"cleric": 7},
        "classes": {"cleric": 7},
    },

    # ════════════════ 火领域 (Fire) ════════════════
    {
        "id": "produce_flame",
        "nameEn": "Produce Flame",
        "nameZh": "产生火焰",
        "level": 2,
        "school": "塑能系",
        "subschool": "",
        "descriptor": "[火]",
        "components": "V, S",
        "castingTime": "标准动作",
        "range": "0尺",
        "target": "一个火焰球",
        "duration": "1轮/环（见描述）",
        "savingThrow": "无",
        "spellResist": "是",
        "desc": "你创造出一团火焰在手中燃烧。这团火焰不会伤害你。你可以将火焰投掷向目标，造成1d6+1点火系伤害每施法者等级（最高5d6+5）。",
        "arcane": None,
        "divine": {"druid": 2},
        "classes": {"druid": 2},
    },

    # ════════════════ 善良领域 (Good) ════════════════
    {
        "id": "holy_smite",
        "nameEn": "Holy Smite",
        "nameZh": "神圣重击",
        "level": 4,
        "school": "塑能系",
        "subschool": "",
        "descriptor": "[善良][光亮]",
        "components": "V, S, DF",
        "castingTime": "标准动作",
        "range": "近距 (25尺+5尺/2环)",
        "target": "至多每3等级1个邪恶生物的放射区域",
        "duration": "瞬时",
        "savingThrow": "无或反射过则减半（见描述）",
        "spellResist": "是",
        "desc": "你释放出一股神圣的能量，对邪恶生物造成2d8点伤害每3施法者等级（最高10d8）。受影响的邪恶生物如果未能通过反射检定，会目盲1轮。",
        "arcane": None,
        "divine": {"cleric": 4},
        "classes": {"cleric": 4},
    },
    {
        "id": "dispel_evil",
        "nameEn": "Dispel Evil",
        "nameZh": "驱散邪恶",
        "level": 5,
        "school": "塑能系",
        "subschool": "",
        "descriptor": "[善良]",
        "components": "V, S, DF",
        "castingTime": "标准动作",
        "range": "近距 (25尺+5尺/2环)",
        "target": "一个邪恶生物",
        "duration": "瞬时",
        "savingThrow": "见描述",
        "spellResist": "是",
        "desc": "该法术的功能如同驱散混乱，但针对邪恶生物。你尝试驱散邪恶生物身上的诅咒和腐化法术。此外，该法术可以驱散邪恶异位面生物。",
        "arcane": None,
        "divine": {"cleric": 5},
        "classes": {"cleric": 5},
    },
    {
        "id": "blade_barrier",
        "nameEn": "Blade Barrier",
        "nameZh": "刀刃壁垒",
        "level": 6,
        "school": "塑能系",
        "subschool": "",
        "descriptor": "",
        "components": "V, S, M/DF",
        "castingTime": "标准动作",
        "range": "中距 (100尺+10尺/环)",
        "target": "见描述",
        "duration": "1轮/环（D）",
        "savingThrow": "反射过则减半",
        "spellResist": "是",
        "desc": "你创造出一道旋转的刀刃壁。你可以使刀刃壁呈直线（最长20尺，宽5尺）或呈圆柱（半径5尺，高20尺）。任何穿过刀刃壁的生物受到伤害。",
        "material": "一个小剪刀碎片",
        "arcane": None,
        "divine": {"cleric": 6},
        "classes": {"cleric": 6},
    },
    {
        "id": "holy_word",
        "nameEn": "Holy Word",
        "nameZh": "神圣之言",
        "level": 7,
        "school": "塑能系",
        "subschool": "",
        "descriptor": "[善良][音波][影响心灵]",
        "components": "V",
        "castingTime": "标准动作",
        "range": "40尺半径",
        "target": "放射区域内所有邪恶生物",
        "duration": "瞬时",
        "savingThrow": "无或意志过则无害（见描述）",
        "spellResist": "是",
        "desc": "你说出神圣的言辞，使邪恶生物受到不同影响，取决于其生命骰数：小于施法者等级的生物立即死亡；其余邪恶生物被震慑或眩晕。",
        "arcane": None,
        "divine": {"cleric": 7},
        "classes": {"cleric": 7},
    },

    # ════════════════ 知识领域 (Knowledge) ════════════════
    {
        "id": "detect_thoughts",
        "nameEn": "Detect Thoughts",
        "nameZh": "侦测思想",
        "level": 2,
        "school": "预言系",
        "subschool": "心灵感应",
        "descriptor": "[影响心灵][语言依赖]",
        "components": "V, S, M",
        "castingTime": "标准动作",
        "range": "60尺",
        "target": "锥形区域",
        "duration": "专注，最长1分钟/环",
        "savingThrow": "意志过则无效",
        "spellResist": "是",
        "desc": "你侦测到60尺锥形区域内生物表面的思想。你可以指定一个方向进行侦测。被侦测的生物如果通过意志豁免，在该轮内不再受影响。",
        "material": "一小片铅片",
        "arcane": {"wizard": 2, "sorcerer": 2, "bard": 2},
        "divine": None,
        "classes": {"wizard": 2, "sorcerer": 2, "bard": 2},
    },
    {
        "id": "discern_location",
        "nameEn": "Discern Location",
        "nameZh": "辨位术",
        "level": 8,
        "school": "预言系",
        "subschool": "",
        "descriptor": "",
        "components": "V, S, DF",
        "castingTime": "标准动作",
        "range": "无限制",
        "target": "一个生物、物件或地点",
        "duration": "瞬时",
        "savingThrow": "无",
        "spellResist": "否",
        "desc": "你精确知道一个生物、物件或地点的位置。该法术不需要对你想定位的目标有直接的感知或了解。任何魔法屏障都不能阻挡该法术。",
        "arcane": {"wizard": 8, "sorcerer": 8},
        "divine": {"cleric": 8},
        "classes": {"wizard": 8, "sorcerer": 8, "cleric": 8},
    },

    # ════════════════ 守序领域 (Law) ════════════════
    {
        "id": "protection_from_chaos",
        "nameEn": "Protection from Chaos",
        "nameZh": "防护混乱",
        "level": 1,
        "school": "防护系",
        "subschool": "",
        "descriptor": "[混乱]",
        "components": "V, S, DF",
        "castingTime": "标准动作",
        "range": "触碰",
        "target": "触碰的生物",
        "duration": "1分钟/环",
        "savingThrow": "意志过则无效（无害）",
        "spellResist": "是（无害）",
        "desc": "该法术在受术者周围创造一个魔法屏障，保护其免受混乱生物的攻击。受术者对混乱生物的攻击有+2偏斜加值，对混乱生物的法术有+2抗性加值。",
        "arcane": None,
        "divine": {"cleric": 1},
        "classes": {"cleric": 1},
    },
    {
        "id": "calm_emotions",
        "nameEn": "Calm Emotions",
        "nameZh": "平静情绪",
        "level": 2,
        "school": "惑控系",
        "subschool": "强迫",
        "descriptor": "[影响心灵]",
        "components": "V, S, M/DF",
        "castingTime": "标准动作",
        "range": "近距 (25尺+5尺/2环)",
        "target": "至多每等级1个生物的放射区域",
        "duration": "专注，最长1轮/环",
        "savingThrow": "意志过则无效",
        "spellResist": "是",
        "desc": "该法术使受影响目标的情绪平静下来。受术者不会进行攻击动作，也不会施展攻击性法术。该法术可以压制魅惑和恐惧效果。",
        "material": "一块纯雪花石膏",
        "arcane": {"bard": 2},
        "divine": {"cleric": 2},
        "classes": {"bard": 2, "cleric": 2},
    },
    {
        "id": "orders_wrath",
        "nameEn": "Order's Wrath",
        "nameZh": "秩序之怒",
        "level": 4,
        "school": "塑能系",
        "subschool": "",
        "descriptor": "[守序][声波]",
        "components": "V, S, DF",
        "castingTime": "标准动作",
        "range": "近距 (25尺+5尺/2环)",
        "target": "至多每3等级1个混乱生物的放射区域",
        "duration": "瞬时",
        "savingThrow": "强韧过则减半（见描述）",
        "spellResist": "是",
        "desc": "你发射一道守序能量的冲击波，对混乱生物造成1d8点伤害每2施法者等级（最高5d8）。混乱生物如果未能通过强韧检定，会耳聋1d4轮。",
        "arcane": None,
        "divine": {"cleric": 4},
        "classes": {"cleric": 4},
    },
    {
        "id": "dispel_chaos",
        "nameEn": "Dispel Chaos",
        "nameZh": "驱散混乱",
        "level": 5,
        "school": "塑能系",
        "subschool": "",
        "descriptor": "[守序]",
        "components": "V, S, DF",
        "castingTime": "标准动作",
        "range": "近距 (25尺+5尺/2环)",
        "target": "一个混乱生物",
        "duration": "瞬时",
        "savingThrow": "见描述",
        "spellResist": "是",
        "desc": "该法术的功能如同驱散邪恶，但针对混乱生物。你尝试驱散混乱生物身上的腐化和混乱法术。此外，该法术可以驱散混乱异位面生物。",
        "arcane": None,
        "divine": {"cleric": 5},
        "classes": {"cleric": 5},
    },

    # ════════════════ 魔法领域 (Magic) ════════════════
    {
        "id": "magic_aura",
        "nameEn": "Magic Aura",
        "nameZh": "魔法灵光",
        "level": 1,
        "school": "咒法系",
        "subschool": "创造",
        "descriptor": "",
        "components": "V, S, M/DF",
        "castingTime": "标准动作",
        "range": "触碰",
        "target": "触碰的一件物品或至多每等级1立方尺的物品",
        "duration": "1天/环",
        "savingThrow": "无",
        "spellResist": "否",
        "desc": "你对一件物品施加魔法灵光，使其对侦测魔法显示出虚假的信息。你可以使物品看起来有魔法、没有魔法，或者属于某个特定的学派。",
        "material": "一小撮价值50gp或更贵的粉末",
        "arcane": {"wizard": 1, "sorcerer": 1},
        "divine": None,
        "classes": {"wizard": 1, "sorcerer": 1},
    },
    {
        "id": "imbue_with_spell_ability",
        "nameEn": "Imbue with Spell Ability",
        "nameZh": "赋予法术能力",
        "level": 4,
        "school": "变化系",
        "subschool": "",
        "descriptor": "",
        "components": "V, S, M/DF",
        "castingTime": "1小时",
        "range": "触碰",
        "target": "触碰的生物",
        "duration": "24小时（见描述）或直到能量被用完",
        "savingThrow": "意志过则无效（无害）",
        "spellResist": "是（无害）",
        "desc": "你从自己身上吸取准备好的法术，赋予受术者使用这些法术的能力。你每天可以赋予的法术总数等于你的施法者等级。",
        "material": "有价值100gp的宝石",
        "arcane": None,
        "divine": {"cleric": 4},
        "classes": {"cleric": 4},
    },
    {
        "id": "protection_from_spells",
        "nameEn": "Protection from Spells",
        "nameZh": "防护法术",
        "level": 8,
        "school": "防护系",
        "subschool": "",
        "descriptor": "",
        "components": "V, S, M/DF",
        "castingTime": "标准动作",
        "range": "触碰",
        "target": "触碰的生物",
        "duration": "1轮/环",
        "savingThrow": "意志过则无效（无害）",
        "spellResist": "是（无害）",
        "desc": "受术者对法术和类法术能力有等级抗力。每当一个法术或类法术能力以受术者为目标，受术者可以进行等级检定来对抗该法术的DC。",
        "material": "一瓶价值500gp的珍珠粉末",
        "arcane": None,
        "divine": {"cleric": 8},
        "classes": {"cleric": 8},
    },
    {
        "id": "mages_disjunction",
        "nameEn": "Mage's Disjunction",
        "nameZh": "法师裂解术",
        "level": 9,
        "school": "咒法系",
        "subschool": "创造",
        "descriptor": "",
        "components": "V",
        "castingTime": "标准动作",
        "range": "近距 (25尺+5尺/2环)",
        "target": "以你为中心，半径40尺的弥散区域",
        "duration": "瞬时",
        "savingThrow": "见描述",
        "spellResist": "否",
        "desc": "该法术是最强大的反魔法法术。区域内所有的魔法效果和魔法物品有2%的几率每施法者等级被解除（最高90%）。该法术还能解除反魔法场。",
        "arcane": {"wizard": 9, "sorcerer": 9},
        "divine": None,
        "classes": {"wizard": 9, "sorcerer": 9},
    },

    # ════════════════ 植物领域 (Plant) ════════════════
    {
        "id": "entangle",
        "nameEn": "Entangle",
        "nameZh": "纠缠术",
        "level": 1,
        "school": "咒法系",
        "subschool": "召唤",
        "descriptor": "",
        "components": "V, S, M/DF",
        "castingTime": "标准动作",
        "range": "近距 (25尺+5尺/2环)",
        "target": "以你为中心，半径40尺的弥散区域",
        "duration": "1分钟/环（D）",
        "savingThrow": "反射过则无效（见描述）",
        "spellResist": "否",
        "desc": "区域内的植物快速生长并纠缠在一起，形成困住生物的障碍。穿过该区域的生物需要移动检定（DC15）以避免被绊倒。火可以烧毁纠缠的植物。",
        "material": "一小撮草或苔藓",
        "arcane": None,
        "divine": {"druid": 1},
        "classes": {"druid": 1},
    },
    {
        "id": "barkskin",
        "nameEn": "Barkskin",
        "nameZh": "树皮术",
        "level": 2,
        "school": "变化系",
        "subschool": "",
        "descriptor": "",
        "components": "V, S, M/DF",
        "castingTime": "标准动作",
        "range": "触碰",
        "target": "触碰的生物",
        "duration": "10分钟/环",
        "savingThrow": "意志过则无效（无害）",
        "spellResist": "是（无害）",
        "desc": "受术者的皮肤变得像树皮一样坚硬，获得天然护甲加值+2。护甲加值不受受术者穿着护甲的影响。该法术可以叠加于天然护甲加值之上。",
        "material": "一块树皮",
        "arcane": None,
        "divine": {"druid": 2, "ranger": 2},
        "classes": {"druid": 2, "ranger": 2},
    },
    {
        "id": "plant_growth",
        "nameEn": "Plant Growth",
        "nameZh": "植物生长",
        "level": 3,
        "school": "咒法系",
        "subschool": "召唤",
        "descriptor": "",
        "components": "V, S, M/DF",
        "castingTime": "标准动作",
        "range": "见描述",
        "target": "见描述",
        "duration": "瞬时（见描述）",
        "savingThrow": "无",
        "spellResist": "否",
        "desc": "该法术有两种用途：1）针对一小片区域，使该区域内的植物生长茂盛，提高作物产量；2）针对大量植物，使它们快速生长并形成障碍，使移动速度减半。",
        "material": "一小撮粪便和腐殖质",
        "arcane": None,
        "divine": {"druid": 3},
        "classes": {"druid": 3},
    },
    {
        "id": "command_plants",
        "nameEn": "Command Plants",
        "nameZh": "命令植物",
        "level": 4,
        "school": "变化系",
        "subschool": "",
        "descriptor": "",
        "components": "V, S, M/DF",
        "castingTime": "标准动作",
        "range": "近距 (25尺+5尺/2环)",
        "target": "至多每等级1株植物的放射区域",
        "duration": "1轮/环",
        "savingThrow": "意志过则无效",
        "spellResist": "否",
        "desc": "你命令植物按照你的意愿行动。受命令的植物可以移动、攻击或以其他方式行动。智能植物（如菌人、莎草人）可以通过意志豁免抵抗该法术。",
        "material": "一片树叶",
        "arcane": None,
        "divine": {"druid": 4},
        "classes": {"druid": 4},
    },
    {
        "id": "wall_of_thorns",
        "nameEn": "Wall of Thorns",
        "nameZh": "荆棘墙",
        "level": 5,
        "school": "咒法系",
        "subschool": "召唤",
        "descriptor": "",
        "components": "V, S, M/DF",
        "castingTime": "标准动作",
        "range": "中距 (100尺+10尺/环)",
        "target": "见描述",
        "duration": "1轮/环（D）",
        "savingThrow": "无",
        "spellResist": "否",
        "desc": "你创造一道由浓密荆棘和藤蔓组成的墙。墙的厚度为5尺，高度和长度各为20尺。穿过墙的生物受到穿刺伤害。远程攻击无法穿过墙。",
        "material": "一撮荆棘或一根带刺的枝条",
        "arcane": None,
        "divine": {"druid": 5},
        "classes": {"druid": 5},
    },
    {
        "id": "animate_plants",
        "nameEn": "Animate Plants",
        "nameZh": "活化植物",
        "level": 7,
        "school": "变化系",
        "subschool": "",
        "descriptor": "",
        "components": "V, S, M/DF",
        "castingTime": "标准动作",
        "range": "近距 (25尺+5尺/2环)",
        "target": "至多每等级2HD的植物或植物的放射区域",
        "duration": "1轮/环",
        "savingThrow": "无",
        "spellResist": "否",
        "desc": "你使植物变成仆从。你可以活化大量的植物，使其为你作战。活化的植物攻击如同植物性生物（如莎草人）。该法术可以使森林在敌人通过时攻击他们。",
        "material": "一撮蒲公英种子",
        "arcane": None,
        "divine": {"druid": 7},
        "classes": {"druid": 7},
    },
    {
        "id": "control_plants",
        "nameEn": "Control Plants",
        "nameZh": "控制植物",
        "level": 8,
        "school": "变化系",
        "subschool": "",
        "descriptor": "",
        "components": "V, S, M/DF",
        "castingTime": "标准动作",
        "range": "近距 (25尺+5尺/2环)",
        "target": "以你为中心，半径40尺的弥散区域内的植物",
        "duration": "1轮/环",
        "savingThrow": "意志过则无效",
        "spellResist": "否",
        "desc": "你控制植物的行动。你可以命令区域内的植物攻击敌人、束缚生物或以其他方式协助你。智能植物可以通过意志豁免抵抗该法术。",
        "material": "一片树叶和一小撮泥土",
        "arcane": None,
        "divine": {"druid": 8},
        "classes": {"druid": 8},
    },

    # ════════════════ 防护领域 (Protection) ════════════════
    {
        "id": "sanctuary",
        "nameEn": "Sanctuary",
        "nameZh": "庇护所",
        "level": 1,
        "school": "防护系",
        "subschool": "",
        "descriptor": "",
        "components": "V, S, M/DF",
        "castingTime": "标准动作",
        "range": "触碰",
        "target": "触碰的生物",
        "duration": "1轮/环",
        "savingThrow": "无",
        "spellResist": "是（无害）",
        "desc": "受术者被神圣的力量保护，任何试图攻击或以有害法术 targeting 受术者的生物必须首先通过意志豁免。如果豁免失败，该生物失去下一轮的行动。",
        "material": "一片雪白的树叶或一根小羽毛",
        "arcane": None,
        "divine": {"cleric": 1},
        "classes": {"cleric": 1},
    },
    {
        "id": "spell_immunity",
        "nameEn": "Spell Immunity",
        "nameZh": "法术免疫",
        "level": 4,
        "school": "防护系",
        "subschool": "",
        "descriptor": "",
        "components": "V, S, M/DF",
        "castingTime": "标准动作",
        "range": "触碰",
        "target": "触碰的生物",
        "duration": "10分钟/环",
        "savingThrow": "意志过则无效（无害）",
        "spellResist": "是（无害）",
        "desc": "你选择至多每4施法者等级一个法术（最多5个），并使受术者对所选法术完全免疫。该法术不能使受术者对超过4级法术免疫。",
        "material": "一瓶价值150gp的圣水",
        "arcane": None,
        "divine": {"cleric": 4},
        "classes": {"cleric": 4},
    },
    {
        "id": "mind_blank",
        "nameEn": "Mind Blank",
        "nameZh": "心灵空白",
        "level": 8,
        "school": "防护系",
        "subschool": "",
        "descriptor": "",
        "components": "V, S, M/DF",
        "castingTime": "标准动作",
        "range": "近距 (25尺+5尺/2环)",
        "target": "一个自愿生物",
        "duration": "1轮/环（D）",
        "savingThrow": "无",
        "spellResist": "否",
        "desc": "受术者对所有的心灵效果、心灵感应、魅惑、胁迫、侦测思想和类似的攻击完全免疫。该法术免疫包括所有影响心智的法术和能力，以及侦测法术的尝试。",
        "material": "一块价值100gp的蛋白石",
        "arcane": {"wizard": 8, "sorcerer": 8},
        "divine": {"cleric": 8},
        "classes": {"wizard": 8, "sorcerer": 8, "cleric": 8},
    },

    # ════════════════ 力量领域 (Strength) ════════════════
    {
        "id": "magic_vestment",
        "nameEn": "Magic Vestment",
        "nameZh": "魔法护甲",
        "level": 3,
        "school": "变化系",
        "subschool": "",
        "descriptor": "",
        "components": "V, S, M/DF",
        "castingTime": "标准动作",
        "range": "触碰",
        "target": "一件护甲或盾牌",
        "duration": "1小时/环",
        "savingThrow": "意志过则无效（无害）",
        "spellResist": "是（无害）",
        "desc": "你使一件护甲或盾牌获得增强护甲加值+1。该法术可以叠加于魔法护甲上，但不能使总加值超过+5。增强加值提高护甲或盾牌的护甲等级。",
        "material": "价值50gp的细线金或银线",
        "arcane": None,
        "divine": {"cleric": 3},
        "classes": {"cleric": 3},
    },
    {
        "id": "righteous_might",
        "nameEn": "Righteous Might",
        "nameZh": "正义威仪",
        "level": 5,
        "school": "变化系",
        "subschool": "变身",
        "descriptor": "",
        "components": "V, S, DF",
        "castingTime": "标准动作",
        "range": "个人",
        "target": "自己",
        "duration": "1轮/环（D）",
        "savingThrow": "无",
        "spellResist": "否",
        "desc": "你的体型增大一个等级（最小小型），获得+4体型加值到力量，+2体型加值到魅力，-2体型惩罚到敏捷。你的天然护甲加值提高+6。",
        "arcane": None,
        "divine": {"cleric": 5},
        "classes": {"cleric": 5},
    },
    {
        "id": "grasping_hand",
        "nameEn": "Grasping Hand",
        "nameZh": "抓握之手",
        "level": 7,
        "school": "咒法系",
        "subschool": "创造",
        "descriptor": "",
        "components": "V, S, M/DF",
        "castingTime": "标准动作",
        "range": "中距 (100尺+10尺/环)",
        "target": "见描述",
        "duration": "1轮/环",
        "savingThrow": "无",
        "spellResist": "是",
        "desc": "你创造一只巨大的手，如同 intervening hand 但更强大。手可以抓握敌人、抓取物品或执行你的命令。手的攻击加值为+9近战接触攻击。",
        "material": "一块手套形状的琥珀、水晶或蓝宝石",
        "arcane": {"wizard": 7, "sorcerer": 7},
        "divine": None,
        "classes": {"wizard": 7, "sorcerer": 7},
    },
    {
        "id": "clenched_fist",
        "nameEn": "Clenched Fist",
        "nameZh": "紧握之手",
        "level": 8,
        "school": "咒法系",
        "subschool": "创造",
        "descriptor": "",
        "components": "V, S, M/DF",
        "castingTime": "标准动作",
        "range": "中距 (100尺+10尺/环)",
        "target": "见描述",
        "duration": "1轮/环",
        "savingThrow": "无",
        "spellResist": "是",
        "desc": "你创造一只紧握的拳头，如同 grasping hand 但更强大。拳头可以攻击敌人、砸碎物品或以其他方式执行你的命令。拳头的攻击加值为+11近战接触攻击。",
        "material": "一块手套形状的琥珀、水晶或蓝宝石",
        "arcane": {"wizard": 8, "sorcerer": 8},
        "divine": None,
        "classes": {"wizard": 8, "sorcerer": 8},
    },
    {
        "id": "crushing_hand",
        "nameEn": "Crushing Hand",
        "nameZh": "碾压之手",
        "level": 9,
        "school": "咒法系",
        "subschool": "创造",
        "descriptor": "",
        "components": "V, S, M/DF",
        "castingTime": "标准动作",
        "range": "中距 (100尺+10尺/环)",
        "target": "见描述",
        "duration": "1轮/环",
        "savingThrow": "无",
        "spellResist": "是",
        "desc": "你创造一只碾压的手，如同 clenched fist 但更强大。手可以碾压敌人、压碎物品或以其他方式执行你的命令。手的攻击加值为+13近战接触攻击。",
        "material": "一块手套形状的琥珀、水晶或蓝宝石",
        "arcane": {"wizard": 9, "sorcerer": 9},
        "divine": None,
        "classes": {"wizard": 9, "sorcerer": 9},
    },

    # ════════════════ 太阳领域 (Sun) ════════════════
    {
        "id": "heat_metal",
        "nameEn": "Heat Metal",
        "nameZh": "加热金属",
        "level": 2,
        "school": "塑能系",
        "subschool": "",
        "descriptor": "[火]",
        "components": "V, S, M/DF",
        "castingTime": "标准动作",
        "range": "中距 (100尺+10尺/环)",
        "target": "至多每等级1件金属物品的放射区域",
        "duration": "每轮增加热度，共7轮",
        "savingThrow": "反射过则减半",
        "spellResist": "否",
        "desc": "你加热金属物品。金属物品在7轮内逐渐变热：第1轮微温；第2轮发热；第3轮烫手（1d4点火伤害）；第4轮灼热（2d4点）；第5轮炽热（3d4点）；第6轮白热（4d4点）；第7轮熔化（6d4点）。",
        "material": "一根火把或一块烧过的煤炭",
        "arcane": None,
        "divine": {"druid": 2},
        "classes": {"druid": 2},
    },
    {
        "id": "sunbeam",
        "nameEn": "Sunbeam",
        "nameZh": "太阳光束",
        "level": 7,
        "school": "塑能系",
        "subschool": "",
        "descriptor": "[光亮][善良][火]",
        "components": "V, S, DF",
        "castingTime": "标准动作",
        "range": "60尺",
        "target": "一道光束",
        "duration": "1轮/环",
        "savingThrow": "反射过则减半（见描述）",
        "spellResist": "是",
        "desc": "你创造出一道明亮的太阳光束。光束对不死生物造成2d8点伤害每2施法者等级（最高10d8），并使其目盲一轮。对恶魔、魔鬼和其他邪恶异位面生物也造成额外伤害。",
        "arcane": None,
        "divine": {"cleric": 7, "druid": 7},
        "classes": {"cleric": 7, "druid": 7},
    },

    # ════════════════ 旅行领域 (Travel) ════════════════
    {
        "id": "longstrider",
        "nameEn": "Longstrider",
        "nameZh": "长跑术",
        "level": 1,
        "school": "变化系",
        "subschool": "",
        "descriptor": "",
        "components": "V, S, M/DF",
        "castingTime": "标准动作",
        "range": "触碰",
        "target": "触碰的生物",
        "duration": "1小时/环",
        "savingThrow": "意志过则无效（无害）",
        "spellResist": "是（无害）",
        "desc": "受术者的陆地速度增加10尺。该法术不会影响飞行或游泳速度。速度增加可以使受术者在一天内移动更远的距离。",
        "material": "一小块皮革带",
        "arcane": None,
        "divine": {"druid": 1, "ranger": 1},
        "classes": {"druid": 1, "ranger": 1},
    },
    {
        "id": "locate_object",
        "nameEn": "Locate Object",
        "nameZh": "定位物品",
        "level": 2,
        "school": "预言系",
        "subschool": "",
        "descriptor": "",
        "components": "V, S, M/DF",
        "castingTime": "标准动作",
        "range": "近距 (25尺+5尺/2环)",
        "target": "你本人",
        "duration": "1分钟/环",
        "savingThrow": "无",
        "spellResist": "否",
        "desc": "你感知到特定物品的方向。你需要有一个特定物品的描述，或者可以搜索一般类型的物品（如魔法剑）。该法术告诉你物品的方向和距离（如果物品在施法距离内）。",
        "material": "一块价值50gp的叉铃（钟）",
        "arcane": {"wizard": 2, "sorcerer": 2},
        "divine": {"cleric": 2, "ranger": 2},
        "classes": {"wizard": 2, "sorcerer": 2, "cleric": 2, "ranger": 2},
    },

    # ════════════════ 诡术领域 (Trickery) ════════════════
    {
        "id": "disguise_self",
        "nameEn": "Disguise Self",
        "nameZh": "伪装自己",
        "level": 1,
        "school": "幻术系",
        "subschool": "虚假幻觉",
        "descriptor": "",
        "components": "V, S, M/DF",
        "castingTime": "标准动作",
        "range": "个人",
        "target": "自己",
        "duration": "10分钟/环（D）",
        "savingThrow": "无",
        "spellResist": "否",
        "desc": "你改变自己的外表，使其看起来像另一个生物或物体。你可以改变自己的体型（最多一个等级差异）、外观和装备。该法术不能改变你的声音、触感或气味。",
        "material": "一小片丝绸或一块宝石",
        "arcane": {"wizard": 1, "sorcerer": 1, "bard": 1},
        "divine": {"cleric": 1},
        "classes": {"wizard": 1, "sorcerer": 1, "bard": 1, "cleric": 1},
    },
    {
        "id": "screen",
        "nameEn": "Screen",
        "nameZh": "屏蔽术",
        "level": 7,
        "school": "幻术系",
        "subschool": "虚假幻觉",
        "descriptor": "",
        "components": "V, S, M/DF",
        "castingTime": "标准动作",
        "range": "以你为中心，半径40尺的弥散区域",
        "target": "见描述",
        "duration": "1轮/环",
        "savingThrow": "意志过则无效",
        "spellResist": "否",
        "desc": "该法术隐藏区域内所有生物、物品和法术效果的真实性质。任何侦测效果（如侦测魔法、侦测思想、真知术）都会显示虚假信息。",
        "material": "一小片丝绸或一块宝石",
        "arcane": {"wizard": 7, "sorcerer": 7},
        "divine": None,
        "classes": {"wizard": 7, "sorcerer": 7},
    },

    # ════════════════ 战争领域 (War) ════════════════
    {
        "id": "spiritual_weapon",
        "nameEn": "Spiritual Weapon",
        "nameZh": "灵体武器",
        "level": 2,
        "school": "塑能系",
        "subschool": "",
        "descriptor": "",
        "components": "V, S, M/DF",
        "castingTime": "标准动作",
        "range": "近距 (25尺+5尺/2环)",
        "target": "见描述",
        "duration": "1轮/环",
        "savingThrow": "无",
        "spellResist": "是",
        "desc": "你创造一个由魔法能量构成的武器（通常是钉头锤）。武器可以攻击你的敌人，如同你用远程攻击一样（但在近战中使用）。武器使用你的基本攻击加值+你的魅力调整值。",
        "material": "一把价值5gp以上的小雕像武器",
        "arcane": None,
        "divine": {"cleric": 2},
        "classes": {"cleric": 2},
    },
    {
        "id": "divine_power",
        "nameEn": "Divine Power",
        "nameZh": "神力术",
        "level": 4,
        "school": "变化系",
        "subschool": "",
        "descriptor": "",
        "components": "V, S, DF",
        "castingTime": "标准动作",
        "range": "个人",
        "target": "自己",
        "duration": "1轮/环",
        "savingThrow": "无",
        "spellResist": "否",
        "desc": "你获得+6力量加值，获得临时生命值等于你拥有HD的4倍，并获得基础攻击加值等于你的角色等级（使你可以进行多次攻击）。该法术使你在近战中非常强大。",
        "arcane": None,
        "divine": {"cleric": 4},
        "classes": {"cleric": 4},
    },

    # ════════════════ 水领域 (Water) ════════════════
    {
        "id": "fog_cloud",
        "nameEn": "Fog Cloud",
        "nameZh": "云雾术",
        "level": 2,
        "school": "咒法系",
        "subschool": "创造",
        "descriptor": "",
        "components": "V, S",
        "castingTime": "标准动作",
        "range": "中距 (100尺+10尺/环)",
        "target": "以目标点为中心，半径20尺的弥散范围",
        "duration": "10分钟/环",
        "savingThrow": "无",
        "spellResist": "否",
        "desc": "你创造出一团浓密的云雾，使所有穿过该区域的生物的有效视野缩短至5尺。远程攻击无法穿过云雾，侦测类和侦察检定会受到-5惩罚。云雾可以被风驱散。",
        "arcane": {"wizard": 2, "sorcerer": 2},
        "divine": {"cleric": 2, "druid": 2},
        "classes": {"wizard": 2, "sorcerer": 2, "cleric": 2, "druid": 2},
    },
    {
        "id": "control_water",
        "nameEn": "Control Water",
        "nameZh": "控制水质",
        "level": 4,
        "school": "咒法系",
        "subschool": "召唤",
        "descriptor": "",
        "components": "V, S, M/DF",
        "castingTime": "标准动作",
        "range": "长距 (400尺+40尺/环)",
        "target": "水体，至多每等级1立方尺的水",
        "duration": "10分钟/环（D）",
        "savingThrow": "无",
        "spellResist": "否",
        "desc": "你控制水体的水位和流动。你可以使水位上升或下降（最多3尺），创造或移除水流，或使平静的水变得汹涌。该法术可以用来创造浅滩、淹没区域或驱散雾气。",
        "material": "一小片一块木头或一小撮水",
        "arcane": None,
        "divine": {"cleric": 4, "druid": 4},
        "classes": {"cleric": 4, "druid": 4},
    },
    {
        "id": "cone_of_cold",
        "nameEn": "Cone of Cold",
        "nameZh": "冷锥术",
        "level": 6,
        "school": "塑能系",
        "subschool": "",
        "descriptor": "[寒气]",
        "components": "V, S, M/DF",
        "castingTime": "标准动作",
        "range": "60尺锥形",
        "target": "锥形区域内的生物和物品",
        "duration": "瞬时",
        "savingThrow": "强韧过则减半",
        "spellResist": "是",
        "desc": "你释放出一股极寒气，对锥形区域内的所有生物和物品造成1d8点寒冷伤害每施法者等级（最高15d8）。该法术可以熄灭火焰、冻结液体和造成其他寒冷相关效果。",
        "material": "一块价值25gp的玻璃或水晶锥体",
        "arcane": {"wizard": 5, "sorcerer": 5},
        "divine": None,
        "classes": {"wizard": 5, "sorcerer": 5},
    },
]

# ─── 工具函数 ───

def esc(s):
    """转义字符串中的双引号和反斜杠"""
    return s.replace('\\', '\\\\').replace('"', '\\"')

def serialize_spell(spell, indent=2):
    """将法术 dict 序列化为 JS 对象字面量"""
    sp = ' ' * indent
    lines = []
    lines.append('{')
    lines.append(f'{sp}id:"{spell["id"]}", nameEn:"{spell["nameEn"]}", nameZh:"{spell["nameZh"]}",')
    lines.append(f'{sp}level:{spell["level"]}, school:"{spell["school"]}", ', end='')
    if spell.get("subschool"):
        lines[-1] += f'subschool:"{spell["subschool"]}", '
    if spell.get("descriptor"):
        lines[-1] += f'descriptor:"{spell["descriptor"]}", '
    lines[-1] += f'components:"{spell["components"]}", castingTime:"{spell["castingTime"]}",'
    lines.append(f'{sp}range:"{spell["range"]}", target:"{spell["target"]}",')
    lines.append(f'{sp}duration:"{spell["duration"]}", savingThrow:"{spell["savingThrow"]}", spellResist:"{spell["spellResist"]}",')
    lines.append(f'{sp}desc:"{esc(spell["desc"])}",')
    if spell.get("material"):
        lines.append(f'{sp}material:"{esc(spell["material"])}",')
    if spell.get("focus"):
        lines.append(f'{sp}focus:"{esc(spell["focus"])}",')
    
    # arcane
    if spell.get("arcane"):
        entries = ", ".join(f'{k}:{v}' for k, v in spell["arcane"].items())
        lines.append(f'{sp}arcane:{{{entries}}}, ')
    else:
        lines.append(f'{sp}arcane:null, ')
    
    # divine
    if spell.get("divine"):
        entries = ", ".join(f'{k}:{v}' for k, v in spell["divine"].items())
        lines.append(f'{sp}divine:{{{entries}}}, ')
    else:
        lines.append(f'{sp}divine:null, ')
    
    # classes
    class_entries = ", ".join(f'{k}:{v}' for k, v in spell["classes"].items())
    lines.append(f'{sp}classes:{{{class_entries}}}}')
    lines.append('  }')
    return '\n'.join(lines)

# ─── 主逻辑 ───

# 读取原始文件
bak_path = 'js/spells-data.js.bak'
with open(bak_path, 'r', encoding='utf-8') as f:
    content = f.read()

print(f'已读取备份文件：{len(content)} 字节')

# 解析现有 ID
id_pattern = re.compile(r'id\s*:\s*"([^"]+)"')
existing_ids = set(id_pattern.findall(content))
print(f'现有法术数（按ID）: {len(existing_ids)}')

# 去重：只保留不存在的法术
to_add = [s for s in SPELLS_DATA if s["id"] not in existing_ids]
print(f'需要添加的新法术: {len(to_add)} 个')
print(f'已存在（跳过）: {len(SPELLS_DATA) - len(to_add)} 个')

if len(to_add) == 0:
    print('没有新法术需要添加')
    exit(0)

# 生成要插入的文本
insert_text = ''
for i, spell in enumerate(to_add):
    if i > 0:
        insert_text += ',\n'
    insert_text += serialize_spell(spell, indent=2)
insert_text = ',\n' + insert_text + '\n'

# 找到数组结尾位置
last_bracket = content.rfind('];')
if last_bracket == -1:
    print('错误：找不到数组结尾 ];')
    exit(1)

# 插入到 ]; 之前
new_content = content[:last_bracket] + insert_text + content[last_bracket:]

# 备份当前文件（如果存在）
import shutil
if os.path.exists('js/spells-data.js'):
    backup_path = 'js/spells-data.js.bak_new'
    shutil.copy2('js/spells-data.js', backup_path)
    print(f'已备份当前文件到: {backup_path}')

# 写入
with open('js/spells-data.js', 'w', encoding='utf-8') as f:
    f.write(new_content)

print(f'\n✅ 已添加 {len(to_add)} 个新法术到 spells-data.js')
print(f'文件大小: {len(new_content)} 字节')

# 验证
try:
    with open('js/spells-data.js', 'r', encoding='utf-8') as f:
        test_content = f.read()
    SPELLS = eval(test_content + '\nreturn SPELLS;')
    print(f'验证：法术总数: {len(SPELLS)}')
    
    # 检查重复
    ids = [s["id"] for s in SPELLS]
    unique = set(ids)
    if len(ids) != len(unique):
        print(f'⚠️ 仍有重复ID: {len(ids) - len(unique)} 个')
        # 找出重复的
        seen = set()
        for i, id in enumerate(ids):
            if id in seen:
                print(f'  重复: {id} (索引 {i})')
            else:
                seen.add(id)
    else:
        print('✅ 无重复ID')
except Exception as e:
    print(f'❌ 验证失败: {e}')
