const fs = require('fs');
const path = require('path');

// 读取当前的spells-data.js
const spellsDataPath = path.join(__dirname, 'js', 'spells-data.js');
let content = fs.readFileSync(spellsDataPath, 'utf8');

// 提取现有的SPELLS数组
const match = content.match(/const SPELLS = \[([\s\S]*)\];/);
if (!match) {
    console.error('无法解析spells-data.js');
    process.exit(1);
}

// 解析现有法术的ID
const existingIds = new Set();
const idRegex = /id:\s*['"]([^'"]+)['"]/g;
let idMatch;
while ((idMatch = idRegex.exec(content)) !== null) {
    existingIds.add(idMatch[1]);
}

console.log(`现有法术数量: ${existingIds.size}`);

// 定义缺失的66个领域法术
const newSpells = [
  // ===== 似水领域 (Water) =====
  {
    id: 'watery-bubble',
    nameEn: 'Watery Bubble',
    nameZh: '水之泡',
    level: { magus: 1, wizard: 1, sorcerer: 1 },
    school: 'conjuration',
    subSchool: 'water',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '近距 (25尺+5尺/2等级)',
    target: '你或生物/每3等级，所有目标必须在15尺内',
    duration: '1轮/等级',
    savingThrow: '无',
    spellResist: true,
    desc: '你创造多个充满呼吸空气的水泡，每个足够容纳一个中型或更小的生物。每个水泡被1英寸厚的软水层包围，并漂浮在你周围15尺半径区域内。每个水泡内的生物可以呼吸、施法和使用其他需呼吸的技能。'
  },
  {
    id: 'summon-monster-2-water',
    nameEn: 'Summon Monster II (Water)',
    nameZh: '召唤怪物II（水）',
    level: { cleric: 2, druid: 2 },
    school: 'conjuration',
    subSchool: 'summoning',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '1轮',
    range: '近距 (25尺+5尺/2等级)',
    target: '一个生物',
    duration: '1轮/等级',
    savingThrow: '无',
    spellResist: true,
    desc: '召唤一个水元素盟友为你作战。'
  },
  {
    id: 'ice-floes',
    nameEn: 'Ice Floes',
    nameZh: '浮冰',
    level: { magus: 3, wizard: 3, sorcerer: 3 },
    school: 'evocation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '远距',
    area: '四个5尺方形区域，每两个之间相距不超过30尺',
    duration: '1轮/等级',
    savingThrow: '反射过则无伤害',
    spellResist: false,
    desc: '你在水面或地面上创造四个浮冰区域。每个区域成为困难地形，并对进入的生物造成1d6点寒冷伤害。'
  },
  {
    id: 'summon-avalancher',
    nameEn: 'Summon Avalancher',
    nameZh: '召唤雪崩者',
    level: { cleric: 4, druid: 4 },
    school: 'conjuration',
    subSchool: 'summoning',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '1轮',
    range: '近距 (25尺+5尺/2等级)',
    target: '一个生物',
    duration: '1轮/等级',
    savingThrow: '无',
    spellResist: true,
    desc: '召唤一个雪崩者（大型冰元素）为你作战。'
  },
  {
    id: 'ice-flow',
    nameEn: 'Ice Flow',
    nameZh: '冰流',
    level: { magus: 5, wizard: 5, sorcerer: 5 },
    school: 'evocation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '远距 (400尺+40尺/等级)',
    area: '直线释放，长度每等级30尺，宽度10尺',
    duration: '1轮/等级',
    savingThrow: '反射过则无伤害',
    spellResist: false,
    desc: '创造一条冰流，对路径上的所有生物造成5d6点寒冷伤害，并将区域变为困难地形。'
  },
  {
    id: 'cone-of-cold',
    nameEn: 'Cone of Cold',
    nameZh: '寒冰锥',
    level: { magus: 6, wizard: 6, sorcerer: 6, cleric: 6 },
    school: 'evocation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '60尺锥形',
    area: '60尺锥形',
    duration: '瞬时',
    savingThrow: '反射过则伤害减半',
    spellResist: true,
    desc: '你释放一道寒冰锥，对区域内的所有生物造成10d6点寒冷伤害。'
  },
  {
    id: 'vortex',
    nameEn: 'Vortex',
    nameZh: '漩涡',
    level: { cleric: 7, druid: 7 },
    school: 'evocation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '远距 (400尺+40尺/等级)',
    target: '一个生物或物体',
    duration: '1轮/等级',
    savingThrow: '反射过则无效果',
    spellResist: true,
    desc: '创造一个水漩涡，将目标困在中心并每轮造成8d6点伤害。'
  },
  {
    id: 'horrid-wilting',
    nameEn: 'Horrid Wilting',
    nameZh: '恐萎术',
    level: { magus: 8, wizard: 8, sorcerer: 8 },
    school: 'necromancy',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '远距 (400尺+40尺/等级)',
    target: '一个或多个生物，总HD不超过2/等级',
    duration: '瞬时',
    savingThrow: '强韧过则伤害减半',
    spellResist: true,
    desc: '该法术从生物体内吸取所有水分，造成每目标1d6点/每等级（最大25d6）的伤害。不死生物和构装体不受影响。在水下施放此法术将自动失败。'
  },
  {
    id: 'energy-flood',
    nameEn: 'Energy Flood (Cold)',
    nameZh: '能量洪流（寒冷）',
    level: { wizard: 9, sorcerer: 9 },
    school: 'evocation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '远距 (400尺+40尺/等级)',
    area: '四个10尺方形区域，每两个之间相距不超过30尺',
    duration: '瞬时',
    savingThrow: '反射过则伤害减半',
    spellResist: true,
    desc: '释放四股寒冷能量洪流，每道造成10d6点寒冷伤害。'
  },

  // ===== 战争领域 (War) =====
  {
    id: 'true-strike',
    nameEn: 'True Strike',
    nameZh: '精准打击',
    level: { magus: 1, wizard: 1, sorcerer: 1 },
    school: 'divination',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '个人',
    target: '自己',
    duration: '见描述',
    savingThrow: '无',
    spellResist: false,
    desc: '你的下一次攻击检定获得+20洞察加值。该法术在击中后或下一轮结束时消散。'
  },
  {
    id: 'spiritual-weapon',
    nameEn: 'Spiritual Weapon',
    nameZh: '灵体武器',
    level: { cleric: 2 },
    school: 'evocation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '近距 (25尺+5尺/2等级)',
    target: '一把灵体武器',
    duration: '1轮/等级',
    savingThrow: '无',
    spellResist: true,
    desc: '你创造一把漂浮的灵体武器复制品（你选择的任何种族的简单或军用武器）。每轮，你可以用一个标准动作命令武器攻击一个敌人，造成1d8+你的魅力调整值的伤害。'
  },
  {
    id: 'magic-vestment',
    nameEn: 'Magic Vestment',
    nameZh: '魔法外衣',
    level: { cleric: 3 },
    school: 'transmutation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '接触',
    target: '一件防具或盾牌',
    duration: '1小时/等级',
    savingThrow: '意志过则无效（无害）',
    spellResist: true,
    desc: '你使一件防具或盾牌获得+1增强加值。每4等级（最大+5在16级），这个加值增加+1。'
  },
  {
    id: 'divine-power',
    nameEn: 'Divine Power',
    nameZh: '神力',
    level: { cleric: 4 },
    school: 'evocation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '个人',
    target: '自己',
    duration: '1轮/等级',
    savingThrow: '无',
    spellResist: false,
    desc: '你获得：力量+4增强加值，基础攻击加值等于你的角色等级（可能获得额外攻击），每本轮一次重骰攻击骰。'
  },
  {
    id: 'righteous-might',
    nameEn: 'Righteous Might',
    nameZh: '正义威仪',
    level: { cleric: 5 },
    school: 'transmutation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '个人',
    target: '自己',
    duration: '1轮/等级',
    savingThrow: '无',
    spellResist: false,
    desc: '你的体型增大一级，获得+4体型加值力量，-2敏捷，+4天生护甲加值，你的武器造成额外1d8点伤害。'
  },
  {
    id: 'blade-barrier',
    nameEn: 'Blade Barrier',
    nameZh: '刀墙术',
    level: { cleric: 6 },
    school: 'evocation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '近距 (25尺+5尺/2等级)',
    area: '环形墙，半径最多10尺+1尺/等级',
    duration: '1轮/等级',
    savingThrow: '反射过则伤害减半',
    spellResist: true,
    desc: '你创造一道旋转的刀刃墙。任何穿过墙的生物受到每轮1d6点/每2等级（最大10d6）的挥砍伤害。'
  },
  {
    id: 'holy-sword',
    nameEn: 'Holy Sword',
    nameZh: '圣剑',
    level: { paladin: 4, cleric: 7 },
    school: 'evocation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '接触',
    target: '一把近战武器',
    duration: '1轮/等级',
    savingThrow: '意志过则无效（无害）',
    spellResist: true,
    desc: '你使一把武器获得+5神圣增强加值，并对邪恶生物额外造成2d6点神圣伤害。如果武器离开你的手，该法术结束。'
  },
  {
    id: 'power-word-stun',
    nameEn: 'Power Word Stun',
    nameZh: '力令眩晕',
    level: { bard: 4, wizard: 8, sorcerer: 8 },
    school: 'enchantment',
    components: { verbal: true, somatic: false, material: false },
    castingTime: '标准动作',
    range: '近距 (25尺+5尺/2等级)',
    target: '一个生物',
    duration: '见描述',
    savingThrow: '意志过则无效',
    spellResist: true,
    desc: '你对一个生物说出一个魔力词，使其眩晕。如果目标有75点或更多生命值，无效果。51-74点生命值，眩晕1d4轮。35-50点生命值，眩晕1d4+1d4轮。少于35点生命值，眩晕2d4+1d4轮。'
  },
  {
    id: 'power-word-kill',
    nameEn: 'Power Word Kill',
    nameZh: '力令死',
    level: { wizard: 9, sorcerer: 9, bard: 6 },
    school: 'enchantment',
    components: { verbal: true, somatic: false, material: false },
    castingTime: '标准动作',
    range: '近距 (25尺+5尺/2等级)',
    target: '一个生物',
    duration: '瞬时',
    savingThrow: '无',
    spellResist: true,
    desc: '你对一个生物说出一个魔力词，立即杀死它。如果目标有51点或更多生命值，法术失败。否则，目标立即死亡。'
  },

  // ===== 诡计领域 (Trickery) =====
  {
    id: 'disguise-self',
    nameEn: 'Disguise Self',
    nameZh: '伪装术',
    level: { bard: 1, magus: 1, wizard: 1, sorcerer: 1, cleric: 1 },
    school: 'illusion',
    subSchool: 'figment',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '个人',
    target: '自己',
    duration: '10分钟/等级',
    savingThrow: '意志过则识破（如果有互动）',
    spellResist: '特殊（见描述）',
    desc: '你可以改变自己的外观。你可以看起来像另一个体型类别的生物。该法术不会改变你的能力值、装备或声音。物理检查可能揭示你的真实身份。'
  },
  {
    id: 'invisibility',
    nameEn: 'Invisibility',
    nameZh: '隐形术',
    level: { bard: 2, magus: 2, wizard: 2, sorcerer: 2 },
    school: 'illusion',
    subSchool: 'glamer',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '接触',
    target: '自己或生物/每等级，所有目标必须在30尺内',
    duration: '1轮/等级（D）',
    savingThrow: '意志过则无效（无害）或意志过则无效（无害，对物体）',
    spellResist: '是（无害）',
    desc: '目标变得看不见。如果目标攻击或施展攻击性法术，隐形术在回合结束时结束。'
  },
  {
    id: 'nondetection',
    nameEn: 'Nondetection',
    nameZh: '反侦测',
    level: { bard: 3, magus: 3, wizard: 3, sorcerer: 3, cleric: 3 },
    school: 'abjuration',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '接触',
    target: '自己或生物/每等级，所有目标必须在30尺内',
    duration: '1小时/等级',
    savingThrow: '意志过则无效（无害）',
    spellResist: true,
    desc: '目标对侦察和探知法术（如侦测魔法、真实视觉）获得+4抗力加值。'
  },
  {
    id: 'confusion',
    nameEn: 'Confusion',
    nameZh: '困惑术',
    level: { bard: 3, magus: 4, wizard: 4, sorcerer: 4, cleric: 4 },
    school: 'enchantment',
    subSchool: 'compulsion',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '近距 (25尺+5尺/2等级)',
    area: '半径15尺的扩散，中心在落点',
    duration: '1轮/等级',
    savingThrow: '意志过则无效',
    spellResist: true,
    desc: '区域内所有生物必须每轮掷d%：01-10攻击最近的生物，11-25站立不动，26-50行动缓慢不能攻击，51-75四处游荡，76-100正常行动。'
  },
  {
    id: 'false-vision',
    nameEn: 'False Vision',
    nameZh: '假象',
    level: { bard: 5, wizard: 5, sorcerer: 5, cleric: 5 },
    school: 'illusion',
    subSchool: 'glamer',
    components: { verbal: true, somatic: true, material: true },
    material: '价值500gp的兔毛和杜松浆果',
    castingTime: '标准动作',
    range: '接触',
    area: '接触到的10尺方形区域/每等级',
    duration: '1小时/等级',
    savingThrow: '无',
    spellResist: false,
    desc: '该法术在受影响区域创造虚假的感官印象。任何通过探知或远程视觉观察区域的人看到的是你选择的虚假图像，而不是真实情况。'
  },
  {
    id: 'mislead',
    nameEn: 'Mislead',
    nameZh: '误导',
    level: { bard: 6, wizard: 6, sorcerer: 6, cleric: 6 },
    school: 'illusion',
    subSchool: 'figment',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '个人',
    target: '自己',
    duration: '1轮/等级',
    savingThrow: '无或意志过则识破（见描述）',
    spellResist: '否或见描述',
    desc: '你的身体变得隐形（如同隐形术）。同时，创造一个你的虚假影像（如同投射影像）在你选择的位置。你可以看到和听到虚假影像位置的景象和声音。'
  },
  {
    id: 'project-image',
    nameEn: 'Project Image',
    nameZh: '投射影像',
    level: { bard: 7, wizard: 7, sorcerer: 7, cleric: 7 },
    school: 'illusion',
    subSchool: 'figment',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '远距 (400尺+40尺/等级)',
    target: '你或你的影像',
    duration: '1轮/等级',
    savingThrow: '意志过则识破',
    spellResist: '否',
    desc: '你创造一个你可以看到、听到和说话的自己的影像。影像可以做手势并施法（法术从你的实际位置释放）。影像可以穿过障碍物。'
  },
  {
    id: 'maze',
    nameEn: 'Maze',
    nameZh: '迷宫术',
    level: { wizard: 8, sorcerer: 8, bard: 5, cleric: 8 },
    school: 'conjuration',
    subSchool: 'teleportation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '近距 (25尺+5尺/2等级)',
    target: '一个生物',
    duration: '见描述',
    savingThrow: '无',
    spellResist: true,
    desc: '你将目标放逐到一个无法逃脱的迷宫位面。目标必须成功DC20的智力检定才能每轮逃脱。大型或更大的生物获得+2加值，非凡生物至少需1轮逃脱。'
  },
  {
    id: 'weird',
    nameEn: 'Weird',
    nameZh: '怪影术',
    level: { wizard: 9, sorcerer: 9, bard: 6, cleric: 9 },
    school: 'illusion',
    subSchool: 'phantasm',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '远距 (400尺+40尺/等级)',
    area: '半径30尺+5尺/每3等级的扩散，中心在落点',
    duration: '瞬时',
    savingThrow: '意志过则无效或强韧过则伤害减半',
    spellResist: true,
    desc: '区域内所有生物看到它们最恐惧的景象。失败意志豁免的生物立即死亡。成功豁免但失败强韧豁免的生物受到3d6点生命值损失。'
  },

  // ===== 旅行领域 (Travel) =====
  {
    id: 'longstrider',
    nameEn: 'Longstrider',
    nameZh: '疾行术',
    level: { ranger: 1, druid: 1, magus: 1, wizard: 1, sorcerer: 1 },
    school: 'transmutation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '个人',
    target: '自己',
    duration: '1小时/等级',
    savingThrow: '无',
    spellResist: false,
    desc: '你的陆地速度增加10尺。'
  },
  {
    id: 'locate-object',
    nameEn: 'Locate Object',
    nameZh: '寻找物品',
    level: { bard: 2, cleric: 2, ranger: 2, magus: 2, wizard: 2, sorcerer: 2 },
    school: 'divination',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '远距 (400尺+40尺/等级)',
    target: '自己',
    duration: '1分钟/等级',
    savingThrow: '无',
    spellResist: false,
    desc: '你感知特定物品或一类物品的方向。你可以搜索特定物品（如"我的法术书"）或一般类别（如"法术卷轴"）。'
  },
  {
    id: 'fly',
    nameEn: 'Fly',
    nameZh: '飞行术',
    level: { magus: 3, wizard: 3, sorcerer: 3, bard: 3 },
    school: 'transmutation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '接触',
    target: '一个生物',
    duration: '1轮/等级',
    savingThrow: '意志过则无效（无害）或意志过则无效（无害，对物体）',
    spellResist: '是（无害）或否（对物体）',
    desc: '目标获得40尺飞行速度（机动性：完美）。在法术持续时间内，飞行速度可以因护甲而降低。'
  },
  {
    id: 'dimension-door',
    nameEn: 'Dimension Door',
    nameZh: '任意门',
    level: { bard: 4, magus: 4, wizard: 4, sorcerer: 4 },
    school: 'conjuration',
    subSchool: 'teleportation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '远距 (400尺+40尺/等级)',
    target: '自己或50磅/等级',
    duration: '瞬时',
    savingThrow: '无',
    spellResist: false,
    desc: '你瞬间传送自己（和最多50磅/等级的物品）到可见或熟悉的位置。你不需要看到目的地，但必须能够精确描述它。'
  },
  {
    id: 'overland-flight',
    nameEn: 'Overland Flight',
    nameZh: '长途飞行',
    level: { magus: 5, wizard: 5, sorcerer: 5, bard: 5 },
    school: 'transmutation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '接触',
    target: '一个生物',
    duration: '1小时/等级',
    savingThrow: '意志过则无效（无害）或意志过则无效（无害，对物体）',
    spellResist: '是（无害）或否（对物体）',
    desc: '目标获得40尺飞行速度（机动性：完美）。与飞行术不同，该法术持续更长时间，适合长途旅行。'
  },
  {
    id: 'find-the-path',
    nameEn: 'Find the Path',
    nameZh: '寻路',
    level: { cleric: 6, druid: 6 },
    school: 'divination',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '接触',
    target: '接触到的生物',
    duration: '1分钟/等级',
    savingThrow: '无',
    spellResist: false,
    desc: '你获得到指定地点的完美方向感。该法术告诉你到达目的地的最短、最直接的安全路线。'
  },
  {
    id: 'phase-door',
    nameEn: 'Phase Door',
    nameZh: '相位门',
    level: { wizard: 7, sorcerer: 7, bard: 5 },
    school: 'conjuration',
    subSchool: 'creation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '接触',
    target: '一个生物',
    duration: '1轮/等级',
    savingThrow: '无',
    spellResist: false,
    desc: '你在墙上或固体障碍物上创造一个看不见的入口。任何生物可以用一个标准动作穿过它。入口在一轮后关闭，但你可以再次打开它。'
  },
  {
    id: 'maze',
    nameEn: 'Maze',
    nameZh: '迷宫术',
    level: { wizard: 8, sorcerer: 8, cleric: 8 },
    school: 'conjuration',
    subSchool: 'teleportation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '近距 (25尺+5尺/2等级)',
    target: '一个生物',
    duration: '见描述',
    savingThrow: '无',
    spellResist: true,
    desc: '见上方诡计领域9级法术描述。'
  },
  {
    id: 'astral-projection',
    nameEn: 'Astral Projection',
    nameZh: '星界投射',
    level: { cleric: 9, wizard: 9, sorcerer: 9 },
    school: 'necromancy',
    components: { verbal: true, somatic: true, material: true },
    material: '价值1000gp的钻石和一块卵石',
    castingTime: '30分钟',
    range: '接触',
    target: '你和最多8个接触到的生物',
    duration: '特殊',
    savingThrow: '意志过则无效',
    spellResist: true,
    desc: '你将你的星界体（和物质体）投射到星界位面。在星界，你可以旅行到其他位面。你的星界体看起来像你，但具有额外的能力。'
  },

  // ===== 阳光领域 (Sun) =====
  {
    id: 'endure-elements',
    nameEn: 'Endure Elements',
    nameZh: '忍受环境',
    level: { druid: 1, ranger: 1, cleric: 1 },
    school: 'abjuration',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '接触',
    target: '自己或生物/每等级，所有目标必须在接触范围内',
    duration: '24小时',
    savingThrow: '意志过则无效（无害）或意志过则无效（无害，对物体）',
    spellResist: '是（无害）',
    desc: '受术者免疫极端温度和天气的影响（热、冷、风、雨等）。该法术不提供对火或寒冷攻击的防护。'
  },
  {
    id: 'searing-light',
    nameEn: 'Searing Light',
    nameZh: '灼光术',
    level: { cleric: 2 },
    school: 'evocation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '远距 (400尺+40尺/等级)',
    target: '一个生物或物体',
    duration: '瞬时',
    savingThrow: '强韧过则伤害减半',
    spellResist: true,
    desc: '你释放一道耀眼的光束，对目标造成1d8点/每2等级（最大5d8）的光明伤害。对不死生物，伤害骰变为d6且每骰+1（最大5d6+5）。'
  },
  {
    id: 'daylight',
    nameEn: 'Daylight',
    nameZh: '日光术',
    level: { bard: 3, cleric: 3, druid: 3 },
    school: 'evocation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '接触',
    target: '接触到的物体',
    duration: '10分钟/等级',
    savingThrow: '无',
    spellResist: false,
    desc: '受影响的物体辐射出60尺半径的光明。该法术可以抵消黑暗术和昼明术。对黑暗生物和以光明为弱点的生物造成不适。'
  },
  {
    id: 'sunbeam',
    nameEn: 'Sunbeam',
    nameZh: '日光束',
    level: { druid: 4, cleric: 7 },
    school: 'evocation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '远距 (400尺+40尺/等级)',
    area: '直线释放，长度每等级10尺，宽度5尺',
    duration: '1轮/等级',
    savingThrow: '反射过则无效果',
    spellResist: true,
    desc: '你释放一道明亮的太阳光束。任何在光束中的生物受到每轮3d6点光明伤害。不死生物和黑暗生物受到双倍伤害。'
  },
  {
    id: 'fire-shield',
    nameEn: 'Fire Shield',
    nameZh: '火焰盾',
    level: { magus: 5, wizard: 5, sorcerer: 5 },
    school: 'evocation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '个人',
    target: '自己',
    duration: '1轮/等级',
    savingThrow: '无',
    spellResist: false,
    desc: '你的身体被火焰或寒冷灵光包围。温暖灵光（火）：对寒冷攻击获得抗性15，寒冷生物攻击你受到1d6+1点每2等级（最大+10）的火焰伤害。寒冷灵光（冰）：对火焰攻击获得抗性15，火焰生物攻击你受到相同的寒冷伤害。'
  },
  {
    id: 'fire-seeds',
    nameEn: 'Fire Seeds',
    nameZh: '火种术',
    level: { druid: 6, cleric: 6 },
    school: 'transmutation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '接触',
    target: '最多四个种子或坚果',
    duration: '1天/等级或直到触发',
    savingThrow: '反射过则伤害减半',
    spellResist: true,
    desc: '你将橡子或果实变为投掷武器。橡子造成1d6点火焰伤害（直射60尺，溅射10尺半径）。果实造成2d6点伤害（直射5尺，溅射20尺半径）。你可以设置触发条件。'
  },
  {
    id: 'sunray',
    nameEn: 'Sunray',
    nameZh: '太阳光',
    level: { cleric: 7, druid: 7 },
    school: 'evocation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '30尺',
    area: '30尺锥形',
    duration: '瞬时',
    savingThrow: '强韧过则无效果或反射过则无效果',
    spellResist: '是',
    desc: '你释放一道强烈的太阳光。所有在锥形中的生物受到每HD 1d6点光明伤害（最大20d6）。此外，盲视被致盲1d4轮，黑暗生物被摧毁。'
  },
  {
    id: 'incendiary-cloud',
    nameEn: 'Incendiary Cloud',
    nameZh: '燃烧云雾',
    level: { wizard: 8, sorcerer: 8, druid: 8 },
    school: 'conjuration',
    subSchool: 'creation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '远距 (400尺+40尺/等级)',
    area: '20尺半径球形云，中心在落点',
    duration: '1轮/等级',
    savingThrow: '反射过则伤害减半',
    spellResist: false,
    desc: '你创造一片燃烧的云雾。云雾中的生物每轮受到4d6点火焰伤害。云雾可以移动，每轮移动30尺。'
  },
  {
    id: 'prismatic-sphere',
    nameEn: 'Prismatic Sphere',
    nameZh: '虹光球',
    level: { wizard: 9, sorcerer: 9, cleric: 9 },
    school: 'abjuration',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '10尺',
    area: '10尺半径球形护盾，中心在自己',
    duration: '10分钟/等级',
    savingThrow: '见描述',
    spellResist: '是',
    desc: '你创造一个七层颜色的护盾。每层有不同的效果：红（火伤害）、橙（酸伤害）、黄（电伤害）、绿（毒）、蓝（石化）、靛（疯狂）、紫（放逐）。只有次元门或类似效果可以穿透。'
  },

  // ===== 力量领域 (Strength) =====
  {
    id: 'enlarge-person',
    nameEn: 'Enlarge Person',
    nameZh: '人类定身术',
    level: { magus: 1, wizard: 1, sorcerer: 1 },
    school: 'transmutation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '近距 (25尺+5尺/2等级)',
    target: '一个人类生物/每等级，所有目标必须在15尺内',
    duration: '1分钟/等级',
    savingThrow: '强韧过则无效',
    spellResist: true,
    desc: '目标生物的体型增大一级（最小中型）。获得+2体型加值力量，-2敏捷，和天生攻击造成额外1d4点伤害。'
  },
  {
    id: 'bulls-strength',
    nameEn: "Bull's Strength",
    nameZh: '牛之力量',
    level: { cleric: 2, magus: 2, wizard: 2, sorcerer: 2, paladin: 2 },
    school: 'transmutation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '接触',
    target: '自己或生物/每等级，所有目标必须在接触范围内',
    duration: '1分钟/等级',
    savingThrow: '意志过则无效（无害）或意志过则无效（无害，对物体）',
    spellResist: '是（无害）或否（对物体）',
    desc: '目标获得+4力量增强加值。'
  },
  {
    id: 'rage',
    nameEn: 'Rage',
    nameZh: '狂暴术',
    level: { bard: 3, magus: 3, wizard: 3, sorcerer: 3 },
    school: 'enchantment',
    subSchool: 'compulsion',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '中距 (100尺+10尺/等级)',
    targets: '最多一个生物/每等级，所有目标必须在30尺内',
    duration: '1轮/等级',
    savingThrow: '意志过则无效',
    spellResist: true,
    desc: '目标进入狂暴状态，获得+2力量，+2体质，+1意志豁免，但承受-2护甲等级惩罚。狂暴结束时，目标疲累1轮。'
  },
  {
    id: 'spell-immunity',
    nameEn: 'Spell Immunity',
    nameZh: '法术免疫',
    level: { paladin: 4, cleric: 4 },
    school: 'abjuration',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '接触',
    target: '自己或生物/每等级，所有目标必须在接触范围内',
    duration: '1轮/等级',
    savingThrow: '意志过则无效（无害）或意志过则无效（无害，对物体）',
    spellResist: '是（无害）',
    desc: '目标对最多4个你指定的法术获得免疫。只能免疫等于或低于你施法者等级的法术。'
  },
  {
    id: 'righteous-might',
    nameEn: 'Righteous Might',
    nameZh: '正义威仪',
    level: { cleric: 5 },
    school: 'transmutation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '个人',
    target: '自己',
    duration: '1轮/等级',
    savingThrow: '无',
    spellResist: false,
    desc: '见战争领域5级法术。'
  },
  {
    id: 'heroism-greater',
    nameEn: 'Greater Heroism',
    nameZh: '高等英勇',
    level: { bard: 5, magus: 6, wizard: 6, sorcerer: 6 },
    school: 'enchantment',
    subSchool: 'compulsion',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '近距 (25尺+5尺/2等级)',
    target: '一个生物',
    duration: '1分钟/等级',
    savingThrow: '意志过则无效',
    spellResist: true,
    desc: '目标获得：所有豁免+4抗力加值，攻击和伤害+4抗力加值，技能检定+4抗力加值，免疫恐惧。'
  },
  {
    id: 'power-word-stun',
    nameEn: 'Power Word Stun',
    nameZh: '力令眩晕',
    level: { bard: 4, wizard: 8, sorcerer: 8 },
    school: 'enchantment',
    components: { verbal: true, somatic: false, material: false },
    castingTime: '标准动作',
    range: '近距 (25尺+5尺/2等级)',
    target: '一个生物',
    duration: '见描述',
    savingThrow: '意志过则无效',
    spellResist: true,
    desc: '见战争领域8级法术。'
  },
  {
    id: 'power-word-blind',
    nameEn: 'Power Word Blind',
    nameZh: '力令盲',
    level: { bard: 5, wizard: 7, sorcerer: 7 },
    school: 'enchantment',
    components: { verbal: true, somatic: false, material: false },
    castingTime: '标准动作',
    range: '近距 (25尺+5尺/2等级)',
    target: '一个生物',
    duration: '见描述',
    savingThrow: '无',
    spellResist: true,
    desc: '你对一个生物说出一个魔力词，使其目盲。如果目标有200点或更多生命值，无效果。101-199点生命值，目盲2d4轮。55-100点生命值，目盲1d4+1d4轮。少于55点生命值，永久目盲。'
  },
  {
    id: 'power-word-kill',
    nameEn: 'Power Word Kill',
    nameZh: '力令死',
    level: { wizard: 9, sorcerer: 9, bard: 6 },
    school: 'enchantment',
    components: { verbal: true, somatic: false, material: false },
    castingTime: '标准动作',
    range: '近距 (25尺+5尺/2等级)',
    target: '一个生物',
    duration: '瞬时',
    savingThrow: '无',
    spellResist: true,
    desc: '见战争领域9级法术。'
  },

  // ===== 保护领域 (Protection) =====
  {
    id: 'sanctuary',
    nameEn: 'Sanctuary',
    nameZh: '圣域术',
    level: { cleric: 1 },
    school: 'abjuration',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '接触',
    target: '自己或生物/每等级，所有目标必须在接触范围内',
    duration: '1轮/等级',
    savingThrow: '意志过则无效（无害）或意志过则无效（无害，对物体）',
    spellResist: '是（无害）',
    desc: '任何试图攻击你的生物必须成功意志豁免。失败则失去下一轮动作。如果你攻击或施展攻击性法术，法术结束。'
  },
  {
    id: 'shield-other',
    nameEn: 'Shield Other',
    nameZh: '保护他人',
    level: { cleric: 2, paladin: 2 },
    school: 'abjuration',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '接触',
    target: '一个生物',
    duration: '1小时/等级',
    savingThrow: '意志过则无效（无害）',
    spellResist: false,
    desc: '你和目标之间建立神秘连接。目标承受的伤害和状态效果，你承受其中的一半（向下取整）。你承受的伤害无视你的抗性和免疫。'
  },
  {
    id: 'protection-from-energy',
    nameEn: 'Protection from Energy',
    nameZh: '能量防护',
    level: { cleric: 3, magus: 3, wizard: 3, sorcerer: 3 },
    school: 'abjuration',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '接触',
    target: '自己或生物/每等级，所有目标必须在接触范围内',
    duration: '1轮/等级',
    savingThrow: '意志过则无效（无害）或意志过则无效（无害，对物体）',
    spellResist: '是（无害）或否（对物体）',
    desc: '目标对一种能量类型（酸、冷、电、火、音）获得12点/每等级（最大120点）的伤害减免。'
  },
  {
    id: 'spell-immunity',
    nameEn: 'Spell Immunity',
    nameZh: '法术免疫',
    level: { paladin: 4, cleric: 4 },
    school: 'abjuration',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '接触',
    target: '自己或生物/每等级，所有目标必须在接触范围内',
    duration: '1轮/等级',
    savingThrow: '意志过则无效（无害）或意志过则无效（无害，对物体）',
    spellResist: '是（无害）',
    desc: '见力量领域4级法术。'
  },
  {
    id: 'spell-resistance',
    nameEn: 'Spell Resistance',
    nameZh: '法术抗力',
    level: { cleric: 5 },
    school: 'abjuration',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '接触',
    target: '自己或生物/每等级，所有目标必须在接触范围内',
    duration: '1轮/等级',
    savingThrow: '意志过则无效（无害）或意志过则无效（无害，对物体）',
    spellResist: '是（无害）或否（对物体）',
    desc: '目标获得+6法术抗力。'
  },
  {
    id: 'antimagic-field',
    nameEn: 'Antimagic Field',
    nameZh: '反魔法场',
    level: { cleric: 6, wizard: 6, sorcerer: 6 },
    school: 'abjuration',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '10尺',
    area: '10尺半径球形场，中心在自己',
    duration: '1轮/等级',
    savingThrow: '无',
    spellResist: false,
    desc: '你创造一个反魔法场。在场内，所有魔法效果、物品和生物的法术能力都被抑制。超魔和类法术能力也不能使用。'
  },
  {
    id: 'repulsion',
    nameEn: 'Repulsion',
    nameZh: '排斥术',
    level: { wizard: 7, sorcerer: 7, cleric: 7 },
    school: 'abjuration',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '个人',
    area: '10尺半径脉动球形场，中心在自己',
    duration: '1轮/等级',
    savingThrow: '意志过则无效（见描述）',
    spellResist: true,
    desc: '你周围10尺内的生物必须成功意志豁免才能接近你。失败的生物无法自愿进入区域。'
  },
  {
    id: 'mind-blank',
    nameEn: 'Mind Blank',
    nameZh: '心灵空白',
    level: { wizard: 8, sorcerer: 8, bard: 6 },
    school: 'abjuration',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '接触',
    target: '自己或生物/每等级，所有目标必须在接触范围内',
    duration: '1轮/等级',
    savingThrow: '意志过则无效（无害）或意志过则无效（无害，对物体）',
    spellResist: '是（无害）或否（对物体）',
    desc: '目标对心灵影响效果和探知效果（包括真实视觉）获得免疫。该法术也保护免受心灵感应和情绪读取。'
  },
  {
    id: 'prismatic-sphere',
    nameEn: 'Prismatic Sphere',
    nameZh: '虹光球',
    level: { wizard: 9, sorcerer: 9, cleric: 9 },
    school: 'abjuration',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '10尺',
    area: '10尺半径球形护盾，中心在自己',
    duration: '10分钟/等级',
    savingThrow: '见描述',
    spellResist: '是',
    desc: '见阳光领域9级法术。'
  },

  // ===== 植物领域 (Plant) =====
  {
    id: 'entangle',
    nameEn: 'Entangle',
    nameZh: '纠缠术',
    level: { druid: 1, ranger: 1 },
    school: 'transmutation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '远距 (400尺+40尺/等级)',
    area: '半径40尺+5尺/每等级扩散，中心在落点',
    duration: '1分钟/等级',
    savingThrow: '反射过则无效果',
    spellResist: false,
    desc: '区域内的植物变得活泼并纠缠进入的生物。被纠缠的生物速度减半，并受到-2攻击和护甲等级惩罚。'
  },
  {
    id: 'wood-shape',
    nameEn: 'Wood Shape',
    nameZh: '塑木术',
    level: { druid: 2 },
    school: 'transmutation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '接触',
    target: '未活化的木头物体，大小最多10立方尺/每等级',
    duration: '瞬时',
    savingThrow: '无',
    spellResist: false,
    desc: '你改变木头物体的形状。你可以创造木头容器、工具或简单武器。精细工作（如钥匙）需要DC15的巧手检定。'
  },
  {
    id: 'plant-growth',
    nameEn: 'Plant Growth',
    nameZh: '植物生长',
    level: { druid: 3, ranger: 3 },
    school: 'transmutation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '远距 (400尺+40尺/等级)',
    area: '半径1里格/每等级（最多4里格）的扩散，中心在自己',
    duration: '瞬时',
    savingThrow: '无',
    spellResist: false,
    desc: '你促进植物生长。在法术区域内，植物变得茂盛，灌木和树木生长更快。该法术可以使荒地变为可耕地，或使现有作物增产。'
  },
  {
    id: 'command-plants',
    nameEn: 'Command Plants',
    nameZh: '命令植物',
    level: { druid: 4 },
    school: 'transmutation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '近距 (25尺+5尺/2等级)',
    target: '多达每等级一个植物生物，所有目标必须在15尺内',
    duration: '1轮/等级',
    savingThrow: '意志过则无效',
    spellResist: true,
    desc: '植物生物服从你的精神命令。你可以命令它们攻击、移动、站立不动或执行简单任务。'
  },
  {
    id: 'wall-of-thorns',
    nameEn: 'Wall of Thorns',
    nameZh: '荆棘墙',
    level: { druid: 5 },
    school: 'conjuration',
    subSchool: 'creation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '近距 (25尺+5尺/2等级)',
    area: '直线释放的墙壁，长最多10尺/每等级，高最多10尺/每等级，厚2尺',
    duration: '1轮/等级',
    savingThrow: '无',
    spellResist: false,
    desc: '你创造一道荆棘和藤蔓墙。墙提供掩蔽（ROF +4，ALT +2）。任何试图穿过墙的生物受到每尺1d6点穿刺伤害。'
  },
  {
    id: 'animate-plants',
    nameEn: 'Animate Plants',
    nameZh: '活化植物',
    level: { druid: 6 },
    school: 'transmutation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '近距 (25尺+5尺/2等级)',
    targets: '区域内或每等级一个植物生物，所有目标必须在15尺内',
    duration: '1轮/等级',
    savingThrow: '意志过则无效',
    spellResist: true,
    desc: '你使植物生物获得行动能力。活化的植物可以移动和攻击。大型植物获得12点AC，小型植物获得14点AC。'
  },
  {
    id: 'liveoak',
    nameEn: 'Liveoak',
    nameZh: '活橡树',
    level: { druid: 7 },
    school: 'transmutation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '接触',
    target: '一棵橡树',
    duration: '1小时/等级',
    savingThrow: '无',
    spellResist: false,
    desc: '你使一棵橡树变得活跃并可移动。活橡树可以作为守卫，具有你的激活等级+你的德鲁伊等级的HD。'
  },
  {
    id: 'changestaff',
    nameEn: 'Changestaff',
    nameZh: '法杖变化',
    level: { druid: 8 },
    school: 'transmutation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '接触',
    target: '木制法杖，接触到的',
    duration: '1轮/等级',
    savingThrow: '无',
    spellResist: false,
    desc: '你使法杖变为一棵活橡树（如同活橡树法术）。你可以在法术持续时间内将法杖变回原状。'
  },
  {
    id: 'antipathy',
    nameEn: 'Antipathy',
    nameZh: '反感',
    level: { druid: 9, wizard: 9, sorcerer: 9 },
    school: 'enchantment',
    subSchool: 'compulsion',
    components: { verbal: true, somatic: true, material: true },
    material: '价值1500gp的稀有草药和矿物',
    castingTime: '标准动作',
    range: '远距 (400尺+40尺/等级)',
    target: '一个生物或物体，大小最多20立方尺/每等级',
    duration: '2小时/等级',
    savingThrow: '意志过则无效',
    spellResist: true,
    desc: '你对目标对象或位置施加一种情绪（如恐惧、厌恶、仇恨）。具有特定生命值类型的生物（你选择）会尽可能远离目标。'
  },

  // ===== 魔法领域 (Magic) =====
  {
    id: 'charm-person',
    nameEn: 'Charm Person',
    nameZh: '魅惑人类',
    level: { bard: 1, magus: 1, wizard: 1, sorcerer: 1 },
    school: 'enchantment',
    subSchool: 'charm',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '近距 (25尺+5尺/2等级)',
    target: '一个人类生物',
    duration: '1小时/等级',
    savingThrow: '意志过则无效',
    spellResist: true,
    desc: '目标对你产生好感（视为朋友）。它不会执行明显有害的动作。你可以命令它执行任务，但每轮它都可以重试豁免。'
  },
  {
    id: 'identify',
    nameEn: 'Identify',
    nameZh: '鉴定术',
    level: { bard: 2, magus: 2, wizard: 2, sorcerer: 2 },
    school: 'divination',
    components: { verbal: true, somatic: true, material: true },
    material: '价值100gp的珍珠和40gp的熏香',
    castingTime: '1小时',
    range: '0尺',
    target: '自己',
    duration: '见描述',
    savingThrow: '无',
    spellResist: false,
    desc: '你可以鉴定一个魔法物品。在施法时间内，你研究物品并学习其属性和功能。该法术不能鉴定被诅咒或被智敌防护的物品。'
  },
  {
    id: 'dispel-magic',
    nameEn: 'Dispel Magic',
    nameZh: '解魔法',
    level: { bard: 3, cleric: 3, druid: 3, magus: 3, wizard: 3, sorcerer: 3 },
    school: 'abjuration',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '近距 (25尺+5尺/2等级)',
    target: '一个法术效果、物品或生物',
    duration: '瞬时',
    savingThrow: '无',
    spellResist: false,
    desc: '你尝试解除一个法术效果、魔法物品或生物身上的魔法效果。每轮，你掷1d20 + 你的施法者等级（最大+10），对抗DC11 + 效果的施法者等级。成功则解除。'
  },
  {
    id: 'minor-creation',
    nameEn: 'Minor Creation',
    nameZh: '次级创造',
    level: { magus: 4, wizard: 4, sorcerer: 4 },
    school: 'conjuration',
    subSchool: 'creation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '0尺',
    target: '自己',
    duration: '1轮/等级',
    savingThrow: '无',
    spellResist: false,
    desc: '你创造一个非魔法，矿物或非 живой 物体，体积最多1立方尺/每等级。物体由普通材料制成，持续直到法术结束。不能创造对第0级法术有价值的物品。'
  },
  {
    id: 'permanency',
    nameEn: 'Permanency',
    nameZh: '永久化',
    level: { wizard: 5, sorcerer: 5 },
    school: 'universal',
    components: { verbal: true, somatic: true, material: true },
    material: '根据目标的法术不同，价值500-5000gp的稀有材料',
    castingTime: '2轮',
    range: '接触',
    target: '一个法术效果',
    duration: '永久',
    savingThrow: '见描述',
    spellResist: '见描述',
    desc: '你使另一个法术的效果永久化。不是所有法术都可以永久化。施法者等级必须至少等于法术等级的两倍。永久化法术需要昂贵的材料组件。'
  },
  {
    id: 'mislead',
    nameEn: 'Mislead',
    nameZh: '误导',
    level: { bard: 6, wizard: 6, sorcerer: 6 },
    school: 'illusion',
    subSchool: 'figment',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '个人',
    target: '自己',
    duration: '1轮/等级',
    savingThrow: '无或意志过则识破（见描述）',
    spellResist: '否或见描述',
    desc: '见诡计领域6级法术。'
  },
  {
    id: 'spell-turning',
    nameEn: 'Spell Turning',
    nameZh: '法术反转',
    level: { wizard: 7, sorcerer: 7, magus: 7 },
    school: 'abjuration',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '个人',
    target: '自己',
    duration: '1轮/等级',
    savingThrow: '无',
    spellResist: true,
    desc: '法术效果针对你时，有1d6+你的智力调整值（最小2）的机会被反转回施法者。每等级可以反转最多1个法术。'
  },
  {
    id: 'polymorph-any-object',
    nameEn: 'Polymorph Any Object',
    nameZh: '任意变化',
    level: { wizard: 8, sorcerer: 8 },
    school: 'transmutation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '远距 (400尺+40尺/等级)',
    target: '一个生物或物体',
    duration: '见描述',
    savingThrow: '强韧过则无效（对物体）',
    spellResist: '是',
    desc: '你将一个物体或生物变为另一个物体或生物。持续时间取决于目标和新形式的相似度。相似度越高，持续时间越长。'
  },
  {
    id: 'mage-s-layer',
    nameEn: "Mage's Slayer",
    nameZh: '法师杀手',
    level: { wizard: 9, sorcerer: 9 },
    school: 'abjuration',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '接触',
    target: '一把武器',
    duration: '1轮/等级',
    savingThrow: '意志过则无效（无害，对物体）',
    spellResist: true,
    desc: '你使一把武器获得+5增强加值和对施法者额外造成2d6点伤害。如果武器攻击施法者，目标失去其下一轮动作。'
  },

  // ===== 幸运领域 (Luck) =====
  {
    id: 'true-strike',
    nameEn: 'True Strike',
    nameZh: '精准打击',
    level: { magus: 1, wizard: 1, sorcerer: 1 },
    school: 'divination',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '个人',
    target: '自己',
    duration: '见描述',
    savingThrow: '无',
    spellResist: false,
    desc: '见战争领域1级法术。'
  },
  {
    id: 'aid',
    nameEn: 'Aid',
    nameZh: '援助术',
    level: { cleric: 2, paladin: 2 },
    school: 'enchantment',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '近距 (25尺+5尺/2等级)',
    target: '自己或生物/每等级，所有目标必须在30尺内',
    duration: '1分钟/等级',
    savingThrow: '意志过则无效（无害）',
    spellResist: true,
    desc: '目标获得+1幸运加值所有技能检定，+1d8临时生命值，+1幸运加值所有豁免。'
  },
  {
    id: 'rage',
    nameEn: 'Rage',
    nameZh: '狂暴术',
    level: { bard: 3, magus: 3, wizard: 3, sorcerer: 3 },
    school: 'enchantment',
    subSchool: 'compulsion',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '中距 (100尺+10尺/等级)',
    targets: '最多一个生物/每等级，所有目标必须在30尺内',
    duration: '1轮/等级',
    savingThrow: '意志过则无效',
    spellResist: true,
    desc: '见力量领域3级法术。'
  },
  {
    id: 'freedom-of-movement',
    nameEn: 'Freedom of Movement',
    nameZh: '行动自由',
    level: { cleric: 4, druid: 4 },
    school: 'abjuration',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '个人',
    target: '自己',
    duration: '1轮/等级',
    savingThrow: '意志过则无效（无害）',
    spellResist: true,
    desc: '你免疫麻痹、定身、束缚和困陷效果。你也可以在水中正常行动，不受影响。'
  },
  {
    id: 'break-enchantment',
    nameEn: 'Break Enchantment',
    nameZh: '解除魔法',
    level: { bard: 5, cleric: 5, magus: 5, wizard: 5, sorcerer: 5 },
    school: 'abjuration',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '近距 (25尺+5尺/2等级)',
    target: '最多一个生物/每等级，所有目标必须在25尺内',
    duration: '瞬时',
    savingThrow: '见描述',
    spellResist: '见描述',
    desc: '你尝试解除目标身上的魅惑、 compelled、诅咒或塑能效果。每轮，你掷1d20 + 你的施法者等级（最大+10），对抗DC11 + 效果的施法者等级。'
  },
  {
    id: 'mislead',
    nameEn: 'Mislead',
    nameZh: '误导',
    level: { bard: 6, wizard: 6, sorcerer: 6 },
    school: 'illusion',
    subSchool: 'figment',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '个人',
    target: '自己',
    duration: '1轮/等级',
    savingThrow: '无或意志过则识破（见描述）',
    spellResist: '否或见描述',
    desc: '见诡计领域6级法术。'
  },
  {
    id: 'spell-turning',
    nameEn: 'Spell Turning',
    nameZh: '法术反转',
    level: { wizard: 7, sorcerer: 7 },
    school: 'abjuration',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '个人',
    target: '自己',
    duration: '1轮/等级',
    savingThrow: '无',
    spellResist: true,
    desc: '见魔法领域7级法术。'
  },
  {
    id: 'moment-of-prescience',
    nameEn: 'Moment of Prescience',
    nameZh: '先见之明',
    level: { wizard: 8, sorcerer: 8, bard: 6 },
    school: 'divination',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '个人',
    target: '自己',
    duration: '见描述',
    savingThrow: '无',
    spellResist: false,
    desc: '你获得对未来的短暂洞察。在某个未来轮次（在法术结束前），你可以添加一个洞察加值到任何一次攻击骰、豁免或技能检定。加值等于你的施法者等级（最大+20）。'
  },
  {
    id: 'miracle',
    nameEn: 'Miracle',
    nameZh: '奇迹',
    level: { cleric: 9 },
    school: 'evocation',
    components: { verbal: true, somatic: true, material: true },
    material: 'XP花费或祈祷',
    castingTime: '标准动作',
    range: '见描述',
    target: '见描述',
    duration: '见描述',
    savingThrow: '见描述',
    spellResist: '见描述',
    desc: '你请求你的神祇干预。可以完成几乎任何与神祇领域相关的效果。与祈愿术类似，但不需要材料组件，而是需要神祇的恩典。'
  },

  // ===== 秩序领域 (Law) =====
  {
    id: 'command',
    nameEn: 'Command',
    nameZh: '命令术',
    level: { cleric: 1 },
    school: 'enchantment',
    subSchool: 'compulsion',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '近距 (25尺+5尺/2等级)',
    target: '一个生物',
    duration: '1轮',
    savingThrow: '意志过则无效',
    spellResist: true,
    desc: '你对一个生物说出一个单词命令（如"倒下"、"停止"、"投降"）。目标必须服从。如果命令明显有害，法术自动失败。'
  },
  {
    id: 'calm-emotions',
    nameEn: 'Calm Emotions',
    nameZh: '平静情绪',
    level: { bard: 2, cleric: 2 },
    school: 'enchantment',
    subSchool: 'compulsion',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '近距 (25尺+5尺/2等级)',
    area: '半径15尺+5尺/每2等级的扩散，中心在落点',
    duration: '1轮/等级',
    savingThrow: '意志过则无效',
    spellResist: true,
    desc: '区域内所有生物被平静。他们不能使用狂暴、恐惧或类似能力。受到影响的不死生物、异界生物和教会敌人可以被压制。'
  },
  {
    id: 'suggestion',
    nameEn: 'Suggestion',
    nameZh: '催眠暗示',
    level: { bard: 3, wizard: 3, sorcerer: 3 },
    school: 'enchantment',
    subSchool: 'compulsion',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '近距 (25尺+5尺/2等级)',
    target: '一个生物',
    duration: '1小时/等级',
    savingThrow: '意志过则无效',
    spellResist: true,
    desc: '你向目标提出一个合理的建议（不超过25词）。目标倾向于按照建议行动。建议必须听起来合理，不能明显有害。'
  },
  {
    id: 'discern-lies',
    nameEn: 'Discern Lies',
    nameZh: '识破谎言',
    level: { cleric: 4, inquisitor: 3 },
    school: 'divination',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '近距 (25尺+5尺/2等级)',
    target: '一个生物',
    duration: '1轮/等级',
    savingThrow: '意志过则无效',
    spellResist: '否',
    desc: '你察觉目标何时说谎。每次目标对你或他人说谎，你自动察觉（不需要检定）。该法术不排除欺骗或虚张声势。'
  },
  {
    id: 'mark-of-justice',
    nameEn: 'Mark of Justice',
    nameZh: '正义标记',
    level: { cleric: 5 },
    school: 'enchantment',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '10分钟',
    range: '接触',
    target: '一个生物',
    duration: '永久（见描述）',
    savingThrow: '意志过则无效',
    spellResist: true,
    desc: '你在目标身上施加一个标记。如果你（或你的指定代表）命令目标执行某些行为，而目标违反，惩罚自动发生。惩罚可以是伤害、状态效果或能力降低。'
  },
  {
    id: 'heroism-greater',
    nameEn: 'Greater Heroism',
    nameZh: '高等英勇',
    level: { bard: 5, magus: 6, wizard: 6, sorcerer: 6 },
    school: 'enchantment',
    subSchool: 'compulsion',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '近距 (25尺+5尺/2等级)',
    target: '一个生物',
    duration: '1分钟/等级',
    savingThrow: '意志过则无效',
    spellResist: true,
    desc: '见力量领域6级法术。'
  },
  {
    id: 'dictum',
    nameEn: 'Dictum',
    nameZh: '律令',
    level: { cleric: 7 },
    school: 'evocation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '40尺',
    area: '40尺锥形',
    duration: '瞬时',
    savingThrow: '见描述',
    spellResist: true,
    desc: '你说出秩序之语。混乱阵营的生物受到以下效果：2d6点伤害，耳聋1d4轮，嘶哑1d4轮，昏迷1d4轮（通过强韧豁免避免），死亡（通过强韧豁免避免）。'
  },
  {
    id: 'shield-of-law',
    nameEn: 'Shield of Law',
    nameZh: '秩序之盾',
    level: { cleric: 8 },
    school: 'abjuration',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '20尺',
    area: '20尺半径扩散，中心在落点',
    duration: '1轮/等级',
    savingThrow: '见描述',
    spellResist: true,
    desc: '混乱阵营的生物进入区域受到伤害并恶心。区域提供对混乱生物的防御。'
  },
  {
    id: 'summon-monster-9-law',
    nameEn: 'Summon Monster IX (Law)',
    nameZh: '召唤怪物IX（秩序）',
    level: { cleric: 9 },
    school: 'conjuration',
    subSchool: 'summoning',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '1轮',
    range: '近距 (25尺+5尺/2等级)',
    target: '一个生物',
    duration: '1轮/等级',
    savingThrow: '无',
    spellResist: true,
    desc: '召唤一个秩序领域的强大盟友（如秩序元素长老、天使）为你作战。'
  },

  // ===== 知识领域 (Knowledge) =====
  {
    id: 'detect-magic',
    nameEn: 'Detect Magic',
    nameZh: '侦测魔法',
    level: { bard: 1, cleric: 1, magus: 1, wizard: 1, sorcerer: 1 },
    school: 'divination',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '60尺',
    area: '锥形区域，从自己发出',
    duration: '专注，最长1轮/等级',
    savingThrow: '无',
    spellResist: false,
    desc: '你感知魔法 aura。每轮，你可以检测一个物体或生物是否具有魔法。你可以学习魔法学派和施法者等级。'
  },
  {
    id: 'detect-thoughts',
    nameEn: 'Detect Thoughts',
    nameZh: '侦测思想',
    level: { bard: 2, magus: 2, wizard: 2, sorcerer: 2 },
    school: 'divination',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '60尺',
    area: '锥形区域，从自己发出',
    duration: '专注，最长1轮/等级',
    savingThrow: '意志过则无效',
    spellResist: true,
    desc: '你侦测表面思想（最突出的思想）。你可以读取目标的具体想法（如有语言），但目标若知道你正在读心，可以通过强韧豁免结束法术。'
  },
  {
    id: 'suggestion',
    nameEn: 'Suggestion',
    nameZh: '催眠暗示',
    level: { bard: 3, wizard: 3, sorcerer: 3 },
    school: 'enchantment',
    subSchool: 'compulsion',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '近距 (25尺+5尺/2等级)',
    target: '一个生物',
    duration: '1小时/等级',
    savingThrow: '意志过则无效',
    spellResist: true,
    desc: '见秩序领域3级法术。'
  },
  {
    id: 'discern-lies',
    nameEn: 'Discern Lies',
    nameZh: '识破谎言',
    level: { cleric: 4, inquisitor: 3 },
    school: 'divination',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '近距 (25尺+5尺/2等级)',
    target: '一个生物',
    duration: '1轮/等级',
    savingThrow: '意志过则无效',
    spellResist: '否',
    desc: '见秩序领域4级法术。'
  },
  {
    id: 'true-seeing',
    nameEn: 'True Seeing',
    nameZh: '真实视觉',
    level: { cleric: 5, magus: 5, wizard: 5, sorcerer: 5 },
    school: 'divination',
    components: { verbal: true, somatic: true, material: true },
    material: '价值5000gp的蓝宝石粉末',
    castingTime: '标准动作',
    range: '接触',
    target: '自己或生物/每等级，所有目标必须在接触范围内',
    duration: '1轮/等级',
    savingThrow: '意志过则无效（无害）或意志过则无效（无害，对物体）',
    spellResist: '是（无害）或否（对物体）',
    desc: '目标获得真实视觉，可以看穿幻象、隐形、移位、投影和灵体。也可以看到灵体和移位生物的真实形态。'
  },
  {
    id: 'find-the-path',
    nameEn: 'Find the Path',
    nameZh: '寻路',
    level: { cleric: 6, druid: 6 },
    school: 'divination',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '接触',
    target: '接触到的生物',
    duration: '1分钟/等级',
    savingThrow: '无',
    spellResist: false,
    desc: '见旅行领域6级法术。'
  },
  {
    id: 'legend-lore',
    nameEn: 'Legend Lore',
    nameZh: '传说知识',
    level: { bard: 7, wizard: 7, sorcerer: 7 },
    school: 'divination',
    components: { verbal: true, somatic: true, material: true },
    material: '价值500gp的稀有材料和1小时冥想',
    castingTime: '1小时',
    range: '个人',
    target: '自己',
    duration: '见描述',
    savingThrow: '无',
    spellResist: false,
    desc: '你学习关于一个人、地点或事物的传说知识。获得的信息量取决于主题的知名度和你投入的时间。'
  },
  {
    id: 'discern-location',
    nameEn: 'Discern Location',
    nameZh: '定位',
    level: { cleric: 8, wizard: 8, sorcerer: 8 },
    school: 'divination',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '1轮',
    range: '无限制',
    target: '自己',
    duration: '瞬时',
    savingThrow: '无',
    spellResist: false,
    desc: '你精确知道一个生物或物体的位置，无论距离多远，甚至跨位面。目标必须被你接触过或拥有其个人物品。'
  },
  {
    id: 'foresight',
    nameEn: 'Foresight',
    nameZh: '预见',
    level: { druid: 9, wizard: 9, sorcerer: 9 },
    school: 'divination',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '接触',
    target: '自己或生物/每等级，所有目标必须在接触范围内',
    duration: '1轮/等级',
    savingThrow: '意志过则无效（无害）或意志过则无效（无害，对物体）',
    spellResist: '是（无害）或否（对物体）',
    desc: '目标获得对危险的警报。在受到攻击前，目标自动获得一个额外的闪避加值或先攻加值。该法术也提供对陷阱和伏击的预警。'
  },

  // ===== 善良领域 (Good) =====
  {
    id: 'bless',
    nameEn: 'Bless',
    nameZh: '祝福术',
    level: { cleric: 1, paladin: 1 },
    school: 'enchantment',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '50尺',
    area: '50尺半径扩散，中心在落点',
    duration: '1轮/等级',
    savingThrow: '无',
    spellResist: '是（无害）',
    desc: '区域内所有盟友获得+1士气加值攻击骰和豁免对抗恐惧。'
  },
  {
    id: 'shield-other',
    nameEn: 'Shield Other',
    nameZh: '保护他人',
    level: { cleric: 2, paladin: 2 },
    school: 'abjuration',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '接触',
    target: '一个生物',
    duration: '1小时/等级',
    savingThrow: '意志过则无效（无害）',
    spellResist: false,
    desc: '见保护领域2级法术。'
  },
  {
    id: 'suggestion',
    nameEn: 'Suggestion',
    nameZh: '催眠暗示',
    level: { bard: 3, wizard: 3, sorcerer: 3 },
    school: 'enchantment',
    subSchool: 'compulsion',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '近距 (25尺+5尺/2等级)',
    target: '一个生物',
    duration: '1小时/等级',
    savingThrow: '意志过则无效',
    spellResist: true,
    desc: '见秩序领域3级法术。'
  },
  {
    id: 'holy-smite',
    nameEn: 'Holy Smite',
    nameZh: '神圣重击',
    level: { cleric: 4, paladin: 4 },
    school: 'evocation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '近距 (25尺+5尺/2等级)',
    area: '半径10尺+5尺/每3等级的扩散，中心在落点',
    duration: '瞬时',
    savingThrow: '反射过则无效果',
    spellResist: true,
    desc: '你释放神圣能量。邪恶阵营的生物受到4d8点神圣伤害，善良生物不受影响，其他生物受到2d8点伤害。邪恶生物如果失败强韧豁免则目盲1轮。'
  },
  {
    id: 'dispel-evil',
    nameEn: 'Dispel Evil',
    nameZh: '驱逐邪恶',
    level: { cleric: 5, paladin: 4 },
    school: 'abjuration',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '近距 (25尺+5尺/2等级)',
    target: '见描述',
    duration: '1轮/等级',
    savingThrow: '见描述',
    spellResist: '是',
    desc: '你对邪恶生物和物体的影响：1) 在回合内迫使邪恶生物远离你；2) 对邪恶异界生物和不死生物进行放逐尝试；3) 保护被邪恶生物或物体影响的盟友。'
  },
  {
    id: 'blade-barrier',
    nameEn: 'Blade Barrier',
    nameZh: '刀墙术',
    level: { cleric: 6 },
    school: 'evocation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '近距 (25尺+5尺/2等级)',
    area: '环形墙，半径最多10尺+1尺/等级',
    duration: '1轮/等级',
    savingThrow: '反射过则伤害减半',
    spellResist: true,
    desc: '见战争领域6级法术。'
  },
  {
    id: 'holy-word',
    nameEn: 'Holy Word',
    nameZh: '神圣之语',
    level: { cleric: 7 },
    school: 'evocation',
    components: { verbal: true, somatic: false, material: false },
    castingTime: '标准动作',
    range: '40尺',
    area: '40尺锥形',
    duration: '瞬时',
    savingThrow: '见描述',
    spellResist: true,
    desc: '你说出神圣之语。邪恶阵营的生物受到以下效果：2d6点伤害，耳聋1d4轮，嘶哑1d4轮，昏迷1d4轮（通过强韧豁免避免），死亡（通过强韧豁免避免）。'
  },
  {
    id: 'holy-aura',
    nameEn: 'Holy Aura',
    nameZh: '神圣灵光',
    level: { cleric: 8 },
    school: 'abjuration',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '20尺',
    area: '20尺半径扩散，中心在落点',
    duration: '1轮/等级',
    savingThrow: '见描述',
    spellResist: true,
    desc: '邪恶生物进入区域受到伤害并目盲。区域提供对邪恶生物的防御。盟友对邪恶攻击获得+4抗力加值。'
  },
  {
    id: 'summon-monster-9-good',
    nameEn: 'Summon Monster IX (Good)',
    nameZh: '召唤怪物IX（善良）',
    level: { cleric: 9 },
    school: 'conjuration',
    subSchool: 'summoning',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '1轮',
    range: '近距 (25尺+5尺/2等级)',
    target: '一个生物',
    duration: '1轮/等级',
    savingThrow: '无',
    spellResist: true,
    desc: '召唤一个善良领域的强大盟友（如天使长老、圣者）为你作战。'
  },

  // ===== 火焰领域 (Fire) =====
  {
    id: 'burning-hands',
    nameEn: 'Burning Hands',
    nameZh: '燃烧之手',
    level: { magus: 1, wizard: 1, sorcerer: 1 },
    school: 'evocation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '0尺',
    area: '15尺锥形，从自己发出',
    duration: '瞬时',
    savingThrow: '反射过则伤害减半',
    spellResist: true,
    desc: '你释放一道火焰锥形。所有在锥形中的生物受到1d4点/每等级（最大5d4）的火焰伤害。'
  },
  {
    id: 'produce-flame',
    nameEn: 'Produce Flame',
    nameZh: '生火术',
    level: { druid: 2 },
    school: 'evocation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '0尺',
    target: '自己',
    duration: '1轮/等级',
    savingThrow: '无',
    spellResist: false,
    desc: '你创造一团小火球。你可以用它作为远程接触攻击（射程10尺），造成1d6+1点每等级（最大+5）的火焰伤害。或者，你可以用它点燃物体。'
  },
  {
    id: 'fireball',
    nameEn: 'Fireball',
    nameZh: '火球术',
    level: { magus: 3, wizard: 3, sorcerer: 3 },
    school: 'evocation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '远距 (400尺+40尺/等级)',
    area: '半径20尺+5尺/每2等级的球形扩散，中心在落点',
    duration: '瞬时',
    savingThrow: '反射过则伤害减半',
    spellResist: true,
    desc: '你投掷一个火球。爆炸对区域内所有生物造成1d6点/每等级（最大10d6）的火焰伤害。'
  },
  {
    id: 'wall-of-fire',
    nameEn: 'Wall of Fire',
    nameZh: '火焰墙',
    level: { druid: 4, magus: 4, wizard: 4, sorcerer: 4 },
    school: 'evocation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '中距 (100尺+10尺/等级)',
    area: '直线释放的墙壁，长最多10尺/每等级，高最多10尺/每等级，厚5尺',
    duration: '1轮/等级',
    savingThrow: '反射过则伤害减半',
    spellResist: true,
    desc: '你创造一道火焰墙。墙每轮对穿过或在内的生物造成2d6点火焰伤害。从火侧攻击的生物受到额外1d6点伤害。'
  },
  {
    id: 'fire-shield',
    nameEn: 'Fire Shield',
    nameZh: '火焰盾',
    level: { magus: 5, wizard: 5, sorcerer: 5 },
    school: 'evocation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '个人',
    target: '自己',
    duration: '1轮/等级',
    savingThrow: '无',
    spellResist: false,
    desc: '见阳光领域5级法术。'
  },
  {
    id: 'fire-seeds',
    nameEn: 'Fire Seeds',
    nameZh: '火种术',
    level: { druid: 6, cleric: 6 },
    school: 'transmutation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '接触',
    target: '最多四个种子或坚果',
    duration: '1天/等级或直到触发',
    savingThrow: '反射过则伤害减半',
    spellResist: true,
    desc: '见阳光领域6级法术。'
  },
  {
    id: 'fire-storm',
    nameEn: 'Fire Storm',
    nameZh: '暴火术',
    level: { cleric: 7, druid: 7 },
    school: 'evocation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '远距 (400尺+40尺/等级)',
    area: '两个10尺方形区域/每等级，每两个之间相距不超过30尺',
    duration: '瞬时',
    savingThrow: '反射过则伤害减半',
    spellResist: true,
    desc: '你召唤火焰风暴。每个区域对内部生物造成13d6点火焰伤害。水下施放该法术将自动失败。'
  },
  {
    id: 'incendiary-cloud',
    nameEn: 'Incendiary Cloud',
    nameZh: '燃烧云雾',
    level: { wizard: 8, sorcerer: 8, druid: 8 },
    school: 'conjuration',
    subSchool: 'creation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '远距 (400尺+40尺/等级)',
    area: '20尺半径球形云，中心在落点',
    duration: '1轮/等级',
    savingThrow: '反射过则伤害减半',
    spellResist: false,
    desc: '见阳光领域8级法术。'
  },
  {
    id: 'elemental-swarm',
    nameEn: 'Elemental Swarm',
    nameZh: '元素群',
    level: { druid: 9, cleric: 9 },
    school: 'conjuration',
    subSchool: 'summoning',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '近距 (25尺+5尺/2等级)',
    target: '见描述',
    duration: '1轮/等级',
    savingThrow: '无',
    spellResist: true,
    desc: '你召唤多个元素生物为你作战。可以召唤火元素、水元素、土元素或气元素。总数不超过你的施法者等级。'
  },

  // ===== 邪恶领域 (Evil) =====
  {
    id: 'cause-fear',
    nameEn: 'Cause Fear',
    nameZh: '制造恐惧',
    level: { cleric: 1, wizard: 1, sorcerer: 1 },
    school: 'necromancy',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '近距 (25尺+5尺/2等级)',
    target: '一个生物',
    duration: '1轮/等级',
    savingThrow: '意志过则无效',
    spellResist: true,
    desc: '目标受到恐惧影响。如果目标有4HD或更少，它被惊惧（颤抖无法行动）。否则，它受到-2惩罚所有技能和攻击。'
  },
  {
    id: 'desecrate',
    nameEn: 'Desecrate',
    nameZh: '亵渎术',
    level: { cleric: 2 },
    school: 'evocation',
    components: { verbal: true, somatic: true, material: true },
    material: '价值25gp的奉献邪恶神祇的祭品',
    castingTime: '标准动作',
    range: '近距 (25尺+5尺/2等级)',
    area: '半径20尺+5尺/每2等级的扩散，中心在落点',
    duration: '1轮/等级',
    savingThrow: '无',
    spellResist: false,
    desc: '你亵渎区域。邪恶生物在区域内获得+1血量加值（最大+3）。不死生物被创建时有+1血量加值。善良生物在区域内受到-1所有检定惩罚。'
  },
  {
    id: 'contagion',
    nameEn: 'Contagion',
    nameZh: '疫病术',
    level: { cleric: 3, druid: 3 },
    school: 'necromancy',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '接触',
    target: '一个生物',
    duration: '瞬时',
    savingThrow: '强韧过则无效',
    spellResist: true,
    desc: '你使目标感染一种疾病（如震虎热、腐热病等）。目标必须成功强韧豁免，否则立即感染。疾病有潜伏期和伤害效果。'
  },
  {
    id: 'unholy-blight',
    nameEn: 'Unholy Blight',
    nameZh: '邪秽荒芜',
    level: { cleric: 4 },
    school: 'evocation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '近距 (25尺+5尺/2等级)',
    area: '半径10尺+5尺/每3等级的扩散，中心在落点',
    duration: '瞬时',
    savingThrow: '反射过则无效果',
    spellResist: true,
    desc: '你释放邪秽能量。善良阵营的生物受到4d8点邪恶伤害，邪恶生物不受影响，其他生物受到2d8点伤害。善良生物如果失败强韧豁免则目盲1轮。'
  },
  {
    id: 'dispel-good',
    nameEn: 'Dispel Good',
    nameZh: '驱逐善良',
    level: { cleric: 5 },
    school: 'abjuration',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '近距 (25尺+5尺/2等级)',
    target: '见描述',
    duration: '1轮/等级',
    savingThrow: '见描述',
    spellResist: '是',
    desc: '你对善良生物和物体的影响：1) 在回合内迫使善良生物远离你；2) 对善良异界生物和圣者进行放逐尝试；3) 保护被善良生物或物体影响的盟友。'
  },
  {
    id: 'create-undead',
    nameEn: 'Create Undead',
    nameZh: '创造不死生物',
    level: { cleric: 6, wizard: 7, sorcerer: 7 },
    school: 'necromancy',
    components: { verbal: true, somatic: true, material: true },
    material: '价值500gp的valueon尸体和宝石',
    castingTime: '1轮',
    range: '近距 (25尺+5尺/2等级)',
    target: '一具尸体',
    duration: '瞬时',
    savingThrow: '无',
    spellResist: false,
    desc: '你将一具尸体变为不死生物（如尸妖、幽魂、木乃伊或吸血鬼）。不死生物的HD不能超过你的施法者等级-2。'
  },
  {
    id: 'unholy-word',
    nameEn: 'Unholy Word',
    nameZh: '邪秽之语',
    level: { cleric: 7 },
    school: 'evocation',
    components: { verbal: true, somatic: false, material: false },
    castingTime: '标准动作',
    range: '40尺',
    area: '40尺锥形',
    duration: '瞬时',
    savingThrow: '见描述',
    spellResist: true,
    desc: '你说出邪秽之语。善良阵营的生物受到以下效果：2d6点伤害，耳聋1d4轮，嘶哑1d4轮，昏迷1d4轮（通过强韧豁免避免），死亡（通过强韧豁免避免）。'
  },
  {
    id: 'unholy-aura',
    nameEn: 'Unholy Aura',
    nameZh: '邪秽灵光',
    level: { cleric: 8 },
    school: 'abjuration',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '20尺',
    area: '20尺半径扩散，中心在落点',
    duration: '1轮/等级',
    savingThrow: '见描述',
    spellResist: true,
    desc: '善良生物进入区域受到伤害并目盲。区域提供对善良生物的防御。盟友对善良攻击获得+4抗力加值。'
  },
  {
    id: 'summon-monster-9-evil',
    nameEn: 'Summon Monster IX (Evil)',
    nameZh: '召唤怪物IX（邪恶）',
    level: { cleric: 9 },
    school: 'conjuration',
    subSchool: 'summoning',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '1轮',
    range: '近距 (25尺+5尺/2等级)',
    target: '一个生物',
    duration: '1轮/等级',
    savingThrow: '无',
    spellResist: true,
    desc: '召唤一个邪恶领域的强大盟友（如恶魔、魔鬼）为你作战。'
  },

  // ===== 大地领域 (Earth) =====
  {
    id: 'magic-stone',
    nameEn: 'Magic Stone',
    nameZh: '魔法石',
    level: { druid: 1, cleric: 1 },
    school: 'transmutation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '接触',
    target: '3个石弹或1个石弹/每等级',
    duration: '30分钟或直到击中',
    savingThrow: '无',
    spellResist: false,
    desc: '你使石弹变为魔法。它们可以作为远程武器投掷，造成1d6+1点钝击伤害（对小型生物）或1d6点（对中型生物）。对火属性生物造成+1d6点伤害。'
  },
  {
    id: 'soften-earth-and-stone',
    nameEn: 'Soften Earth and Stone',
    nameZh: '软化土石',
    level: { druid: 2 },
    school: 'transmutation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '近距 (25尺+5尺/2等级)',
    area: '半径10尺+5尺/每等级方形区域，中心在落点',
    duration: '瞬时',
    savingThrow: '无',
    spellResist: false,
    desc: '你软化泥土或石头。软化的泥土变为困难地形。软化的石头可以更容易挖掘。该法术不能影响活体或魔法石头。'
  },
  {
    id: 'meld-into-stone',
    nameEn: 'Meld into Stone',
    nameZh: '融入石头',
    level: { druid: 3 },
    school: 'transmutation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '接触',
    target: '自己',
    duration: '1轮/等级',
    savingThrow: '无',
    spellResist: false,
    desc: '你融入石墙或石头中。你可以看到和听到外面，但不能攻击或施法。你可以离开石头的任何一侧。在石头内，你不需要呼吸、进食或睡眠。'
  },
  {
    id: 'stone-shape',
    nameEn: 'Stone Shape',
    nameZh: '塑石术',
    level: { cleric: 4, druid: 4 },
    school: 'transmutation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '接触',
    target: '未活化的石头物体，大小最多10立方尺/每等级',
    duration: '瞬时',
    savingThrow: '无',
    spellResist: false,
    desc: '你改变石头物体的形状。你可以创造石制容器、石椅或简单石制工具。精细工作（如石钥匙）需要DC15的巧手检定。'
  },
  {
    id: 'wall-of-stone',
    nameEn: 'Wall of Stone',
    nameZh: '石墙术',
    level: { cleric: 5, druid: 5, magus: 5, wizard: 5, sorcerer: 5 },
    school: 'conjuration',
    subSchool: 'creation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '近距 (25尺+5尺/2等级)',
    area: '直线释放的墙壁，长最多10尺/每等级，高最多10尺/每等级，厚2尺',
    duration: '瞬时',
    savingThrow: '无',
    spellResist: false,
    desc: '你创造一道石墙。墙可以水平或垂直放置。墙的AC为5，每10立方尺有180点生命值。墙可以倒塌造成伤害。'
  },
  {
    id: 'flesh-to-stone',
    nameEn: 'Flesh to Stone',
    nameZh: '血肉石化',
    level: { wizard: 6, sorcerer: 6, cleric: 6 },
    school: 'transmutation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '中距 (100尺+10尺/等级)',
    target: '一个生物',
    duration: '永久',
    savingThrow: '强韧过则无效',
    spellResist: true,
    desc: '你将目标变为石头。目标变为石化状态（无意识、无生命、恒定状态）。可以通过解石化或类似法术恢复。'
  },
  {
    id: 'earthquake',
    nameEn: 'Earthquake',
    nameZh: '地震术',
    level: { cleric: 7, druid: 7 },
    school: 'evocation',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '远距 (400尺+40尺/等级)',
    area: '半径40尺+5尺/每等级扩散，中心在落点',
    duration: '1轮',
    savingThrow: '见描述',
    spellResist: false,
    desc: '你引起地震。效果包括：地面裂开、建筑倒塌、生物倒地、石制物体破碎。在地下施放，可能造成隧道坍塌。'
  },
  {
    id: 'repel-metal-or-stone',
    nameEn: 'Repel Metal or Stone',
    nameZh: '排斥金属或石头',
    level: { druid: 8 },
    school: 'abjuration',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '60尺',
    area: '60尺锥形',
    duration: '1轮/等级',
    savingThrow: '意志过则无效（对物体）',
    spellResist: false,
    desc: '你排斥金属和石头物体。物体被推向远离你的方向。大小和重量决定推力。生物穿着金属护甲也必须豁免。'
  },
  {
    id: 'elemental-swarm',
    nameEn: 'Elemental Swarm',
    nameZh: '元素群',
    level: { druid: 9, cleric: 9 },
    school: 'conjuration',
    subSchool: 'summoning',
    components: { verbal: true, somatic: true, material: false },
    castingTime: '标准动作',
    range: '近距 (25尺+5尺/2等级)',
    target: '见描述',
    duration: '1轮/等级',
    savingThrow: '无',
    spellResist: true,
    desc: '见火焰领域9级法术。'
  }
];

// 过滤出尚未存在的法术
const spellsToAdd = newSpells.filter(spell => !existingIds.has(spell.id));

console.log(`需要添加的新法术: ${spellsToAdd.length}`);

if (spellsToAdd.length === 0) {
    console.log('所有法术已存在，无需添加。');
    process.exit(0);
}

// 生成JS代码
function serializeSpell(spell) {
    const lines = [];
    lines.push('  {');
    lines.push(`    id: '${spell.id}',`);
    lines.push(`    nameEn: '${spell.nameEn}',`);
    lines.push(`    nameZh: '${spell.nameZh}',`);
    
    // level
    const levelEntries = Object.entries(spell.level).map(([k, v]) => `'${k}': ${v}`).join(', ');
    lines.push(`    level: { ${levelEntries} },`);
    
    lines.push(`    school: '${spell.school}',`);
    
    if (spell.subSchool) {
        lines.push(`    subSchool: '${spell.subSchool}',`);
    }
    
    // components
    const compEntries = Object.entries(spell.components).map(([k, v]) => `'${k}': ${v}`).join(', ');
    lines.push(`    components: { ${compEntries} },`);
    
    if (spell.material) {
        lines.push(`    material: '${spell.material}',`);
    }
    
    lines.push(`    castingTime: '${spell.castingTime}',`);
    lines.push(`    range: '${spell.range}',`);
    
    if (spell.target) {
        lines.push(`    target: '${spell.target}',`);
    } else if (spell.targets) {
        lines.push(`    targets: '${spell.targets}',`);
    } else if (spell.area) {
        lines.push(`    area: '${spell.area}',`);
    }
    
    lines.push(`    duration: '${spell.duration}',`);
    lines.push(`    savingThrow: '${spell.savingThrow}',`);
    lines.push(`    spellResist: ${JSON.stringify(spell.spellResist)},`);
    lines.push(`    desc: '${spell.desc.replace(/'/g, "\\'")}'`);
    
    lines.push('  }');
    return lines.join('\n');
}

// 在];前插入新法术
const newSpellsCode = spellsToAdd.map(spell => serializeSpell(spell)).join(',\n');
const insertPosition = content.lastIndexOf('];');
if (insertPosition === -1) {
    console.error('无法找到SPELLS数组的结束位置');
    process.exit(1);
}

// 在最后一个]之前插入
const before = content.substring(0, insertPosition - 1);
const after = content.substring(insertPosition - 1);

// 检查是否已有逗号
const needsComma = before.trim().endsWith('}') ? ',\n' : '\n';
const newContent = before + needsComma + newSpellsCode + '\n' + after;

// 备份原文件
const backupPath = spellsDataPath + '.bak4';
fs.copyFileSync(spellsDataPath, backupPath);
console.log(`已备份原文件到: ${backupPath}`);

// 写入新内容
fs.writeFileSync(spellsDataPath, newContent, 'utf8');
console.log(`成功添加 ${spellsToAdd.length} 个新法术到 spells-data.js`);

// 验证结果
const newContentCheck = fs.readFileSync(spellsDataPath, 'utf8');
const idRegexCheck = /id:\s*['"]([^'"]+)['"]/g;
const allIds = new Set();
let matchCheck;
let duplicateCount = 0;
while ((matchCheck = idRegexCheck.exec(newContentCheck)) !== null) {
    if (allIds.has(matchCheck[1])) {
        console.error(`发现重复ID: ${matchCheck[1]}`);
        duplicateCount++;
    }
    allIds.add(matchCheck[1]);
}

if (duplicateCount > 0) {
    console.error(`错误: 发现 ${duplicateCount} 个重复ID!`);
    console.log('正在恢复备份...');
    fs.copyFileSync(backupPath, spellsDataPath);
    process.exit(1);
}

console.log(`验证成功: 总共 ${allIds.size} 个法术，无重复ID`);
