# 第7批法术追加 - 6环法术为主
# 直接写入JS格式，避免JSON解析问题

new_spells_js = """

  // ===== 第7批追加：6环法术 =====
  {
    "id": "acid_fog_6",
    "nameEn": "Acid Fog",
    "nameZh": "酸雾",
    "level": 6,
    "school": "conjuration",
    "subSchool": "creation",
    "components": "V, S, M",
    "castingTime": "单动作",
    "range": "中距",
    "area": "雾气扩散范围（20尺半径，20尺高）",
    "duration": "1轮/级",
    "savingThrow": "无",
    "spellResist": "否",
    "desc": "你创造出一片浓密的黄绿色雾气，雾气对视线造成完全遮蔽（掩蔽+2）。雾气中的生物每轮受到1d6点强酸伤害，金属物品每轮受到2d6点伤害（无豁免）。雾气中心区域可被风吹散。",
    "material": "一小瓶酸液",
    "arcane": {"wizard": 6, "sorcerer": 6},
    "divine": null,
    "classes": {"wizard": 6, "sorcerer": 6}
  },
  {
    "id": "bear_s_endurance_mass",
    "nameEn": "Bear's Endurance, Mass",
    "nameZh": "群体熊之耐力",
    "level": 6,
    "school": "transmutation",
    "components": "V, S, M",
    "castingTime": "单动作",
    "range": "中距",
    "target": "你所选的最多每等级1个生物，彼此相距不超过30尺",
    "duration": "1分钟/级",
    "savingThrow": "意志过则无效（无害）",
    "spellResist": "可（无害）",
    "desc": "如熊之耐力法术，但可影响多个目标。每个受术者的体质获得+4增强加值。",
    "material": "一滴甘草汁",
    "arcane": null,
    "divine": {"cleric": 6, "druid": 6},
    "classes": {"cleric": 6, "druid": 6}
  },
  {
    "id": "bull_s_strength_mass",
    "nameEn": "Bull's Strength, Mass",
    "nameZh": "群体公牛之力",
    "level": 6,
    "school": "transmutation",
    "components": "V, S, M",
    "castingTime": "单动作",
    "range": "中距",
    "target": "你所选的最多每等级1个生物，彼此相距不超过30尺",
    "duration": "1分钟/级",
    "savingThrow": "意志过则无效（无害）",
    "spellResist": "可（无害）",
    "desc": "如公牛之力法术，但可影响多个目标。每个受术者的力量获得+4增强加值。",
    "material": "一摄公牛毛",
    "arcane": {"wizard": 6, "sorcerer": 6},
    "divine": {"cleric": 6},
    "classes": {"wizard": 6, "sorcerer": 6, "cleric": 6}
  },
  {
    "id": "cat_s_grace_mass",
    "nameEn": "Cat's Grace, Mass",
    "nameZh": "群体猫之优雅",
    "level": 6,
    "school": "transmutation",
    "components": "V, S, M",
    "castingTime": "单动作",
    "range": "中距",
    "target": "你所选的最多每等级1个生物，彼此相距不超过30尺",
    "duration": "1分钟/级",
    "savingThrow": "意志过则无效（无害）",
    "spellResist": "可（无害）",
    "desc": "如猫之优雅法术，但可影响多个目标。每个受术者的敏捷获得+4增强加值。",
    "material": "一摄猫毛",
    "arcane": {"wizard": 6, "sorcerer": 6},
    "divine": {"cleric": 6},
    "classes": {"wizard": 6, "sorcerer": 6, "cleric": 6}
  },
  {
    "id": "disintegrate",
    "nameEn": "Disintegrate",
    "nameZh": "解离术",
    "level": 6,
    "school": "transmutation",
    "components": "V, S, M",
    "castingTime": "单动作",
    "range": "中距",
    "target": "一个生物或物体",
    "duration": "即时",
    "savingThrow": "强韧过则部分生效",
    "spellResist": "可",
    "desc": "一道绿色射线射向目标。命中后造成2d6点伤害+每等级1点（最大+25）。如果目标的HP降至0或以下，目标被完全解离为尘埃（无法复活，除非通过神迹术或同等效果）。物体受到完全伤害（每10点击穿AC）。通过的强韧检定将伤害减半。",
    "material": "一撮仙人掌粉末",
    "arcane": {"wizard": 6, "sorcerer": 6},
    "divine": null,
    "classes": {"wizard": 6, "sorcerer": 6}
  },
  {
    "id": "eyebite",
    "nameEn": "Eyebite",
    "nameZh": "邪眼术",
    "level": 6,
    "school": "necromancy",
    "components": "V, S",
    "castingTime": "单动作",
    "range": "近距",
    "target": "一个生物",
    "duration": "即时",
    "savingThrow": "强韧过则无效",
    "spellResist": "可",
    "desc": "你对目标施展邪视。目标必须通过强韧检定，否则受到以下三种效果之一（你选择）：1) 虚弱：目标力量减半；2) 恐慌：目标恐慌逃窜1d4轮；3) 昏迷：目标昏迷1d10分钟。每轮你可以以自由动作对同一个或不同目标施展一次邪视（只要你维持专注）。",
    "arcane": {"wizard": 6, "sorcerer": 6},
    "divine": null,
    "classes": {"wizard": 6, "sorcerer": 6}
  },
  {
    "id": "find_the_path",
    "nameEn": "Find the Path",
    "nameZh": "寻路术",
    "level": 6,
    "school": "divination",
    "components": "V, S, M",
    "castingTime": "3轮",
    "range": "个人或近距（见描述）",
    "target": "你或一个人形生物",
    "duration": "1轮/级或直到到达目的地",
    "savingThrow": "无或意志过则无效（无害）（见描述）",
    "spellResist": "否或可（无害）",
    "desc": "受术者知道到达指定目的地的最直接和安全的路线。该法术可以穿透幻象和迷宫。如果受术者迷路，该法术会指出正确方向。",
    "material": "一套旅行者的衣服",
    "arcane": null,
    "divine": {"cleric": 6},
    "classes": {"cleric": 6}
  },
  {
    "id": "harm",
    "nameEn": "Harm",
    "nameZh": "伤害术",
    "level": 6,
    "school": "necromancy",
    "components": "V, S",
    "castingTime": "单动作",
    "range": "近距",
    "target": "一个生物",
    "duration": "即时",
    "savingThrow": "强韧过则部分生效",
    "spellResist": "可",
    "desc": "你对目标造成10点伤害/级（最大150点）。如果目标有1d4负向等级或更低，伤害加倍。通过的强韧检定将伤害减半。该法术不能杀死目标，只能将目标降至1HP。",
    "arcane": null,
    "divine": {"cleric": 6},
    "classes": {"cleric": 6}
  },
  {
    "id": "heroes_feast",
    "nameEn": "Heroes' Feast",
    "nameZh": "英雄宴",
    "level": 6,
    "school": "conjuration",
    "subSchool": "creation",
    "components": "V, S, DF",
    "castingTime": "10分钟",
    "range": "近距",
    "area": "一桌食物和饮料",
    "duration": "1小时",
    "savingThrow": "无",
    "spellResist": "否",
    "desc": "你创造一场豪华宴席，可供最多每等级1个受术者享用。享用宴席的受术者获得：+1士气加值攻击和豁免，时疫免疫，次级恐惧免疫，被称作英雄宴的状态（所有属性+2，持续1小时）。宴席食物可带走。",
    "arcane": null,
    "divine": {"cleric": 6, "druid": 6},
    "classes": {"cleric": 6, "druid": 6}
  },
  {
    "id": "insanity",
    "nameEn": "Insanity",
    "nameZh": "疯狂术",
    "level": 6,
    "school": "enchantment",
    "subSchool": "compulsion",
    "components": "V, S",
    "castingTime": "单动作",
    "range": "中距",
    "target": "一个生物",
    "duration": "永久",
    "savingThrow": "意志过则无效",
    "spellResist": "可",
    "desc": "目标陷入永久性疯狂。效果如同困惑法术，但永久持续。每24小时目标可以重新进行意志检定以摆脱效果（DC=法术DC）。神迹术、有限祈愿术或医疗术可以恢复正常。",
    "arcane": {"wizard": 6, "sorcerer": 6},
    "divine": null,
    "classes": {"wizard": 6, "sorcerer": 6}
  },
  {
    "id": "legend_lore",
    "nameEn": "Legend Lore",
    "nameZh": "传奇知识",
    "level": 6,
    "school": "divination",
    "components": "V, S, M, F",
    "castingTime": "见描述",
    "range": "个人",
    "target": "你",
    "duration": "见描述",
    "savingThrow": "无",
    "spellResist": "否",
    "desc": "你获得关于传奇人物、地点、物品或事件的知识。施展时间：1轮（已知信息）、1d4+1轮（部分已知）、1d10分钟（完全未知）。你知道关于主题的传说和线索。该法术不会揭示所有秘密，但提供有用的指引。",
    "material": "价值至少5000金币的魔法物品或文物",
    "focus": "价值至少1000金币的水晶球",
    "arcane": {"wizard": 6, "sorcerer": 6},
    "divine": null,
    "classes": {"wizard": 6, "sorcerer": 6, "bard": 6}
  },
  {
    "id": "mass_cure_moderate_wounds",
    "nameEn": "Mass Cure Moderate Wounds",
    "nameZh": "群体次级治疗重伤",
    "level": 6,
    "school": "conjuration",
    "subSchool": "healing",
    "components": "V, S",
    "castingTime": "单动作",
    "range": "近距",
    "target": "你所选的最多每等级1个接触的生物，彼此相距不超过30尺",
    "duration": "即时",
    "savingThrow": "无",
    "spellResist": "可（无害）",
    "desc": "如次级治疗重伤，但可影响多个目标。每个受术者恢复2d8+1/级HP（最大+10）。该法术可以治疗不死生物造成的伤害。",
    "arcane": null,
    "divine": {"cleric": 6, "druid": 6},
    "classes": {"cleric": 6, "druid": 6}
  },
  {
    "id": "mislead",
    "nameEn": "Mislead",
    "nameZh": "误导术",
    "level": 6,
    "school": "illusion",
    "subSchool": "figment",
    "components": "S, M",
    "castingTime": "单动作",
    "range": "个人",
    "target": "你",
    "duration": "1轮/级或直到被解除",
    "savingThrow": "无",
    "spellResist": "否",
    "desc": "你的身体变为隐形（如同隐形术）。同时创造一个你的影像（如同 mirror image 的法术影像）。影像可以行动和说话，你可以通过影像的感官感知。任何对影像的攻击或解咒攻击会优先影响影像。你可以通过自由动作将感官在身体和影像间切换。",
    "material": "一小片玻璃",
    "arcane": {"wizard": 6, "sorcerer": 6},
    "divine": null,
    "classes": {"wizard": 6, "sorcerer": 6}
  },
  {
    "id": "permanent_image",
    "nameEn": "Permanent Image",
    "nameZh": "永久影像",
    "level": 6,
    "school": "illusion",
    "subSchool": "figment",
    "components": "V, S, M, F",
    "castingTime": "单动作",
    "range": "长距",
    "effect": "一个你想象的影像，大小最多每等级一个20尺立方",
    "duration": "永久",
    "savingThrow": "意志过则发现（见描述）",
    "spellResist": "否",
    "desc": "如鬼影憧憧，但影像永久持续。影像可以移动和变化（如同 program image 法术）。你可以调整影像的声音、气味和温度。影像可以伪造一个生物或物体。任何与影像互动的人可以窥破幻象（意志检定）。",
    "material": "一小块玻璃和水晶",
    "focus": "一个价值至少1000金币的宝石",
    "arcane": {"wizard": 6, "sorcerer": 6},
    "divine": null,
    "classes": {"wizard": 6, "sorcerer": 6}
  },
  {
    "id": "planar_ally",
    "nameEn": "Planar Ally",
    "nameZh": "位面盟友",
    "level": 6,
    "school": "conjuration",
    "subSchool": "calling",
    "components": "V, S, M, DF",
    "castingTime": "10分钟",
    "range": "近距",
    "effect": "召唤一个外层位面的生物",
    "duration": "见描述",
    "savingThrow": "无",
    "spellResist": "否",
    "desc": "你召唤一个外层位面的生物来协助你。你必须提供价值至少1000金币的祭品（黄金、宝石或魔法物品）。召唤的生物服务时间：每1000金币价值1轮。你可以要求生物执行任务，但如果任务与本性的阵营严重冲突，生物可以拒绝。",
    "material": "价值至少1000金币的祭品",
    "arcane": null,
    "divine": {"cleric": 6},
    "classes": {"cleric": 6}
  },
  {
    "id": "shadow_walk",
    "nameEn": "Shadow Walk",
    "nameZh": "阴影行走",
    "level": 6,
    "school": "illusion",
    "subSchool": "shadow",
    "components": "V, S, M",
    "castingTime": "单动作",
    "range": "个人",
    "target": "你和其他自愿接触的生物（最多每等级1个）",
    "duration": "1轮/级",
    "savingThrow": "无",
    "spellResist": "否",
    "desc": "你在阴影位面中旅行。在阴影位面中，你的移动速度是正常地面的3倍（每轮最多720尺）。当你离开阴影位面时，你出现在你选择的地点（必须能看到或知道位置）。如果你在阴影位面中被攻击，你会被弹回主位面。",
    "material": "一撮阴影粉尘",
    "arcane": {"wizard": 6, "sorcerer": 6},
    "divine": null,
    "classes": {"wizard": 6, "sorcerer": 6}
  },
  {
    "id": "stone_to_flesh",
    "nameEn": "Stone to Flesh",
    "nameZh": "化石为肉",
    "level": 6,
    "school": "transmutation",
    "components": "V, S, M",
    "castingTime": "单动作",
    "range": "中距",
    "target": "一个宠物或生物",
    "duration": "即时",
    "savingThrow": "强韧过则无效",
    "spellResist": "可",
    "desc": "你将石化的生物恢复为血肉。如果目标是被血肉化石法术变成石头的，该法术可以恢复。如果目标是天然石头，该法术将其变为血肉（但需要每周施展一次以维持生命）。",
    "material": "一撮石灰粉",
    "arcane": {"wizard": 6, "sorcerer": 6},
    "divine": {"cleric": 6},
    "classes": {"wizard": 6, "sorcerer": 6, "cleric": 6}
  },
  {
    "id": "suggestion_mass",
    "nameEn": "Suggestion, Mass",
    "nameZh": "群体暗示术",
    "level": 6,
    "school": "enchantment",
    "subSchool": "compulsion",
    "components": "V, M",
    "castingTime": "单动作",
    "range": "近距",
    "target": "最多每等级1个生物，彼此相距不超过30尺",
    "duration": "1小时/级",
    "savingThrow": "意志过则无效",
    "spellResist": "可",
    "desc": "如暗示术，但可影响多个目标。你可以向所有目标提出相同的暗示，或分别提出不同的暗示。暗示必须听起来合理。",
    "material": "一条蛇舌或一块糖果",
    "arcane": {"wizard": 6, "sorcerer": 6},
    "divine": null,
    "classes": {"wizard": 6, "sorcerer": 6}
  },
  {
    "id": "summon_monster_6",
    "nameEn": "Summon Monster VI",
    "nameZh": "召唤怪物六",
    "level": 6,
    "school": "conjuration",
    "subSchool": "summoning",
    "components": "V, S, F",
    "castingTime": "单动作",
    "range": "近距",
    "effect": "召唤一个生物（列表见描述）",
    "duration": "1轮/级",
    "savingThrow": "无",
    "spellResist": "否",
    "desc": "召唤以下生物之一：1) 1个6级怪兽（如暗剑士、电浆虫）；2) 1d4+1个5级怪兽；3) 1d4+2个4级怪兽；4) 2d6个3级怪兽。召唤的生物在你的控制下。",
    "focus": "一个价值至少1000金币的宝石（某些生物需要）",
    "arcane": {"wizard": 6, "sorcerer": 6},
    "divine": {"cleric": 6},
    "classes": {"wizard": 6, "sorcerer": 6, "cleric": 6}
  },
  {
    "id": "true_seeing",
    "nameEn": "True Seeing",
    "nameZh": "真知术",
    "level": 6,
    "school": "divination",
    "components": "V, S, M, F",
    "castingTime": "单动作",
    "range": "个人接触",
    "target": "接触到的生物",
    "duration": "1轮/级",
    "savingThrow": "感知过则无效（无害）",
    "spellResist": "可（无害）",
    "desc": "受术者获得真知能力：看穿幻象、变形、投影、朦胧术、消失术、石肤术、影影法术等。受术者自动看穿所有5环或以下的幻术法术。该法术不能看穿神级幻象。",
    "material": "一片鹰眼宝石（价值5000金币）",
    "focus": "一个未切割的宝石（价值至少1000金币）",
    "arcane": {"wizard": 6, "sorcerer": 6},
    "divine": {"cleric": 5, "druid": 7},
    "classes": {"wizard": 6, "sorcerer": 6, "cleric": 5, "druid": 7}
  },
  {
    "id": "undeath_to_death",
    "nameEn": "Undeath to Death",
    "nameZh": "不死归亡术",
    "level": 6,
    "school": "necromancy",
    "components": "V, S, M",
    "castingTime": "单动作",
    "range": "中距",
    "area": "以你选择的点为中心，50尺半径扩散",
    "duration": "即时",
    "savingThrow": "强韧过则无效",
    "spellResist": "可",
    "desc": "你摧毁区域内所有HD12或以下的不死生物。HD13或以上的不死生物受到1d6点每等级伤害（最大20d6）。通过强韧检定的不死生物只受到一半伤害。该法术对尚死者（dhampir）无效。",
    "material": "一撮骨粉",
    "arcane": {"wizard": 6, "sorcerer": 6},
    "divine": {"cleric": 6},
    "classes": {"wizard": 6, "sorcerer": 6, "cleric": 6}
  },
  {
    "id": "veil",
    "nameEn": "Veil",
    "nameZh": "面纱术",
    "level": 6,
    "school": "illusion",
    "subSchool": "glamer",
    "components": "V, S, M",
    "castingTime": "单动作",
    "range": "近距",
    "target": "最多每等级1个生物或物体，彼此相距不超过30尺",
    "duration": "1轮/级",
    "savingThrow": "意志过则发现（见描述）",
    "spellResist": "否",
    "desc": "你改变目标的外观。你可以使目标看起来像任何其他生物或物体。改变包括视觉、触觉、嗅觉和声音。任何与目标互动的人可以进行意志检定以看穿面纱。你可以精确控制改变的程度。",
    "material": "一层薄纱",
    "arcane": {"wizard": 6, "sorcerer": 6},
    "divine": null,
    "classes": {"wizard": 6, "sorcerer": 6}
  }
"""

# 读取现有文件
with open('js/spells-data.js', 'r', encoding='utf-8') as f:
    content = f.read()

# 找到数组结束位置
end_marker = '];'
end_pos = content.rfind(end_marker)
if end_pos == -1:
    print("错误：找不到数组结束标记 '];'")
    exit(1)

# 在 '];' 前插入新法术
new_content = content[:end_pos] + new_spells_js + '\n' + content[end_pos:]

# 写回文件
with open('js/spells-data.js', 'w', encoding='utf-8') as f:
    f.write(new_content)

print("成功追加 22 个6环法术")
print("文件已更新：js/spells-data.js")
