import json, os

# 第三批：大量补充各环级核心PHB法术
new_spells = [

  # ===== 3环 =====
  {"id":"arcane_sight","nameEn":"Arcane Sight","nameZh":"奥术视觉",
   "level":3,"school":"预言系","subschool":"","descriptor":"",
   "components":"V,S,M","castingTime":"1标准动作","range":"个人",
   "target":"你自己","duration":"1分钟/环","savingThrow":"无","spellResist":"否",
   "desc":"获得60尺黑暗视觉和奥术视觉。奥术视觉让你看到所有魔法灵光（如同侦测魔法），并可以辨识法术（需要施法者等级+1d20对抗DC15+法术等级）。",
   "material":"两块云石（价值50gp）",
   "arcane":{"wizard":3,"sorcerer":3},"divine":None,
   "classes":{"wizard":3,"sorcerer":3}},

  {"id":"clairaudience_clairvoyance","nameEn":"Clairaudience/Clairvoyance","nameZh":"远聆/远视",
   "level":3,"school":"预言系","subschool":"","descriptor":"",
   "components":"V,S,M","castingTime":"1标准动作","range":"长距",
   "target":"一个感官灵光（60尺散布）","duration":"1分钟/环","savingThrow":"无","spellResist":"否",
   "desc":"创造一个隐形感官灵光（看到或听到）。你可以切换视觉/听觉。灵光有10HP，被攻击则消失。灵光可以被真知术看穿。",
   "material":"一撮云母",
   "arcane":{"wizard":3,"sorcerer":3},"divine":None,
   "classes":{"wizard":3,"sorcerer":3}},

  {"id":"displacement","nameEn":"Displacement","nameZh":"移位术",
   "level":3,"school":"幻术系","subschool":"式技幻术","descriptor":"",
   "components":"V,S,M","castingTime":"1标准动作","range":"触碰",
   "target":"触碰的生物","duration":"1轮/环","savingThrow":"意志过则无害","spellResist":"是（无害）",
   "desc":"目标看起来像是位移了（攻击失手几率50%）。真知术可以看穿移位术。",
   "material":"一小片水晶",
   "arcane":{"wizard":3,"sorcerer":3},"divine":None,
   "classes":{"wizard":3,"sorcerer":3}},

  {"id":"explosive_run","nameEn":"Explosive Runes","nameZh":"爆裂符文",
   "level":3,"school":"咒法学","subschool":"创造","descriptor":"[火][土]",
   "components":"V,S,M","castingTime":"1标准动作","range":"触碰",
   "target":"一个接触的表面","duration":"1天/环 或 直到触发","savingThrow":"见描述","spellResist":"否",
   "desc":"在表面绘制爆裂符文。触发时造成1d6点火焰和强酸伤害每施法者等级（最高10d6）。触发条件由你设定（如「陌生人触碰」）。反射过则减半。",
   "material":"火药、硫磺和强酸（价值50gp）",
   "arcane":{"wizard":3,"sorcerer":3},"divine":None,
   "classes":{"wizard":3,"sorcerer":3}},

  {"id":"gaseous_form","nameEn":"Gaseous Form","nameZh":"气化形体",
   "level":3,"school":"变化系","subschool":"","descriptor":"",
   "components":"S,M","castingTime":"1标准动作","range":"个人",
   "target":"你自己","duration":"1分钟/环","savingThrow":"无","spellResist":"否",
   "desc":"你变成气体状态。你可以飞行（速度10尺，不良机动性），穿过裂缝和缝隙。你在气化状态下无法攻击或施法（除了一直持续的法术）。风吹可以移动你。",
   "material":"一小块纱布和一根稻草",
   "arcane":{"wizard":3,"sorcerer":3},"divine":{"druid":3},
   "classes":{"wizard":3,"sorcerer":3,"druid":3}},

  {"id":"keen_edge","nameEn":"Keen Edge","nameZh":"锋锐之锋",
   "level":3,"school":"变化系","subschool":"","descriptor":"",
   "components":"V,S,M","castingTime":"1标准动作","range":"触碰",
   "target":"一把挥击或射弹武器","duration":"1分钟/环","savingThrow":"意志过则无害","spellResist":"是（无害）",
   "desc":"目标武器获得「锋锐」特性（重击威胁范围翻倍）。如果是魔法武器，锋锐效果与之叠加。",
   "material":"两块磨刀石",
   "arcane":None,"divine":{"cleric":3},
   "classes":{"cleric":3}},

  {"id":"magic_circle_against_alignment","nameEn":"Magic Circle against Alignment","nameZh":"魔法圆环（阵营防护）",
   "level":3,"school":"防护系","subschool":"","descriptor":"",
   "components":"V,S,M/DF","castingTime":"1标准动作","range":"触碰",
   "target":"触碰的生物 或 10尺散布","duration":"1分钟/环","savingThrow":"意志过则无害","spellResist":"否",
   "desc":"以目标为中心创造10尺半径的魔法屏障。屏障内生物：对抗指定阵营的生物获得+2偏斜AC和+2抗性豁免；指定阵营的生物无法进入屏障（需通过施法者等级检定）。有五个版本。",
   "material":"半磅薰香（价值20gp）",
   "arcane":{"wizard":3,"sorcerer":3},"divine":{"cleric":3,"paladin":3},
   "classes":{"wizard":3,"sorcerer":3,"cleric":3,"paladin":3}},

  {"id":"magic_weapon","nameEn":"Magic Weapon","nameZh":"魔法武器",
   "level":3,"school":"变化系","subschool":"","descriptor":"",
   "components":"V,S","castingTime":"1标准动作","range":"触碰",
   "target":"每施法者等级一把武器（最多+5把）","duration":"1分钟/环","savingThrow":"意志过则无害","spellResist":"是（无害）",
   "desc":"目标武器获得+1增强加值。每3环额外+1加值（6环+2，9环+3）。魔法武器可以伤害伤害减免需要魔法武器的生物。",
   "arcane":None,"divine":{"cleric":3,"paladin":3},
   "classes":{"cleric":3,"paladin":3}},

  {"id":"nondetection","nameEn":"Nondetection","nameZh":"反侦测",
   "level":3,"school":"防护系","subschool":"","descriptor":"",
   "components":"V,S,F","castingTime":"1标准动作","range":"触碰",
   "target":"触碰的生物或物品","duration":"1小时/环","savingThrow":"意志过则无害","spellResist":"是（无害）",
   "desc":"目标不会被侦测魔法、法术侦测、定位物体等法术侦测到。施法者等级用于对抗侦测法术的施法者等级检定。",
   "focus":"一根铅条",
   "arcane":{"wizard":3,"sorcerer":3},"divine":None,
   "classes":{"wizard":3,"sorcerer":3}},

  {"id":"obscure_magic","nameEn":"Obscure Magic","nameZh":"遮蔽魔法",
   "level":3,"school":"防护系","subschool":"","descriptor":"",
   "components":"V,S","castingTime":"1标准动作","range":"触碰",
   "target":"一个生物或物品","duration":"1分钟/环","savingThrow":"意志过则无害","spellResist":"是（无害）",
   "desc":"目标对抗侦测魔法的DC增加15。",
   "arcane":{"wizard":3,"sorcerer":3},"divine":None,
   "classes":{"wizard":3,"sorcerer":3}},

  {"id":"phantasmal_terror","nameEn":"Phantasmal Terror","nameZh":"幻象恐怖",
   "level":3,"school":"幻术系","subschool":"心灵幻象","descriptor":"[影响心灵]",
   "components":"V,S","castingTime":"1标准动作","range":"近距",
   "target":"一个生物","duration":"立即","savingThrow":"意志过则无效","spellResist":"是",
   "desc":"创造一个目标最恐惧的事物的幻象。目标需要通过意志检定否则受到2d6点感知伤害，并陷入恐慌1d4轮。如果目标通过检定，则毫发无损。",
   "arcane":{"wizard":3,"sorcerer":3},"divine":None,
   "classes":{"wizard":3,"sorcerer":3}},

  {"id":"sacred_nondetection","nameEn":"Nondetection (Divine)","nameZh":"神圣反侦测",
   "level":3,"school":"防护系","subschool":"","descriptor":"",
   "components":"V,S,DF","castingTime":"1标准动作","range":"触碰",
   "target":"触碰的生物或物品","duration":"1小时/环","savingThrow":"意志过则无害","spellResist":"是（无害）",
   "desc":"同奥术版反侦测，但为神术版。",
   "arcane":None,"divine":{"cleric":3},
   "classes":{"cleric":3}},

  {"id":"searing_light","nameEn":"Searing Light","nameZh":"灼热之光",
   "level":3,"school":"塑能系","subschool":"","descriptor":"[光]",
   "components":"V,S","castingTime":"1标准动作","range":"中距",
   "target":"一道射线","duration":"立即","savingThrow":"无","spellResist":"是",
   "desc":"你需要进行远程接触攻击。命中则造成1d6点伤害每施法者等级（最高15d6）。对不死生物和阴影生物造成双倍伤害。善良牧师对邪恶不死生物造成双倍伤害。",
   "arcane":None,"divine":{"cleric":3},
   "classes":{"cleric":3}},

  {"id":"seonalight","nameEn":"Seonalight","nameZh":"间歇光线",
   "level":3,"school":"咒法学","subschool":"创造","descriptor":"[光]",
   "components":"V,S,M","castingTime":"1标准动作","range":"0尺",
   "target":"扇状区域（锥底60尺，锥高60尺）","duration":"1轮/等级","savingThrow":"反射过则减半","spellResist":"否",
   "desc":"你喷射出一道间歇光线。锥内所有生物受到1d8点伤害每施法者等级（最高10d8）。反射过则减半。可以在法术持续期间以一个标准动作再喷射一次。",
   "material":"一块向日葵花瓣",
   "arcane":None,"divine":{"druid":3},
   "classes":{"druid":3}},

  {"id":"snare","nameEn":"Snare","nameZh":"陷阱术",
   "level":3,"school":"咒法学","subschool":"创造","descriptor":"",
   "components":"V,S,M","castingTime":"3轮","range":"触碰",
   "target":"地面上的一个位置","duration":"1天/环 或 直到触发","savingThrow":"无","spellResist":"否",
   "desc":"制造一个魔法绳索陷阱。触发时，目标的腿被绳索捆住（需要通过脱逃检定DC20或力量检定DC25才能挣脱）。触发者如果成功通过反射检定DC20则不受陷阱影响。",
   "material":"一根绳索（价值30gp）",
   "arcane":None,"divine":{"druid":3},
   "classes":{"druid":3}},

  {"id":"speak_with_plants","nameEn":"Speak with Plants","nameZh":"植物交谈",
   "level":3,"school":"预言系","subschool":"","descriptor":"",
   "components":"V,S,DF","castingTime":"1标准动作","range":"个人",
   "target":"你自己","duration":"1分钟/环","savingThrow":"无","spellResist":"否",
   "desc":"你可以和植物交谈（植物有智商0，但可以提供简单信息）。植物可以告诉你最近（1天/环）看到或听到的事情。",
   "arcane":None,"divine":{"druid":3},
   "classes":{"druid":3}},

  {"id":"tongues","nameEn":"Tongues","nameZh":"巧言术",
   "level":3,"school":"预言系","subschool":"","descriptor":"",
   "components":"V,M","castingTime":"1标准动作","range":"触碰",
   "target":"触碰的生物","duration":"1分钟/环","savingThrow":"意志过则无害","spellResist":"是（无害）",
   "desc":"目标可以理解任何口头语言（不需要理解语言法术），并以任何语言回答（听者可以理解，不需要懂该语言）。巧言术影响读写和听说。",
   "material":"一小撮蜂蜜和一滴橄榄油",
   "arcane":{"wizard":3,"sorcerer":3,"bard":3},"divine":{"cleric":3},
   "classes":{"wizard":3,"sorcerer":3,"bard":3,"cleric":3}},

  {"id":"water_walk","nameEn":"Water Walk","nameZh":"水上行走",
   "level":3,"school":"变化系","subschool":"","descriptor":"",
   "components":"V,S,DF","castingTime":"1标准动作","range":"触碰",
   "target":"你以及最多每施法者等级一个盟友","duration":"1分钟/环","savingThrow":"意志过则无害","spellResist":"是（无害）",
   "desc":"受术者可以在水面、酸液、熔岩上行走（如同在平地一样）。如果法术终止时受术者在水面上，则沉入水中（但不会受到伤害）。",
   "arcane":None,"divine":{"cleric":3,"druid":3},
   "classes":{"cleric":3,"druid":3}},

  {"id":"wind_wall","nameEn":"Wind Wall","nameZh":"风墙术",
   "level":3,"school":"塑能系","subschool":"","descriptor":"",
   "components":"V,S,M","castingTime":"1标准动作","range":"近距",
   "target":"一道风墙（最长10尺+10尺/环，高10尺）","duration":"1分钟/环","savingThrow":"无","spellResist":"否",
   "desc":"你创造一道强劲的风墙。风墙可以偏转远程攻击（弓箭、弩箭等）和气体/呼吸法术（如云击、毒云）。风吹向你的选择方向（可以每轮以一个标准动作改变方向）。",
   "material":"一把扇子或风车玩具",
   "arcane":{"wizard":3,"sorcerer":3,"druid":3},"divine":None,
   "classes":{"wizard":3,"sorcerer":3,"druid":3}},

  # ===== 4环补充 =====
  {"id":"animate_dead","nameEn":"Animate Dead","nameZh":"操控死尸",
   "level":4,"school":"死灵系","subschool":"","descriptor":"[邪恶]",
   "components":"V,S,M","castingTime":"1轮","range":"近距",
   "target":"最多2HD/环的不死生物","duration":"瞬间 或 1分钟/环（见描述）","savingThrow":"无","spellResist":"否",
   "desc":"你使尸体或骸骨复活为僵尸或骷髅为你服务。你可以控制的不死生物HD总值最多2HD/环。牧师可以控制任意数量的不死生物（无HD上限）。通过魅惑不死生物法术可以增强控制。⚠️ 邪恶法术。",
   "material":"一撮骨灰（价值25gp）",
   "arcane":{"wizard":4,"sorcerer":4},"divine":{"cleric":4},
   "classes":{"wizard":4,"sorcerer":4,"cleric":4}},

  {"id":"confusion","nameEn":"Confusion","nameZh":"困惑术",
   "level":4,"school":"惑控系","subschool":"强迫","descriptor":"[影响心灵]",
   "components":"V,S,M","castingTime":"1标准动作","range":"中距",
   "target":"所有在范围内的生物（最多2HD/环）","duration":"1轮/环","savingThrow":"意志过则无效","spellResist":"是",
   "desc":"范围内所有生物陷入困惑（每轮随机行动：01-10=攻击最近生物；11-20=失手；21-50=全轮防御；51-70=正常行动；71-100=错误行动）。通过意志检定则不受影响。",
   "material":"三块胡桃壳",
   "arcane":{"wizard":4,"sorcerer":4},"divine":None,
   "classes":{"wizard":4,"sorcerer":4}},

  {"id":"contagion","nameEn":"Contagion","nameZh":"传染术",
   "level":4,"school":"死灵系","subschool":"","descriptor":"[疾病][影响心灵]",
   "components":"V,S","castingTime":"1标准动作","range":"近距",
   "target":"一个生物","duration":"立即","savingThrow":"强韧过则无效","spellResist":"是",
   "desc":"你需要进行远程接触攻击。命中则目标感染一种疾病（你选择）：腐热症、失水症、倦怠症、震颠症或红热症。疾病通常在1d4天后发作。",
   "arcane":{"wizard":4,"sorcerer":4},"divine":{"cleric":4},
   "classes":{"wizard":4,"sorcerer":4,"cleric":4}},

  {"id":"crushing_despair","nameEn":"Crushing Despair","nameZh":"粉碎绝望",
   "level":4,"school":"惑控系","subschool":"强迫","descriptor":"[影响心灵][语言依赖][听觉]",
   "components":"V,S","castingTime":"1标准动作","range":"近距",
   "target":"最多一个生物/环","duration":"1轮/环","savingThrow":"意志过则无效","spellResist":"是",
   "desc":"你需要成功吹奏音管（需通过演奏检定）。受术者陷入绝望，攻击检定-2、伤害-2、所有技能-2。通过意志检定则不受影响。",
   "arcane":{"bard":2},"divine":None,
   "classes":{"bard":2}},

  {"id":"divination_arcane","nameEn":"Divination (Arcane)","nameZh":"占卜术（奥术）",
   "level":4,"school":"预言系","subschool":"","descriptor":"",
   "components":"V,S,M","castingTime":"10分钟","range":"个人",
   "target":"你自己","duration":"立即","savingThrow":"无","spellResist":"否",
   "desc":"你询问一个关于未来事件的问题（只能回答「是」「否」或「不确定」）。DM根据问题给出一个诚实的答案。每天只能用一次。",
   "material":"价值25gp的贡品（如香、酒、罕见药材）",
   "arcane":{"wizard":4},"divine":None,
   "classes":{"wizard":4}},

  {"id":"enervation","nameEn":"Enervation","nameZh":"负能量射线",
   "level":4,"school":"死灵系","subschool":"","descriptor":"[负能量]",
   "components":"V,S","castingTime":"1标准动作","range":"近距",
   "target":"一道射线","duration":"1小时/环","savingThrow":"强韧过则无效","spellResist":"是",
   "desc":"你需要进行远程接触攻击。命中则目标受到1d4个负等级。目标每轮结束时可以通过强韧检定以移除一个负等级。如果法术持续，负等级成为永久。",
   "arcane":{"wizard":4,"sorcerer":4},"divine":None,
   "classes":{"wizard":4,"sorcerer":4}},

  {"id":"fear","nameEn":"Fear","nameZh":"恐惧术",
   "level":4,"school":"惑控系","subschool":"强迫","descriptor":"[恐惧][影响心灵]",
   "components":"V,S,M","castingTime":"1标准动作","range":"近距",
   "target":"所有在范围内的生物","duration":"1轮/环","savingThrow":"意志过则无效","spellResist":"是",
   "desc":"范围内所有生物陷入恐慌（通过意志检定则不受影响）。恐慌的生物会全速逃离你，持续1轮/环。",
   "material":"一块白羽毛（在一小块铅中）",
   "arcane":{"wizard":4,"sorcerer":4},"divine":None,
   "classes":{"wizard":4,"sorcerer":4}},

  {"id":"identify_monster","nameEn":"Identify Monster","nameZh":"辨识怪物",
   "level":4,"school":"预言系","subschool":"","descriptor":"",
   "components":"V,S","castingTime":"1轮","range":"中距",
   "target":"一个生物","duration":"立即","savingThrow":"无","spellResist":"否",
   "desc":"你辨识一个生物：知道其属性、技能、特殊能力和弱点。如果你在之后再次遇到同一生物，你可以重新辨识（不需要再施法）。",
   "arcane":{"wizard":4,"sorcerer":4},"divine":None,
   "classes":{"wizard":4,"sorcerer":4}},

  {"id":"lesser_planar_binding","nameEn":"Lesser Planar Binding","nameZh":"次级异界束缚",
   "level":4,"school":"咒法学","subschool":"召唤","descriptor":"",
   "components":"V,S,M","castingTime":"1轮","range":"近距",
   "target":"一个异界生物","duration":"见描述","savingThrow":"无","spellResist":"否",
   "desc":"你召唤一个异界生物并试图与它谈判（需要魅力检定对抗DC=10+HD+异界生物魅力调整值）。成功则生物为你服务（最多1天/环）。失败则生物返回原位。消耗1000XP可以强制生物服务。",
   "material":"价值500gp的贡品（依异界生物喜好）",
   "arcane":{"wizard":4,"sorcerer":4},"divine":None,
   "classes":{"wizard":4,"sorcerer":4}},
]

fpath = r"C:\Users\wyb\WorkBuddy\2026-06-20-01-52-30\dnd35-wiki-pro\js\spells-data.js"
with open(fpath, 'r', encoding='utf-8') as f:
    content = f.read()

marker = "\n];"
if marker in content:
    insert_pos = content.index(marker)
    entries = ',\n'.join(json.dumps(sp, ensure_ascii=False, indent=2) for sp in new_spells)
    new_content = content[:insert_pos] + ',\n  ' + entries + content[insert_pos:]
    with open(fpath, 'w', encoding='utf-8') as f:
        f.write(new_content)
    print(f"成功追加 {len(new_spells)} 个法术")
    print(f"新文件行数：{len(new_content.splitlines())}")
else:
    print("未找到 ]; 标记")
