import json, os

# 第4批：大量补充4~9环核心PHB法术
new_spells = [

  # ===== 4环 续 =====
  {"id":"iversal_poison","nameEn":"Universal Poison","nameZh":"全能毒素",
   "level":4,"school":"死灵系","subschool":"","descriptor":"[毒][影响心灵]",
   "components":"V,S", "castingTime":"1标准动作","range":"触碰",
   "target":"一个生物","duration":"立即","savingThrow":"强韧过则无效","spellResist":"是",
   "desc":"需要近战接触攻击。命中则目标感染你选择的疾病或毒素。通过强韧检定则不受影响。",
   "arcane":{"wizard":4,"sorcerer":4},"divine":None,
   "classes":{"wizard":4,"sorcerer":4}},

  {"id":"wall_of_fire_4","nameEn":"Wall of Fire","nameZh":"火焰墙",
   "level":4,"school":"塑能系","subschool":"","descriptor":"[火]",
   "components":"V,S,M", "castingTime":"1标准动作","range":"中距",
   "target":"一道火焰墙（最长20尺+10尺/环，高20尺）","duration":"专注","savingThrow":"无或反射过则减半","spellResist":"是",
   "desc":"你创造一道垂直或环形的火焰墙。任何生物穿过墙受到2d6点火焰伤害每施法者等级（最高20d6）。墙的一侧（你选择）喷射出火焰。",
   "material":"一小块磷光或硫磺",
   "arcane":{"wizard":4,"sorcerer":4,"druid":4},"divine":None,
   "classes":{"wizard":4,"sorcerer":4,"druid":4}},

  # ===== 5环 =====
  {"id":"baleful_polymorph_5","nameEn":"Baleful Polymorph","nameZh":"恶毒变化术",
   "level":5,"school":"变化系","subschool":"","descriptor":"",
   "components":"V,S", "castingTime":"1标准动作","range":"近距",
   "target":"一个生物","duration":"永久","savingThrow":"强韧过则无效","spellResist":"是",
   "desc":"将目标变化为一头无害的小动物（如老鼠、青蛙）。目标失去所有特殊能力、超自然能力和法术能力，获得新形态的物理属性。通过强韧检定则不受影响。",
   "arcane":{"wizard":5,"sorcerer":5},"divine":None,
   "classes":{"wizard":5,"sorcerer":5}},

  {"id":"break_enchantment","nameEn":"Break Enchantment","nameZh":"解除奇术",
   "level":5,"school":"惑控系","subschool":"","descriptor":"[影响心灵]",
   "components":"V,S", "castingTime":"1分钟","range":"近距",
   "target":"一个生物","duration":"立即","savingThrow":"见描述","spellResist":"是",
   "desc":"尝试解除目标身上的所有惑控系法术。你需要对每个法术进行一次施法者等级检定（d20+施法者等级对抗DC11+法术等级）。",
   "arcane":{"wizard":5,"sorcerer":5,"bard":5},"divine":None,
   "classes":{"wizard":5,"sorcerer":5,"bard":5}},

  {"id":"contact_outer_plane","nameEn":"Contact Outer Plane","nameZh":"接触外位面",
   "level":5,"school":"预言系","subschool":"","descriptor":"",
   "components":"V,S", "castingTime":"10分钟","range":"个人",
   "target":"你自己","duration":"立即","savingThrow":"无","spellResist":"否",
   "desc":"你接触一个外位面存在并询问问题。你可以问最多一个问题每2施法者等级。存在会诚实回答（但可能简短或含糊）。有风险：可能陷入恍惚（1d6轮）或获得疯狂（1d6点临时属性伤害）。",
   "arcane":{"wizard":5,"sorcerer":5},"divine":None,
   "classes":{"wizard":5,"sorcerer":5}},

  {"id":"dispel_law","nameEn":"Dispel Law","nameZh":"解除守序",
   "level":5,"school":"防护系","subschool":"","descriptor":"[混乱]",
   "components":"V,S,DF", "castingTime":"1标准动作","range":"近距",
   "target":"一个生物","duration":"立即","savingThrow":"无","spellResist":"是（无害）",
   "desc":"如同解除魔法，但专门用于解除守序生物施放的法术。对守序生物造成1d6点伤害每施法者等级（最高10d6）。",
   "arcane":None,"divine":{"cleric":5},
   "classes":{"cleric":5}},

  {"id":"false_vision","nameEn":"False Vision","nameZh":"错误视觉",
   "level":5,"school":"幻术系","subschool":"式技幻术","descriptor":"",
   "components":"V,S,M", "castingTime":"1标准动作","range":"触碰",
   "target":"一个地点或生物","duration":"1小时/环","savingThrow":"无","spellResist":"否",
   "desc":"在目标区域创造视觉假象。任何使用预言系法术侦测目标区域的人会看到假象（通过意志检定则看穿）。",
   "material":"价值100gp的玉石粉末",
   "arcane":{"wizard":5,"sorcerer":5},"divine":None,
   "classes":{"wizard":5,"sorcerer":5}},

  {"id":"feeblemind","nameEn":"Feeblemind","nameZh":"削弱心智",
   "level":5,"school":"惑控系","subschool":"强迫","descriptor":"[影响心灵]",
   "components":"V,S", "castingTime":"1标准动作","range":"中距",
   "target":"一个生物","duration":"见描述","savingThrow":"意志过则无效","spellResist":"是",
   "desc":"目标 intellect 降到1（如同失智）。受影响生物无法进行任何需要智力的行动。通过意志检定则不受影响。可以通过移除诅咒或有限祈愿解除。",
   "arcane":{"wizard":5,"sorcerer":5},"divine":None,
   "classes":{"wizard":5,"sorcerer":5}},

  {"id":"hold_monster_5","nameEn":"Hold Monster","nameZh":"定身怪物",
   "level":5,"school":"惑控系","subschool":"强迫","descriptor":"[影响心灵]",
   "components":"V,S,F", "castingTime":"1标准动作","range":"中距",
   "target":"一个生物","duration":"1轮/环","savingThrow":"意志过则无效","spellResist":"是",
   "desc":"如同定身人类，但可以影响任何生物。目标被定身（无法行动）。",
   "focus":"一个小的人偶，用象牙制成（价值50gp）",
   "arcane":{"wizard":5,"sorcerer":5,"bard":5},"divine":{"cleric":5},
   "classes":{"wizard":5,"sorcerer":5,"bard":5,"cleric":5}},

  {"id":"justice_eye","nameEn":"Eye of Justice","nameZh":"正义之眼",
   "level":5,"school":"预言系","subschool":"","descriptor":"",
   "components":"V,S,DF", "castingTime":"1标准动作","range":"触碰",
   "target":"触碰的生物","duration":"1分钟/环","savingThrow":"意志过则无害","spellResist":"是（无害）",
   "desc":"受术者获得60尺黑暗视觉、看穿幻术和隐形、对邪恶生物发现弱点（+2攻击和伤害）。",
   "arcane":None,"divine":{"cleric":5,"paladin":4},
   "classes":{"cleric":5,"paladin":4}},

  {"id":"mind_fog","nameEn":"Mind Fog","nameZh":"心灵迷雾",
   "level":5,"school":"幻术系","subschool":"五官幻术","descriptor":"[影响心灵]",
   "components":"V,S", "castingTime":"1标准动作","range":"中距",
   "target":"半径20尺散布","duration":"1轮/环","savingThrow":"无","spellResist":"否",
   "desc":"制造一片浓密的心灵迷雾。雾内所有生物受到-10警觉检定，潜行检定DC+10。法术侦测也受阻碍。",
   "arcane":{"wizard":5,"sorcerer":5},"divine":None,
   "classes":{"wizard":5,"sorcerer":5}},

  {"id":"overland_flight","nameEn":"Overland Flight","nameZh":"越野飞行",
   "level":5,"school":"变化系","subschool":"","descriptor":"",
   "components":"V,S,F", "castingTime":"1标准动作","range":"触碰",
   "target":"触碰的生物","duration":"1小时/环","savingThrow":"意志过则无害","spellResist":"是（无害）",
   "desc":"受术者获得飞行速度80尺（不良机动性）。比飞行术更快，适合长距离旅行。",
   "focus":"一根轻羽毛或一小片羽毛",
   "arcane":{"wizard":5,"sorcerer":5},"divine":None,
   "classes":{"wizard":5,"sorcerer":5}},

  {"id":"prying_eyes","nameEn":"Prying Eyes","nameZh":"窥视之眼",
   "level":5,"school":"咒法学","subschool":"创造","descriptor":"",
   "components":"V,S,M", "castingTime":"1轮","range":"近距",
   "target":"至多一打窥视之眼","duration":"1小时/环","savingThrow":"无","spellResist":"否",
   "desc":"你创造至多12只魔法眼球。每只眼球有30尺黑暗视觉，可以看穿隐形。你可以通过眼球看（使用你的正常视觉）。眼球有10HP，AC 18。",
   "material":"一撮猫毛",
   "arcane":{"wizard":5,"sorcerer":5},"divine":None,
   "classes":{"wizard":5,"sorcerer":5}},

  {"id":"searing_light_5","nameEn":"Searing Light","nameZh":"灼热之光",
   "level":5,"school":"塑能系","subschool":"","descriptor":"[光]",
   "components":"V,S", "castingTime":"1标准动作","range":"中距",
   "target":"一道射线","duration":"立即","savingThrow":"无","spellResist":"是",
   "desc":"你需要进行远程接触攻击。命中则造成1d8点伤害每施法者等级（最高15d8）。对不死生物和阴影生物造成最大伤害。",
   "arcane":None,"divine":{"cleric":5},
   "classes":{"cleric":5}},

  {"id":"summon_monster_5_full","nameEn":"Summon Monster V","nameZh":"召唤怪物Ⅴ",
   "level":5,"school":"咒法学","subschool":"召唤","descriptor":"",
   "components":"V,S,F", "castingTime":"1轮","range":"近距",
   "target":"见描述","duration":"1轮/环","savingThrow":"无","spellResist":"否",
   "desc":"召唤一个CR5或更低的生物为你作战。常见选择：1个石元素、1个大型土元素、1个狂战幽灵等。",
   "focus":"一个嵌有宝石的小哨子（价值100gp）",
   "arcane":{"wizard":5,"sorcerer":5,"bard":5},"divine":{"cleric":5},
   "classes":{"wizard":5,"sorcerer":5,"bard":5,"cleric":5}},

  {"id":"transmute_mud_rock","nameEn":"Transmute Mud to Rock / Rock to Mud","nameZh":"泥岩互变",
   "level":5,"school":"变化系","subschool":"","descriptor":"",
   "components":"V,S,M,DF", "castingTime":"1标准动作","range":"中距",
   "target":"两个10尺散布（任选）","duration":"永久","savingThrow":"无","spellResist":"否",
   "desc":"将两个区域互换：泥→岩（固化）或岩→泥（软化）。岩变泥可以让建筑物倒塌、地面变成困难地形。泥变岩可以固化泥沼。",
   "material":"泥土和一块花岗岩",
   "arcane":{"wizard":5,"sorcerer":5},"divine":{"druid":5},
   "classes":{"wizard":5,"sorcerer":5,"druid":5}},

  {"id":"wall_of_stone_5","nameEn":"Wall of Stone","nameZh":"石墙术",
   "level":5,"school":"塑能系","subschool":"","descriptor":"",
   "components":"V,S,M,DF", "castingTime":"1标准动作","range":"中距",
   "target":"一道石墙（最厚10尺+5尺/环，面积100平方尺/环）","duration":"永久","savingThrow":"无","spellResist":"否",
   "desc":"你创造一道石墙。墙可以是垂直、水平或任何形状。墙的厚度由你决定。墙的硬度14，HP厚度每寸10点。",
   "material":"一小块花岗岩",
   "arcane":{"wizard":5,"sorcerer":5},"divine":{"cleric":5,"druid":5},
   "classes":{"wizard":5,"sorcerer":5,"cleric":5,"druid":5}},

  # ===== 6环 =====
  {"id":"antimagic_field","nameEn":"Antimagic Field","nameZh":"反魔法场",
   "level":6,"school":"防护系","subschool":"","descriptor":"",
   "components":"V,S", "castingTime":"1标准动作","range":"个人",
   "target":"以你为中心，半径10尺散布","duration":"1轮/环","savingThrow":"见描述","spellResist":"见描述",
   "desc":"创造一片反魔法区域。区域内所有魔法效果和法术无效（包括你自己的法术）。魔法物品和法术抗力在区域内无效。你可以解除反魔法场（以一个标准动作）。",
   "arcane":{"wizard":6,"sorcerer":6},"divine":None,
   "classes":{"wizard":6,"sorcerer":6}},

  {"id":"contingency","nameEn":"Contingency","nameZh":" Magic 法术 contingeny","desc":"你绑定一个法术，当特定条件满足时自动触发。被绑定的法术必须是个人范围或触碰范围。触发条件由你设定（如「我受到攻击时」「我生命值降到0时」）。",
   "level":6,"school":"变化系","subschool":"","descriptor":"",
   "components":"V,S", "castingTime":"1轮","range":"个人",
   "target":"你自己","duration":"1天/环 或 直到触发","savingThrow":"见描述","spellResist":"是（无害）",
   "arcane":{"wizard":6,"sorcerer":6},"divine":None,
   "classes":{"wizard":6,"sorcerer":6}},

  {"id":"circle_of_death","nameEn":"Circle of Death","nameZh":"死亡之环",
   "level":6,"school":"死灵系","subschool":"","descriptor":"[死亡]",
   "components":"V,S,M", "castingTime":"1标准动作","range":"0尺",
   "target":"半径40尺散布","duration":"立即","savingThrow":"强韧过则无效","spellResist":"是",
   "desc":"你以自己为中心释放负能量波。范围内所有生物受到1d4点负等级每施法者等级（最高10d4）。通过强韧检定则不受影响。",
   "material":"价值500gp的黑玛瑙粉末",
   "arcane":{"wizard":6,"sorcerer":6},"divine":None,
   "classes":{"wizard":6,"sorcerer":6}},

  {"id":"create_undead","nameEn":"Create Undead","nameZh":"创造亡灵",
   "level":6,"school":"死灵系","subschool":"","descriptor":"[邪恶]",
   "components":"V,S,M", "castingTime":"1轮","range":"近距",
   "target":"最多2HD/环的尸体","duration":"立即","savingThrow":"无","spellResist":"否",
   "desc":"你将尸体转化为亡灵生物（僵尸、骷髅、食尸鬼、幽影等）。你可以控制的不死生物HD总值最多2HD/环。⚠️ 邪恶法术。",
   "material":"价值150gp的黑玛瑙（消耗）",
   "arcane":{"wizard":6,"sorcerer":6},"divine":None,
   "classes":{"wizard":6,"sorcerer":6}},

  {"id":"eyebite","nameEn":"Eyebite","nameZh":"目咬术",
   "level":6,"school":"死灵系","subschool":"","descriptor":"[影响心灵]",
   "components":"V,S", "castingTime":"1标准动作","range":"近距",
   "target":"一个生物","duration":"见描述","savingThrow":"意志过则无效","spellResist":"是",
   "desc":"你对目标造成目盲（通过意志检定则不受影响）。目盲的生物受到-4攻击检定和技能检定。如果目标通过检定，则不受任何效果。",
   "arcane":{"wizard":6,"sorcerer":6},"divine":None,
   "classes":{"wizard":6,"sorcerer":6}},

  {"id":"geas_quest","nameEn":"Geas/Quest","nameZh":"重责/ quest",
   "level":6,"school":"惑控系","subschool":"强迫","descriptor":"[语言依赖][影响心灵]",
   "components":"V,S", "castingTime":"1轮","range":"近距",
   "target":"一个生物","duration":"见描述","savingThrow":"意志过则无效","spellResist":"是",
   "desc":"你命令目标完成一个任务（不能明显有害）。目标必须通过意志检定否则被强迫完成任务。如果任务明显有害，目标获得新的豁免检定。目标的HD决定法术持续时间（HD12以下永久，HD12+ 1天/环）。",
   "arcane":{"wizard":6,"sorcerer":6},"divine":{"cleric":6},
   "classes":{"wizard":6,"sorcerer":6,"cleric":6}},

  {"id":"globe_of_invulnerability","nameEn":"Globe of Invulnerability","nameZh":"无敌法球",
   "level":6,"school":"防护系","subschool":"","descriptor":"",
   "components":"V,S,M", "castingTime":"1标准动作","range":"个人",
   "target":"以你为中心，半径10尺散布","duration":"1轮/环","savingThrow":"无","spellResist":"见描述",
   "desc":"创造一片魔法屏障。所有法术等级低于法球施展者等级的法术无法穿透屏障（无论奥术或神术）。更高等级的法术可以穿透。",
   "material":"一颗价值1000gp的珍珠（消耗）",
   "arcane":{"wizard":6,"sorcerer":6},"divine":None,
   "classes":{"wizard":6,"sorcerer":6}},

  {"id":"guards_and_wards","nameEn":"Guards and Wards","nameZh":"守卫与防护",
   "level":6,"school":"防护系","subschool":"","descriptor":"",
   "components":"V,S,M", "castingTime":"1轮","range":"个人",
   "target":"以你为中心，半径200尺散布","duration":"2小时/环","savingThrow":"见描述","spellResist":"见描述",
   "desc":"创造多重防护效果：1=酯术（防止侦测）；2=误途（误导方向）；3=幽灵守卫（吓退入侵者）；4=放逐仆从（驱散召唤生物）。",
   "material":"价值100gp的稀有药材",
   "arcane":{"wizard":6,"sorcerer":6},"divine":None,
   "classes":{"wizard":6,"sorcerer":6}},

  {"id":"legend_lore","nameEn":"Legend Lore","nameZh":"传奇知识",
   "level":6,"school":"预言系","subschool":"","descriptor":"",
   "components":"V,S", "castingTime":"见描述","range":"个人",
   "target":"你自己","duration":"立即","savingThrow":"无","spellResist":"否",
   "desc":"你获取关于传奇人物、地点或物品的知识。施展时间取决于你已知信息（已知名字→1轮；已知描述→10分钟；一无所知→1天）。DM告知你相关知识。",
   "arcane":{"wizard":6,"sorcerer":6},"divine":None,
   "classes":{"wizard":6,"sorcerer":6}},

  {"id":"mislead","nameEn":"Mislead","nameZh":"误导术",
   "level":6,"school":"幻术系","subschool":"式技幻术","descriptor":"",
   "components":"S", "castingTime":"1标准动作","range":"个人",
   "target":"你自己","duration":"1轮/环","savingThrow":"无","spellResist":"否",
   "desc":"你创造一个你的幻象分身（虚假图像），同时你的身体变为隐形。分身可以移动、说话、施法（假动作）。你可以通过分身看到和听到。任何生物攻击分身会使其消失（你显形）。",
   "arcane":{"wizard":6,"sorcerer":6},"divine":None,
   "classes":{"wizard":6,"sorcerer":6}},

  {"id":"move_earth","nameEn":"Move Earth","nameZh":"移土术",
   "level":6,"school":"变化系","subschool":"","descriptor":"",
   "components":"V,S,M,DF", "castingTime":"10分钟","range":"长距",
   "target":"一片区域（最大10尺+10尺/环边长）","duration":"立即","savingThrow":"无","spellResist":"否",
   "desc":"你缓慢移动大量泥土和石头（每小时10立方尺）。可以造山、挖沟、改道河流等。法术需要专注。",
   "material":"价值10gp的稀有土壤",
   "arcane":{"wizard":6,"sorcerer":6},"divine":{"druid":6},
   "classes":{"wizard":6,"sorcerer":6,"druid":6}},

  {"id":"summon_monster_6_full","nameEn":"Summon Monster VI","nameZh":"召唤怪物Ⅵ",
   "level":6,"school":"咒法学","subschool":"召唤","descriptor":"",
   "components":"V,S,F", "castingTime":"1轮","range":"近距",
   "target":"见描述","duration":"1轮/环","savingThrow":"无","spellResist":"否",
   "desc":"召唤一个CR6或更低的生物为你作战。常见选择：1个大型火元素、1个石巨像、1个狂战幽灵等。",
   "focus":"一个嵌有宝石的小哨子（价值100gp）",
   "arcane":{"wizard":6,"sorcerer":6,"bard":6},"divine":{"cleric":6},
   "classes":{"wizard":6,"sorcerer":6,"bard":6,"cleric":6}},

  {"id":"undetectable_alignment","nameEn":"Undetectable Alignment","nameZh":"不可侦测阵营",
   "level":6,"school":"防护系","subschool":"","descriptor":"",
   "components":"V,S,DF", "castingTime":"1标准动作","range":"触碰",
   "target":"触碰的生物","duration":"24小时","savingThrow":"意志过则无害","spellResist":"是（无害）",
   "desc":"目标无法被任何法术或能力侦测到阵营（包括侦测邪恶、知道阵营等）。",
   "arcane":{"wizard":6,"sorcerer":6},"divine":{"cleric":6,"druid":6},
   "classes":{"wizard":6,"sorcerer":6,"cleric":6,"druid":6}},

  # ===== 7环 =====
  {"id":"banishment","nameEn":"Banishment","nameZh":"放逐术",
   "level":7,"school":"防护系","subschool":"","descriptor":"",
   "components":"V,S,DF", "castingTime":"1标准动作","range":"近距",
   "target":"所有在范围内的异界生物","duration":"见描述","savingThrow":"意志过则无效","spellResist":"是",
   "desc":"你尝试放逐一群异界生物回其本有位面。受影响生物需要通过意志检定否则被放逐。如果目标的信念与你不同，法术对其造成1d6点伤害每施法者等级（最高15d6）。",
   "arcane":None,"divine":{"cleric":7},
   "classes":{"cleric":7}},

  {"id":"control_weather","nameEn":"Control Weather","nameZh":"控制天气",
   "level":7,"school":"变化系","subschool":"","descriptor":"",
   "components":"V,S,DF", "castingTime":"10分钟","range":"8英里",
   "target":"以你为中心，半径4英里散布","duration":"4d12小时","savingThrow":"无","spellResist":"否",
   "desc":"你可以改变天气模式。你可以选择：大晴天、大风天、暴雨、暴风雪、浓雾等。天气变化在法术施展后1d4×10分钟后生效。",
   "arcane":None,"divine":{"cleric":7,"druid":7},
   "classes":{"cleric":7,"druid":7}},

  {"id":"creeping_doom","nameEn":"Creeping Doom","nameZh":"爬行厄运",
   "level":7,"school":"咒法学","subschool":"召唤","descriptor":"[虫]",
   "components":"V,S", "castingTime":"1轮","range":"近距",
   "target":"半径20尺散布","duration":"1轮/环","savingThrow":"反射过则减半","spellResist":"否",
   "desc":"你召唤一片虫群（蟑螂、甲虫等）。虫群每轮对区域内所有生物造成2d6点伤害。虫群可以被火攻驱散。",
   "arcane":{"wizard":7,"sorcerer":7},"divine":None,
   "classes":{"wizard":7,"sorcerer":7}},

  {"id":"destruction","nameEn":"Destruction","nameZh":"毁灭术",
   "level":7,"school":"死灵系","subschool":"","descriptor":"[死亡]",
   "components":"V,S,DF", "castingTime":"1标准动作","range":"近距",
   "target":"一个生物","duration":"立即","savingThrow":"强韧过则无效","spellResist":"是",
   "desc":"你需要成功近战接触攻击。命中则目标受到10d6点伤害。如果目标HP降到0以下，则立即死亡（即死效果）。通过强韧检定则只受到5d6点伤害。⚠️ 邪恶法术。",
   "arcane":None,"divine":{"cleric":7},
   "classes":{"cleric":7}},

  {"id":"ethereal_jaunt","nameEn":"Ethereal Jaunt","nameZh":"以太跳跃",
   "level":7,"school":"咒法学","subschool":"传送","descriptor":"",
   "components":"V,S", "castingTime":"1标准动作","range":"个人",
   "target":"你自己","duration":"1轮/环","savingThrow":"无","spellResist":"否",
   "desc":"你跳入以太位面1轮。之后你可以回到物质位面（以一个标准动作）。在以太位面时，你无法互动物质位面。",
   "arcane":{"wizard":7,"sorcerer":7},"divine":None,
   "classes":{"wizard":7,"sorcerer":7}},

  {"id":"grater_teleport","nameEn":"Greater Teleport","nameZh":"高等传送术",
   "level":7,"school":"咒法学","subschool":"传送","descriptor":"",
   "components":"V", "castingTime":"1标准动作","range":"个人和近距",
   "target":"你自己和最多50磅/环的物品","duration":"立即","savingThrow":"无","spellResist":"否",
   "desc":"如同传送术，但你不需要熟悉目的地（「研究过」和「视野内」成功率提升）。你也不会错误传送（除非掷出天然1）。高等传送术是自发施法职业的最佳选择。",
   "arcane":{"wizard":7,"sorcerer":7},"divine":{"cleric":7,"druid":7},
   "classes":{"wizard":7,"sorcerer":7,"cleric":7,"druid":7}},

  {"id":"regenerate","nameEn":"Regenerate","nameZh":"再生术",
   "level":7,"school":"死灵系","subschool":"","descriptor":"[正能量]",
   "components":"V,S,DF", "castingTime":"1标准动作","range":"触碰",
   "target":"触碰的生物","duration":"立即","savingThrow":"意志过则无害","spellResist":"是（无害）",
   "desc":"受术者失去的肢体立即再生。受术者以每轮1HP的速度恢复生命值（无上限）。再生术可以治愈致残效果。",
   "arcane":None,"divine":{"cleric":7},
   "classes":{"cleric":7}},

  {"id":"repulsion","nameEn":"Repulsion","nameZh":"排斥术",
   "level":7,"school":"防护系","subschool":"","descriptor":"",
   "components":"V,S,M", "castingTime":"1标准动作","range":"个人",
   "target":"以你为中心，半径10尺散布","duration":"1轮/环","savingThrow":"意志过则无效","spellResist":"是",
   "desc":"你排斥所有生物（你指定的阵营或生物类型）。被排斥的生物无法接近你（最低5尺）。通过意志检定则不受影响。",
   "material":"价值100gp的铅制护符",
   "arcane":{"wizard":7,"sorcerer":7},"divine":None,
   "classes":{"wizard":7,"sorcerer":7}},

  {"id":"sea_pain","nameEn":"Sea Pain","nameZh":"剧痛之海",
   "level":7,"school":"死灵系","subschool":"","descriptor":"[影响心灵][恐惧]",
   "components":"V,S", "castingTime":"1标准动作","range":"中距",
   "target":"一个生物","duration":"1轮/环","savingThrow":"强韧过则无效","spellResist":"是",
   "desc":"目标受到剧痛（每轮1d6点体质伤害，通过强韧检定则只受到1d6点伤害）。如果目标失败两次，则陷入恐慌。",
   "arcane":{"wizard":7,"sorcerer":7},"divine":None,
   "classes":{"wizard":7,"sorcerer":7}},

  {"id":"spell_turning","nameEn":"Spell Turning","nameZh":"法术反转",
   "level":7,"school":"防护系","subschool":"","descriptor":"",
   "components":"V,S", "castingTime":"1标准动作","range":"触碰",
   "target":"触碰的生物","duration":"1轮/环 或 直到法术被触发","savingThrow":"意志过则无害","spellResist":"是（无害）",
   "desc":"受术者的法术抗力获得+8加值。并且，任何针对受术者的法术有总法术等级（向上取整）的几率反转到施法者身上。",
   "arcane":{"wizard":7,"sorcerer":7},"divine":None,
   "classes":{"wizard":7,"sorcerer":7}},

  {"id":"summon_monster_7","nameEn":"Summon Monster VII","nameZh":"召唤怪物Ⅶ",
   "level":7,"school":"咒法学","subschool":"召唤","descriptor":"",
   "components":"V,S,F", "castingTime":"1轮","range":"近距",
   "target":"见描述","duration":"1轮/环","savingThrow":"无","spellResist":"否",
   "desc":"召唤一个CR7或更低的生物为你作战。常见选择：1个冰元素（大型）、1个石巨人、1个成年铜龙等。",
   "focus":"一个嵌有宝石的小哨子（价值100gp）",
   "arcane":{"wizard":7,"sorcerer":7,"bard":7},"divine":{"cleric":7},
   "classes":{"wizard":7,"sorcerer":7,"bard":7,"cleric":7}},

  {"id":"word_of_chaos","nameEn":"Word of Chaos","nameZh":"混乱真言",
   "level":7,"school":"惑控系","subschool":"强迫","descriptor":"[混乱][语言依赖][影响心灵][听觉]",
   "components":"V", "castingTime":"1标准动作","range":"40尺",
   "target":"所有在范围内的守序生物","duration":"见描述","savingThrow":"无","spellResist":"是",
   "desc":"你说出一个混乱真言。守序生物受到以下效果（基于HD）：HD9或更少→立即死亡；HD10-18→目盲、耳聋、目盲1d4轮；HD19+→目盲1轮。守序生物可以通过强韧检定来减半效果。",
   "arcane":None,"divine":{"cleric":7},
   "classes":{"cleric":7}},
]

fpath = r"C:\Users\wyb\WorkBuddy\2026-06-20-01-52-30\dnd35-wiki-pro\js\spells-data.js"
with open(fpath, 'r', encoding='utf-8') as f:
    content = f.read()

marker = "\n];"
if marker in content:
    insert_pos = content.index(marker)
    entries = ',\n  '.join(json.dumps(sp, ensure_ascii=False, indent=2) for sp in new_spells)
    new_content = content[:insert_pos] + ',\n  ' + entries + content[insert_pos:]
    with open(fpath, 'w', encoding='utf-8') as f:
        f.write(new_content)
    print(f"成功追加 {len(new_spells)} 个法术")
    print(f"新文件行数：{len(new_content.splitlines())}")
else:
    print("未找到 ] 标记")
