#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
为缺失的138个领域法术生成基础数据并添加到spells-data.js
"""

import re

# 定义缺失法术的基础数据
MISSING_SPELLS = {
  # ========== 气领域 ==========
  'gust-of-wind': {
    'nameEn': 'Gust of Wind',
    'nameZh': '阵风',
    'level': 2,
    'school': '变化系',
    'components': 'V, S',
    'castingTime': '标准动作',
    'range': '近距',
    'target': '60尺锥形',
    'duration': '1轮/级',
    'savingThrow': '见描述',
    'spellResist': '是',
    'desc': '你制造一阵强烈的阵风，可以吹灭蜡烛、火炬等小型火焰。',
    'divine': True,
    'classes': {'cleric': 2}
  },
  'invisibility-mundane': {
    'nameEn': 'Invisibility, Mundane',
    'nameZh': '凡物隐形',
    'level': 1,
    'school': '幻术系',
    'components': 'V, S, M',
    'castingTime': '标准动作',
    'range': '触碰',
    'target': '接触的生物或物体',
    'duration': '1分钟/级',
    'savingThrow': '意志通过则无效（物体）',
    'spellResist': '是',
    'desc': '使目标生物或物体变得不可见。',
    'divine': True,
    'classes': {'cleric': 1}
  },
  'air-walk': {
    'nameEn': 'Air Walk',
    'nameZh': '空中行走',
    'level': 4,
    'school': '变化系',
    'components': 'V, S, DF',
    'castingTime': '标准动作',
    'range': '触碰',
    'target': '接触的生物',
    'duration': '10分钟/级',
    'savingThrow': '意志通过则无效（物体）',
    'spellResist': '是',
    'desc': '目标可以在空中行走，如同在实地上行走一样。',
    'divine': True,
    'classes': {'cleric': 4}
  },
  'control-winds': {
    'nameEn': 'Control Winds',
    'nameZh': '控制风力',
    'level': 5,
    'school': '变化系',
    'components': 'V, S, DF',
    'castingTime': '标准动作',
    'range': '2里',
    'target': '以你为中心，2里半径的圆形区域',
    'duration': '10分钟/级',
    'savingThrow': '无',
    'spellResist': '否',
    'desc': '你可以改变指定区域内的风力。',
    'divine': True,
    'classes': {'cleric': 5}
  },
  'chain-lightning': {
    'nameEn': 'Chain Lightning',
    'nameZh': '连锁闪电',
    'level': 6,
    'school': '塑能系',
    'components': 'V, S, F',
    'castingTime': '标准动作',
    'range': '远距',
    'target': '一个主要目标以及额外的次要目标',
    'duration': '立即',
    'savingThrow': '反射通过则减半',
    'spellResist': '是',
    'desc': '释放一道闪电，击中主要目标后会跳跃到附近的其他目标。',
    'arcane': True,
    'divine': False,
    'classes': {'wizard': 6, 'sorcerer': 6}
  },
  'control-weather': {
    'nameEn': 'Control Weather',
    'nameZh': '控制天气',
    'level': 7,
    'school': '变化系',
    'components': 'V, S, M, DF',
    'castingTime': '10分钟',
    'range': '见描述',
    'target': '见描述',
    'duration': '12小时',
    'savingThrow': '无',
    'spellResist': '否',
    'desc': '你可以改变指定区域内的天气。',
    'divine': True,
    'classes': {'cleric': 7, 'druid': 7}
  },
  'whirlwind': {
    'nameEn': 'Whirlwind',
    'nameZh': '旋风',
    'level': 8,
    'school': '塑能系',
    'components': 'V, S, DF',
    'castingTime': '标准动作',
    'range': '远距',
    'target': '见描述',
    'duration': '1轮/级',
    'savingThrow': '反射通过则无效',
    'spellResist': '是',
    'desc': '你制造一个巨大的旋风，可以卷起生物和物体。',
    'divine': True,
    'classes': {'cleric': 8}
  },
  'elemental-swarm-air': {
    'nameEn': 'Elemental Swarm (Air)',
    'nameZh': '元素狂潮（气）',
    'level': 9,
    'school': '咒法系',
    'components': 'V, S, DF',
    'castingTime': '标准动作',
    'range': '近距',
    'target': '见描述',
    'duration': '10分钟/级',
    'savingThrow': '见描述',
    'spellResist': '否',
    'desc': '召唤多个气元素为你作战。',
    'divine': True,
    'classes': {'cleric': 9}
  },
  
  # ========== 动物领域 ==========
  'charm-animal': {
    'nameEn': 'Charm Animal',
    'nameZh': '魅惑动物',
    'level': 1,
    'school': '惑控系',
    'components': 'V, S',
    'castingTime': '标准动作',
    'range': '近距',
    'target': '一个动物',
    'duration': '1小时/级',
    'savingThrow': '意志通过则无效',
    'spellResist': '是',
    'desc': '使一个动物成为你的朋友。',
    'arcane': False,
    'divine': True,
    'classes': {'cleric': 1, 'druid': 1}
  },
  'speak-with-animals': {
    'nameEn': 'Speak with Animals',
    'nameZh': '动物交谈',
    'level': 2,
    'school': '预言系',
    'components': 'V, S',
    'castingTime': '标准动作',
    'range': '个人',
    'target': '自己',
    'duration': '10分钟/级',
    'savingThrow': '无',
    'spellResist': '否',
    'desc': '你可以与动物进行交谈。',
    'divine': True,
    'classes': {'cleric': 2, 'druid': 2, 'ranger': 1}
  },
  'lions-charge': {
    'nameEn': "Lion's Charge",
    'nameZh': '雄狮冲锋',
    'level': 3,
    'school': '变化系',
    'components': 'V, S, DF',
    'castingTime': '标准动作',
    'range': '触碰',
    'target': '接触的生物',
    'duration': '1轮/级',
    'savingThrow': '意志通过则无效（物体）',
    'spellResist': '否',
    'desc': '获得雄狮的力量，可以进行冲锋攻击。',
    'divine': True,
    'classes': {'cleric': 3}
  },
  'divination-animal': {
    'nameEn': 'Divination (Animal)',
    'nameZh': '预言术（动物）',
    'level': 4,
    'school': '预言系',
    'components': 'V, S, M, DF',
    'castingTime': '10分钟',
    'range': '个人',
    'target': '自己',
    'duration': '见描述',
    'savingThrow': '无',
    'spellResist': '否',
    'desc': '询问动物精灵关于未来的问题。',
    'divine': True,
    'classes': {'cleric': 4}
  },
  'beast-shape-i': {
    'nameEn': 'Beast Shape I',
    'nameZh': '野兽形态I',
    'level': 5,
    'school': '变化系',
    'components': 'V, S, DF',
    'castingTime': '标准动作',
    'range': '个人',
    'target': '自己',
    'duration': '1小时/级',
    'savingThrow': '无',
    'spellResist': '否',
    'desc': '你变成小型或中型动物的形状。',
    'arcane': False,
    'divine': True,
    'classes': {'druid': 5}
  },
  'beast-shape-ii': {
    'nameEn': 'Beast Shape II',
    'nameZh': '野兽形态II',
    'level': 6,
    'school': '变化系',
    'components': 'V, S, DF',
    'castingTime': '标准动作',
    'range': '个人',
    'target': '自己',
    'duration': '1小时/级',
    'savingThrow': '无',
    'spellResist': '否',
    'desc': '你变成大型动物的形状。',
    'arcane': False,
    'divine': True,
    'classes': {'druid': 6}
  },
  'beast-shape-iii': {
    'nameEn': 'Beast Shape III',
    'nameZh': '野兽形态III',
    'level': 7,
    'school': '变化系',
    'components': 'V, S, DF',
    'castingTime': '标准动作',
    'range': '个人',
    'target': '自己',
    'duration': '1小时/级',
    'savingThrow': '无',
    'spellResist': '否',
    'desc': '你变成超大型或微小动物的形状。',
    'arcane': False,
    'divine': True,
    'classes': {'druid': 7}
  },
  'beast-shape-iv': {
    'nameEn': 'Beast Shape IV',
    'nameZh': '野兽形态IV',
    'level': 8,
    'school': '变化系',
    'components': 'V, S, DF',
    'castingTime': '标准动作',
    'range': '个人',
    'target': '自己',
    'duration': '1小时/级',
    'savingThrow': '无',
    'spellResist': '否',
    'desc': '你变成巨型动物的形状。',
    'arcane': False,
    'divine': True,
    'classes': {'druid': 8}
  },
  
  # ========== 混乱领域 ==========
  'chaos-hammer': {
    'nameEn': "Chaos Hammer",
    'nameZh': '混乱之锤',
    'level': 2,
    'school': '塑能系',
    'components': 'V, S',
    'castingTime': '标准动作',
    'range': '近距',
    'target': '见描述',
    'duration': '立即',
    'savingThrow': '强韧通过则减半',
    'spellResist': '是',
    'desc': '对守序生物造成伤害并使其颤抖。',
    'divine': True,
    'classes': {'cleric': 2}
  },
  'logic-lapse': {
    'nameEn': 'Logic Lapse',
    'nameZh': '逻辑中断',
    'level': 3,
    'school': '惑控系',
    'components': 'V, S, DF',
    'castingTime': '标准动作',
    'range': '近距',
    'target': '一个守序生物',
    'duration': '1轮/级',
    'savingThrow': '意志通过则无效',
    'spellResist': '是',
    'desc': '使守序生物的逻辑思维暂时中断。',
    'divine': True,
    'classes': {'cleric': 3}
  },
  'fear': {
    'nameEn': 'Fear',
    'nameZh': '恐惧',
    'level': 4,
    'school': '惑控系',
    'components': 'V, S, M',
    'castingTime': '标准动作',
    'range': '近距',
    'target': '见描述',
    'duration': '1轮/级',
    'savingThrow': '意志通过则无效',
    'spellResist': '是',
    'desc': '使目标陷入恐惧状态。',
    'arcane': True,
    'classes': {'wizard': 4, 'sorcerer': 4}
  },
  'chaos-bolt': {
    'nameEn': 'Chaos Bolt',
    'nameZh': '混乱箭',
    'level': 5,
    'school': '塑能系',
    'components': 'V, S',
    'castingTime': '标准动作',
    'range': '近距',
    'target': '一个生物',
    'duration': '立即',
    'savingThrow': '强韧通过则减半',
    'spellResist': '是',
    'desc': '发射一道混乱能量箭矢。',
    'divine': True,
    'classes': {'cleric': 5}
  },
  'chaos-bolt-mass': {
    'nameEn': 'Chaos Bolt, Mass',
    'nameZh': '群体混乱箭',
    'level': 6,
    'school': '塑能系',
    'components': 'V, S',
    'castingTime': '标准动作',
    'range': '近距',
    'target': '多个生物',
    'duration': '立即',
    'savingThrow': '强韧通过则减半',
    'spellResist': '是',
    'desc': '发射多道混乱能量箭矢。',
    'divine': True,
    'classes': {'cleric': 6}
  },
  
  # ========== 死亡领域 ==========
  'bane': {
    'nameEn': 'Bane',
    'nameZh': '厄运',
    'level': 1,
    'school': '惑控系',
    'components': 'V, S, M',
    'castingTime': '标准动作',
    'range': '近距',
    'target': '半径5尺内的所有敌人',
    'duration': '1分钟/级',
    'savingThrow': '意志通过则无效',
    'spellResist': '是',
    'desc': '使敌人的攻击骰和伤害骰承受-1罚值。',
    'divine': True,
    'classes': {'cleric': 1}
  },
  'death-knell': {
    'nameEn': 'Death Knell',
    'nameZh': '死亡丧钟',
    'level': 2,
    'school': '死灵系',
    'components': 'V, S, DF',
    'castingTime': '标准动作',
    'range': '触碰',
    'target': '接触的一个濒死生物',
    'duration': '10分钟/级',
    'savingThrow': '意志通过则无效',
    'spellResist': '是',
    'desc': '吸取濒死生物的能量，获得力量加值。',
    'divine': True,
    'classes': {'cleric': 2}
  },
  'animate-dead': {
    'nameEn': 'Animate Dead',
    'nameZh': '操纵死尸',
    'level': 3,
    'school': '死灵系',
    'components': 'V, S, M',
    'castingTime': '标准动作',
    'range': '近距',
    'target': '尸体',
    'duration': '立即',
    'savingThrow': '无',
    'spellResist': '否',
    'desc': '将尸体转化为不死生物奴仆。',
    'arcane': False,
    'divine': True,
    'classes': {'cleric': 3, 'wizard': 5}
  },
  'create-undead': {
    'nameEn': 'Create Undead',
    'nameZh': '创造不死生物',
    'level': 4,
    'school': '死灵系',
    'components': 'V, S, M',
    'castingTime': '10分钟',
    'range': '近距',
    'target': '尸体',
    'duration': '立即',
    'savingThrow': '无',
    'spellResist': '否',
    'desc': '创造更强大的不死生物。',
    'arcane': False,
    'divine': True,
    'classes': {'cleric': 4, 'wizard': 6}
  },
  'slay-living': {
    'nameEn': 'Slay Living',
    'nameZh': '杀生术',
    'level': 5,
    'school': '死灵系',
    'components': 'V, S, DF',
    'castingTime': '标准动作',
    'range': '触碰',
    'target': '接触的一个生物',
    'duration': '立即',
    'savingThrow': '强韧通过则无效',
    'spellResist': '是',
    'desc': '触碰目标造成大量伤害，可能立即杀死。',
    'divine': True,
    'classes': {'cleric': 5}
  },
  'power-word-blind': {
    'nameEn': 'Power Word Blind',
    'nameZh': '力量真言：盲',
    'level': 7,
    'school': '惑控系',
    'components': 'V',
    'castingTime': '标准动作',
    'range': '近距',
    'target': '一个生物',
    'duration': '见描述',
    'savingThrow': '无',
    'spellResist': '是',
    'desc': '说出真言使目标目盲。',
    'arcane': True,
    'divine': True,
    'classes': {'wizard': 7, 'sorcerer': 7, 'cleric': 7, 'bard': 6}
  },
  'power-word-stun': {
    'nameEn': 'Power Word Stun',
    'nameZh': '力量真言：震慑',
    'level': 8,
    'school': '惑控系',
    'components': 'V',
    'castingTime': '标准动作',
    'range': '近距',
    'target': '一个生物',
    'duration': '见描述',
    'savingThrow': '无',
    'spellResist': '是',
    'desc': '说出真言使目标震慑。',
    'arcane': True,
    'divine': True,
    'classes': {'wizard': 8, 'sorcerer': 8, 'cleric': 8, 'bard': 7}
  },
  'power-word-kill': {
    'nameEn': 'Power Word Kill',
    'nameZh': '力量真言：死',
    'level': 9,
    'school': '惑控系',
    'components': 'V',
    'castingTime': '标准动作',
    'range': '近距',
    'target': '一个生物',
    'duration': '立即',
    'savingThrow': '无',
    'spellResist': '是',
    'desc': '说出真言立即杀死目标。',
    'arcane': True,
    'divine': True,
    'classes': {'wizard': 9, 'sorcerer': 9, 'cleric': 9, 'bard': 8}
  }
}

print(f"定义了 {len(MISSING_SPELLS)} 个缺失法术的基础数据")
print("需要继续添加更多法术数据...")
